@echo off
chcp 65001 >nul
cd /d "%~dp0"
set XGN_SELF_OPTIMIZER_INTERVAL_SECONDS=60
set XGN_SELF_OPTIMIZER_IDLE_UPDATE_MIN_SECONDS=180
set XGN_SELF_OPTIMIZER_ROLEPLAY_UPDATE_MIN_SECONDS=180
set XGN_SELF_OPTIMIZER_BOOK_CANDIDATE_UPDATE_MIN_SECONDS=180
call "%~dp0tools\python_cmd.bat"
"%PYTHON_EXE%" self_optimizer.py daemon %*
