# Auto-generated split runtime module.
# Source: backup/AutoMediaProducer_integrated_postprocess_spec.py lines 1-767.
# Do not edit this file alone; edit the canonical source and run tools/sync_split_runtime.py.

#!/usr/bin/env python3
"""
纯净版 PDF 本地解析工具 + 全 API 自动流水线 (全澜脑科学优化版)
支持：PDF 目录提取 -> 章节 PDF 切分 -> 本地 PyMuPDF4LLM 逐章解析 Markdown -> GPT / Gemini / 豆包 Ark 生成脚本/润色 -> GPT Image 2 / Gemini / ChatShare 生成分镜图片；支持 API 自动调用与网页手动输入双模式
依赖安装:
pip install requests openai google-genai customtkinter pypdf pillow pymupdf4llm pymupdf
安全策略：PDF 只允许本地解析成 Markdown 后发送给大模型；禁止把 PDF 文件作为附件上传给任何大模型。
"""

import os
import re
import time
import random
import queue
from collections import Counter
import threading

runtime_context = threading.local()
POSTPROCESS_RUNTIME_LOCK = threading.RLock()
MAX_PARALLEL_BOOK_TASKS = 1
import subprocess
import platform
import shutil
import tempfile
import unicodedata
import base64
import json
import math
import zipfile
import smtplib
from email.message import EmailMessage
from datetime import datetime, timedelta, timezone
from urllib.parse import quote
import requests
try:
    import customtkinter as ctk
except Exception:
    ctk = None
try:
    import tkinter as tk
    from tkinter import ttk, filedialog, messagebox
except Exception:
    tk = None
    ttk = filedialog = messagebox = None

BASE_SAVE_FOLDER = os.path.abspath("chapter_pdf_direct_output")
WINDOWS_FILE_CLEANUP_RETRIES = int(os.environ.get("QUANLAN_WINDOWS_FILE_CLEANUP_RETRIES", "8"))
WINDOWS_FILE_CLEANUP_SLEEP = float(os.environ.get("QUANLAN_WINDOWS_FILE_CLEANUP_SLEEP", "0.6"))
DIRECT_PDF_TO_LLM_DEFAULT = False  # PDF 只允许本地解析，禁止上传大模型
OPENAI_PDF_UPLOAD_PURPOSE = os.environ.get("OPENAI_PDF_UPLOAD_PURPOSE", "assistants")

# ================== 统一医学插画风格字体 ==================
# 不内置任何字体文件；只在用户系统中按顺序寻找一套中文字体 + 一套英文字体，保证封面/首页/尾页风格一致。
CELL_CN_FONT_CANDIDATES = [
    os.environ.get("QUANLAN_CN_FONT", "").strip(),
    os.environ.get("QUANLAN_UI_FONT", "").strip(),
    "PingFang SC",
    "HarmonyOS Sans SC",
    "MiSans",
    "Source Han Sans SC",
    "Noto Sans CJK SC",
    "Microsoft YaHei UI",
    "Microsoft YaHei",
]
CELL_EN_FONT_CANDIDATES = [
    os.environ.get("QUANLAN_EN_FONT", "").strip(),
    os.environ.get("QUANLAN_UI_FONT", "").strip(),
    "Avenir Next",
    "Avenir",
    "Helvetica Neue",
    "SF Pro Rounded",
    "SF Compact Rounded",
    "Segoe UI Variable",
    "Segoe UI",
    "Arial",
]
CELL_CN_FONT_FALLBACK = os.environ.get("QUANLAN_CN_FONT", "Microsoft YaHei UI").strip() or "Microsoft YaHei UI"
CELL_EN_FONT_FALLBACK = os.environ.get("QUANLAN_EN_FONT", "Segoe UI").strip() or "Segoe UI"

# 兼容旧 UI 入口：UI 控件优先使用中文医学字体。
FRIENDLY_CELL_FONT_CANDIDATES = CELL_CN_FONT_CANDIDATES + CELL_EN_FONT_CANDIDATES
FRIENDLY_CELL_FALLBACK_FONT = CELL_CN_FONT_FALLBACK
IMAGE_FILE_EXTENSIONS = (".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff")


# 默认精简日志：日志按任务页独立保存；界面只显示关键阶段、警告/错误和最终结果。
COMPACT_LOG_MODE = os.environ.get("QUANLAN_COMPACT_LOG", "1").strip().lower() in {"1", "true", "yes", "y", "on"}
COMPACT_LOG_MAX_LINES = int(os.environ.get("QUANLAN_COMPACT_LOG_MAX_LINES", "500") or 500)
COMPACT_LOG_SUPPRESS_RE = re.compile(
    r"("
    r"系统已就绪|已切换到任务|当前已选|输出目录：|"
    r"注入分层生产 raw 图协议|已保存模型原始图备份|内容页安全蒙版|"
    r"手动生成图片请按命名规则保存|详细命名规则已写入|raw=_raw/|"
    r"已读取后处理提示词映射|后处理提示词映射|已同步封面/首页元信息|"
    r"内容图品牌已锁定|封面/首页章节元信息已解析|A页元信息已锁定|"
    r"后处理完成|图片已保存|API 图片已保存|GPT Image 2 图片已保存|"
    r"已保存：|已另存|已原样保存|已剥离并保存|已输出带配图锚点|"
    r"LRC 配图台词对应表已保存|已从纯台词生成 LRC|已从独立台词文件重建 LRC|"
    r"章节名翻译：|书名翻译：|已在完整脚本原稿开头补充|"
    r"目录信息已保存|计时摘要已保存|视频简介已保存|短视频总结已保存|"
    r"正在把章节 PDF 上传|PDF 已上传|file_id=|正在请求 .*API|已完成 PDF 附件直读生成|"
    r"章节 PDF 直传模式|章节 PDF 已准备|正在切出章节 PDF|"
    r"下一章 PDF|下一章真实内容|下一章预告|下一章校验|当前章节结尾|"
    r"完整脚本原稿|图文总脚本|图文一一对应脚本|总脚本为准|"
    r"逐句锁定模式|润色结果已通过逐句锁定校验|"
    r"最终精简输出已清理|最终精简模式已开启|"
    r"已在子目录发现并后处理已有图片|检测到历史输出目录|检测到旧版已操作目录"
    r")",
    re.I,
)
COMPACT_LOG_IMPORTANT_RE = re.compile(
    r"("
    r"已导入书籍 PDF|正在提取 PDF 目录|成功提取|已自动提取|未在 PDF 书签|"
    r"已启动书籍按章流程|开始按章流水线|开始处理章节|章节完成|按章流水线结束|"
    r"正在使用 .*生成章节脚本|正在使用 .*润色|发现已生成的章节脚本|三步骤完成|"
    r"配图状态|所有配图已存在|本章节所有配图已存在|配图完成|图全生成完|"
    r"文件夹后处理开始|文件夹后处理完成|已进入网页手动|网页手动输入模式|"
    r"已请求停止|"
    r"模型方案已保存|内容风格已切换|Key 已保存|提示词与后处理参数已保存|"
    r"AI 已将自然语言|已导出提示词模板|已导入提示词模板|正在调用 .*优化|正在调用 .*规范化|"
    r"章节压缩包|邮件|邮箱|SMTP|已发送"
    r")",
    re.I,
)
COMPACT_LOG_CRITICAL_RE = re.compile(r"(❌|⚠️|失败|错误|异常|不可用|缺少|无效|停止)", re.I)


def compact_log_message_for_display(message: str) -> str | None:
    """把底层运行日志压缩成面向任务页的简洁状态日志；返回 None 表示不显示。"""
    msg = str(message or "").strip()
    if not msg:
        return None
    # 日志已经按任务页隔离，界面内不再重复显示 [任务1] 这类前缀。
    msg = re.sub(r"^\[任务\d+\]\s*", "", msg).strip()
    if not msg:
        return None
    if not COMPACT_LOG_MODE:
        return msg

    # 关键错误/警告必须保留。
    if COMPACT_LOG_CRITICAL_RE.search(msg):
        return msg

    m = re.search(r"已启动书籍按章流程，共选中\s*(\d+)\s*个章节", msg)
    if m:
        return f"🚀 已开始：{m.group(1)} 个章节。"
    m = re.search(r"开始按章流水线处理，共选中\s*(\d+)\s*个章节", msg)
    if m:
        return f"🚀 已开始：{m.group(1)} 个章节。"
    m = re.search(r"开始处理章节 \[(\d+/\d+)\]: \[(.*?)\]", msg)
    if m:
        return f"▶ 章节 {m.group(1)}：{m.group(2).strip()}"
    m = re.search(r"章节完成 \[(\d+/\d+)\]\s*(.*?)：总用时\s*(.*?)（状态：([^）]+)）", msg)
    if m:
        status = m.group(4).strip()
        mark = "✅" if status == "完成" else "⏹️"
        return f"{mark} 章节 {m.group(1)} {status}：用时 {m.group(3).strip()}。"
    m = re.search(r"按章流水线结束。总用时：([^。]+)", msg)
    if m:
        return f"🎉 全部完成：总用时 {m.group(1).strip()}。"
    m = re.search(r"配图状态：共\s*(\d+)\s*张，已完成\s*(\d+)\s*张，待生成\s*(\d+)\s*张", msg)
    if m:
        return f"🎨 配图：共 {m.group(1)} 张，已完成 {m.group(2)} 张，待生成 {m.group(3)} 张。"
    m = re.search(r"正在使用\s*(.*?)\s*生成章节脚本", msg)
    if m:
        return f"🧠 生成脚本：{m.group(1).strip()}。"
    m = re.search(r"正在使用\s*(.*?)\s*单独润色", msg)
    if m:
        return f"🪶 润色台词：{m.group(1).strip()}。"
    m = re.search(r"文件夹后处理开始：.*?图片\s*(\d+)\s*张", msg)
    if m:
        return f"🖼️ 开始后处理图片：{m.group(1)} 张。"
    m = re.search(r"文件夹后处理完成：成功\s*(\d+)\s*张，失败\s*(\d+)\s*张", msg)
    if m:
        return f"✅ 后处理完成：成功 {m.group(1)} 张，失败 {m.group(2)} 张。"

    if COMPACT_LOG_SUPPRESS_RE.search(msg):
        return None
    if COMPACT_LOG_IMPORTANT_RE.search(msg):
        return msg
    return None


def should_suppress_log_message(message: str) -> bool:
    return compact_log_message_for_display(message) is None


def _detect_font_family_from_candidates(candidates, fallback: str, root=None) -> str:
    preferred = [x for x in candidates if x]
    try:
        import tkinter.font as tkfont
        families = set(tkfont.families(root=root))
        lower_map = {f.lower(): f for f in families}
        for name in preferred:
            found = lower_map.get(str(name).lower())
            if found:
                return found
    except Exception:
        pass
    return fallback


def detect_friendly_cell_font(root=None) -> str:
    """检测系统里可用的中文医学插画风格 UI 字体；失败时回退到微软雅黑 UI。"""
    return _detect_font_family_from_candidates(CELL_CN_FONT_CANDIDATES, CELL_CN_FONT_FALLBACK, root=root)


def detect_cell_cn_font(root=None) -> str:
    return _detect_font_family_from_candidates(CELL_CN_FONT_CANDIDATES, CELL_CN_FONT_FALLBACK, root=root)


def detect_cell_en_font(root=None) -> str:
    return _detect_font_family_from_candidates(CELL_EN_FONT_CANDIDATES, CELL_EN_FONT_FALLBACK, root=root)


def clear_generated_image_folder(images_dir: str, logger=None, *, include_raw_backup: bool = True) -> int:
    """清空某个配图目录里的已有图片和 raw 备份，用于强制重新绘制。"""
    if not images_dir:
        return 0
    os.makedirs(images_dir, exist_ok=True)
    removed = 0
    try:
        for name in list(os.listdir(images_dir)):
            path = os.path.join(images_dir, name)
            if os.path.isdir(path):
                if include_raw_backup and name == "_raw":
                    if safe_rmtree(path, logger=logger):
                        removed += 1
                continue
            if name.lower().endswith(IMAGE_FILE_EXTENSIONS):
                if safe_remove_file(path, logger=logger):
                    removed += 1
        if logger:
            logger(f"🧽 已清空旧配图：{images_dir}（删除 {removed} 项）。")
    except Exception as e:
        if logger:
            logger(f"⚠️ 清空旧配图失败：{str(e)[:120]}")
    return removed


os.makedirs(BASE_SAVE_FOLDER, exist_ok=True)

APP_VERSION = "科学经典单任务精简版 v2026.05.27"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
RESEARCH_MODE_DIR = os.path.dirname(os.path.dirname(SCRIPT_DIR))


def _mode_config_path(name: str) -> str:
    mode_path = os.path.join(RESEARCH_MODE_DIR, name)
    if os.path.exists(mode_path):
        return mode_path
    return os.path.join(SCRIPT_DIR, name)


GROK_KEY_FILE = os.path.join(SCRIPT_DIR, "xai_api_key.txt")
GEMINI_KEY_FILE = os.path.join(SCRIPT_DIR, "gemini_api_key.txt")
OPENAI_KEY_FILE = os.path.join(SCRIPT_DIR, "openai_api_key.txt")
IMAGE_KEY_FILE = os.path.join(SCRIPT_DIR, "image_api_key.txt")
CHATSHARE_KEY_FILE = os.path.join(SCRIPT_DIR, "chatshare_api_key.txt")
DEEPSEEK_KEY_FILE = os.path.join(SCRIPT_DIR, "deepseek_api_key.txt")
DOUBAO_KEY_FILE = os.path.join(SCRIPT_DIR, "doubao_api_key.txt")
DOUBAO_ENDPOINT_FILE = os.path.join(SCRIPT_DIR, "doubao_endpoint_id.txt")
DOUBAO_API_BASE_URL = os.environ.get("ARK_API_BASE_URL", "https://ark.cn-beijing.volces.com/api/v3").rstrip("/")
DEFAULT_FOREIGN_MODEL_BASE_URL = "https://www.fhl.mom/v1"
DEFAULT_DEEPSEEK_BASE_URL = "https://api.deepseek.com"
MODEL_SCHEME_FILE = os.environ.get("QUANLAN_MODEL_SCHEME_FILE") or os.path.join(SCRIPT_DIR, "quanlan_model_scheme.json")
TASK_PAGE_SETTINGS_FILE = os.environ.get("QUANLAN_TASK_PAGE_SETTINGS_FILE") or os.path.join(SCRIPT_DIR, "quanlan_task_page_settings.json")
EMAIL_DELIVERY_SETTINGS_FILE = os.environ.get("QUANLAN_EMAIL_DELIVERY_SETTINGS_FILE") or os.path.join(SCRIPT_DIR, "quanlan_email_settings.json")
EMAIL_PACKAGE_DIR_NAME = "99_章节压缩包"

DEFAULT_PROMPT_TEMPLATE_FILE = _mode_config_path("quanlan_default_prompt_templates.json")
PROMPT_TEMPLATE_FILE = _mode_config_path("quanlan_prompt_templates.json")
PROMPT_FRAGMENT_DIR = os.environ.get("QUANLAN_PROMPT_FRAGMENT_DIR") or _mode_config_path("quanlan_prompt_fragments")
CONTENT_STYLE_FILE = _mode_config_path("quanlan_content_styles.json")
DEFAULT_CONTENT_STYLE = "科学经典解读"
CONTENT_STYLE_OPTIONS = ["科学经典解读"]
CONTENT_STYLE_ALIASES = {
    "science": "科学经典解读",
    "scientific": "科学经典解读",
    "科学": "科学经典解读",
    "科学经典": "科学经典解读",
    "脑科学": "科学经典解读",
    "神经科学": "科学经典解读",
}

# 内置脚本生成提示词已删除；请在外部 JSON 配置文件中维护。
DEFAULT_SCRIPT_GENERATION_USER_PROMPT = ""

# 科学经典解读默认脚本生成提示词（优化版）；外部 JSON 缺失时兜底使用。
SCIENCE_CLASSIC_SCRIPT_PROMPT = "请基于本地解析文本生成科学经典解读脚本；完整可调模板见 quanlan_prompt_fragments/script_generation.md。"

# 内置台词润色提示词已删除；请在外部 JSON 配置文件中维护。
DEFAULT_VOICEOVER_POLISH_USER_PROMPT = ""

# 后处理参数默认配置：会显示在“提示词中心 > 后处理参数”里。
# 用户可以直接改 JSON，追加 key=value 简写，或在提示词中心用大模型把自然语言要求规范化为固定 JSON。
DEFAULT_POSTPROCESS_REQUIREMENTS = r"""{
  "coordinate_system": {
    "type": "relative_percent",
    "origin": "top_left",
    "width": "W",
    "height": "H"
  },
  "cover_page": {
    "ratio": "3:4",
    "recommended_size_token_saver": "720x960",
    "recommended_size_high": "1440x1920"
  },
  "home_page": {
    "ratio": "9:16",
    "recommended_size_token_saver": "720x1280",
    "recommended_size_high": "2160x3840"
  },
  "ending_page": {
    "ratio": "9:16",
    "recommended_size_token_saver": "720x1280",
    "recommended_size_high": "1440x2560"
  },
  "background_opacity": {
    "cover": 0.3,
    "home": 0.28,
    "ending": 0.3,
    "range": [
      0.12,
      0.3
    ]
  },
  "center_mask": {
    "cover": {
      "enabled": true,
      "fill": "#FFFFFF",
      "opacity": 0.28,
      "blur": 0,
      "mode": "full_canvas"
    },
    "home": {
      "enabled": true,
      "fill": "#FFFFFF",
      "opacity": 0.24,
      "blur": 0,
      "mode": "full_canvas"
    },
    "ending": {
      "enabled": true,
      "fill": "#FFFFFF",
      "opacity": 0.24,
      "border_radius_ratio_w": 0.0,
      "blur": 0,
      "mode": "full_canvas"
    }
  },
  "content_safe_zone_mask": {
    "enabled": true,
    "top_ratio": 0.2,
    "bottom_ratio": 0.2,
    "fill": "auto",
    "opacity": 0.96,
    "edge_fade_ratio": 0.0,
    "boundary_line_opacity": 0.0
  },
  "cover_layout": {
    "brand_y": 0.06,
    "brand_center_x": 0.5,
    "book_title_cn_y": 0.25,
    "book_title_en_y": 0.335,
    "edition_y": 0.43,
    "author_y": 0.475,
    "chapter_no_y": 0.615,
    "chapter_title_cn_y": 0.695,
    "chapter_title_en_y": 0.78
  },
  "home_layout": {
    "brand_y": 0.07,
    "brand_center_x": 0.5,
    "book_title_cn_y": 0.285,
    "book_title_en_y": 0.355,
    "edition_y": 0.43,
    "author_y": 0.47,
    "chapter_no_y": 0.585,
    "chapter_title_cn_y": 0.655,
    "chapter_title_en_y": 0.725
  },
  "cover_font_size": {
    "brand": 0.039,
    "book_title_cn": 0.073,
    "book_title_en": 0.037,
    "edition": 0.026,
    "author": 0.022,
    "chapter_no": 0.031,
    "chapter_title_cn_max": 0.062,
    "chapter_title_cn_min": 0.038,
    "chapter_title_en": 0.028
  },
  "home_font_size": {
    "brand": 0.03,
    "book_title_cn": 0.056,
    "book_title_en": 0.03,
    "edition": 0.02,
    "author": 0.0185,
    "chapter_no": 0.025,
    "chapter_title_cn_max": 0.048,
    "chapter_title_cn_min": 0.029,
    "chapter_title_en": 0.022
  },
  "chapter_title_cn_dynamic_font": {
    "max_width_ratio": 0.72,
    "line_height": 1.12,
    "align": "center",
    "wrap": true,
    "max_lines": 2
  },
  "ending_layout": {
    "card_x": 0.14,
    "card_y": 0.14,
    "card_width": 0.72,
    "card_height": 0.68,
    "brand_cn_y": 0.345,
    "brand_en_y": 0.418,
    "divider_1_y": 0.47,
    "slogan_cn_y": 0.522,
    "slogan_en_y": 0.572,
    "divider_2_y": 0.62,
    "follow_text_y": 0.674,
    "center_x": 0.5,
    "text_align": "center"
  },
  "ending_font_size": {
    "brand_cn": 0.058,
    "brand_en": 0.03,
    "slogan_cn": 0.036,
    "slogan_en": 0.025,
    "follow_text": 0.03
  },
  "ending_card_style": {
    "fill": "#FFFFFF",
    "opacity": 0.0,
    "border_radius_ratio_w": 0.045,
    "blur": 18,
    "shadow": {
      "enabled": true,
      "opacity": 0.08,
      "blur": 26,
      "offset_y_ratio_h": 0.008
    }
  },
  "ornaments": {
    "cover_brand": {
      "enabled": false,
      "y_offset_ratio_h": 0.02,
      "outer_margin_ratio_w": 0.06,
      "gap_ratio_w": 0.03,
      "dot_radius_ratio_w": 0.0032
    },
    "home_brand": {
      "enabled": false,
      "y_offset_ratio_h": 0.014,
      "outer_margin_ratio_w": 0.15,
      "gap_ratio_w": 0.03,
      "dot_radius_ratio_w": 0.0032
    },
    "home_dividers": {
      "enabled": true,
      "ys": [
        0.535
      ],
      "width_ratio_w": 0.28,
      "dot_radius_ratio_w": 0.003
    },
    "ending_dividers": {
      "enabled": true,
      "width_ratio_w": 0.5,
      "dot_radius_ratio_w": 0.0036
    },
    "cover_dividers": {
      "enabled": true,
      "ys": [
        0.57
      ],
      "width_ratio_w": 0.34,
      "dot_radius_ratio_w": 0.0032
    }
  },
  "colors": {
    "primary_text": "#132A52",
    "secondary_text": "#223A5F",
    "light_line": "#9CB3CC",
    "background_tint": "#EEF5FB"
  },
  "font_weight": {
    "brand": 600,
    "book_title_cn": 700,
    "book_title_en": 500,
    "edition": 500,
    "author": 400,
    "chapter_no": 500,
    "chapter_title_cn": 700,
    "chapter_title_en": 500,
    "ending_brand_cn": 700,
    "ending_slogan_cn": 600
  },
  "content_reference_lines": {
    "enabled": false,
    "show_safe_boundaries": false,
    "show_subtitle_line": false,
    "top_y_ratio": 0.2,
    "bottom_y_ratio": 0.8,
    "subtitle_y_ratio": 0.8,
    "margin_x_ratio": 0.08,
    "width_ratio": 0.0014,
    "dash_ratio": 0.018,
    "gap_ratio": 0.01,
    "color": "#6B8FAE",
    "opacity": 0.26
  }
}"""


PROMPT_TEMPLATE_KEYS = ("script_generation", "voiceover_polish", "postprocess_requirements")
PROMPT_FRAGMENT_KEY_FILES = {
    "script_generation": "script_generation.md",
    "voiceover_polish": "voiceover_polish.md",
    "postprocess_requirements": "postprocess_requirements.json",
}


def load_prompt_fragment(name: str, fallback: str = "") -> str:
    """读取外置提示词片段；用于把所有可调提示词从 Python 逻辑中拆出来。"""
    safe = str(name or "").strip().replace("\\", "/").split("/")[-1]
    if not safe:
        return str(fallback or "")
    path = os.path.join(PROMPT_FRAGMENT_DIR, safe)
    try:
        if os.path.exists(path):
            text = open(path, "r", encoding="utf-8").read().strip()
            if text:
                return text
    except Exception:
        pass
    return str(fallback or "")


def render_prompt_fragment(name: str, values: dict | None = None, fallback: str = "") -> str:
    return render_prompt_template(load_prompt_fragment(name, fallback), values or {})



def builtin_prompt_templates() -> dict:
    """代码内置兜底模板。正常情况下，默认模板从外部 JSON 文件读取。"""
    return {
        "script_generation": DEFAULT_SCRIPT_GENERATION_USER_PROMPT,
        "voiceover_polish": DEFAULT_VOICEOVER_POLISH_USER_PROMPT,
        "postprocess_requirements": DEFAULT_POSTPROCESS_REQUIREMENTS,
    }


def _script_generation_template_needs_visual_upgrade(template: str) -> bool:
    """保留兼容入口：不再检测或改写脚本生成模板里的绘图提示词。"""
    return False


def _upgrade_visual_prompt_template_if_needed(templates: dict) -> dict:
    """不再自动升级/优化绘图提示词模板；用户配置原样保留。"""
    return dict(templates or {})


def _normalize_prompt_templates(data: dict | None, fallback: dict | None = None) -> dict:
    """只保留程序支持的两个提示词槽位；空字段用 fallback 回补。"""
    base = dict(fallback or builtin_prompt_templates())
    if isinstance(data, dict):
        for key in PROMPT_TEMPLATE_KEYS:
            value = data.get(key, "")
            if isinstance(value, str) and value.strip():
                base[key] = value.strip()
    # 外置片段优先，方便单独优化提示词而不改 Python 或 JSON。
    for key, filename in PROMPT_FRAGMENT_KEY_FILES.items():
        fragment = load_prompt_fragment(filename, "")
        if fragment.strip():
            base[key] = fragment.strip()
    return base


def _read_prompt_template_json(path: str) -> dict | None:
    try:
        if path and os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            return data if isinstance(data, dict) else None
    except Exception:
        return None
    return None


def _write_prompt_template_json(path: str, templates: dict, *, content_style: str | None = None) -> bool:
    try:
        payload = _normalize_prompt_templates(templates)
        if content_style:
            payload["_content_style"] = normalize_content_style(content_style)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2)
        return True
    except Exception:
        return False


def normalize_content_style(value: str | None) -> str:
    raw = str(value or "").strip()
    if raw in CONTENT_STYLE_OPTIONS:
        return raw
    lowered = raw.lower()
    if lowered in CONTENT_STYLE_ALIASES:
        return CONTENT_STYLE_ALIASES[lowered]
    if raw in CONTENT_STYLE_ALIASES:
        return CONTENT_STYLE_ALIASES[raw]
    return DEFAULT_CONTENT_STYLE


def get_active_content_style() -> str:
    """直接读取当前风格；多任务线程优先使用自己的风格，避免 3 本书并行时互相覆盖。"""
    try:
        runtime_style = getattr(runtime_context, "content_style", "")
        if runtime_style:
            return normalize_content_style(runtime_style)
    except Exception:
        pass
    try:
        if os.path.exists(MODEL_SCHEME_FILE):
            with open(MODEL_SCHEME_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)
            if isinstance(data, dict):
                return normalize_content_style(data.get("content_style"))
    except Exception:
        pass
    return DEFAULT_CONTENT_STYLE


SCIENCE_ONLY_OUTPUT_STABILITY_SUPPLEMENT = """
【科学经典单风格硬约束】
本工程只做“科学经典解读”，不要输出与科学著作解读无关的内容。脚本必须以章节原文中的科学问题、结构、机制、证据、实验、因果链和概念边界为主线。

【开头三句硬约束】
1. 章节介绍前必须先有钩子：第1句必须是贴近日常生活、并且直连本章主要科学内容的疑问句，例如“那大脑到底如何同时处理成千上万的信号？”不要用“本章主要讲了”开头。
2. 第2句把这个生活疑问自然过渡到本章的核心科学问题。
3. 第3句必须是 A2 首页章节提要句，必须以“在由{author_voiceover_credit}《{book_name_cn}》的{chapter_number}中，我们将讨论{chapter_title_cn}：”开头；书名只用简要中文名，作者只用第一作者简名，合著书写成“XXX等人合著”，不得写成“在《书名》作者的第X章中”。不得在台词开头念英文长书名、版次、出版社、ISBN、editor 全称或资料提取痕迹。

【固定平台图硬约束】
Production Asset Plan 必须绘制四张固定平台图：
- Shot_01：A1. WeChat Cover Page，最终 3:4。
- Shot_02：A2. WeChat Home Page，最终 9:16，绑定第3句章节提要。
- Shot_03：A01. Bilibili Cover Page，最终 4:3。
- Shot_04：A02. Bilibili Home Page，最终 16:9。
A1、A2、A01、A02 使用同一张“整章内容总结”无字背景：背景必须概括本章核心机制/结构/证据/问题关系，不要泛用脑图或装饰海报。四张图的 raw image 都不得出现任何文字、logo、数字、水印或伪文字；公共文字全部由程序后处理。
四张固定平台图的 Text Overlay Spec 必须显式保留同一组字段：Brand、Book Title、Book Title CN、Version、Author、Chapter Number、Chapter Title EN、Chapter Title CN。蒙版必须是 full_canvas，不允许只在中间画一个方块。

【B/C 图硬约束】
B 系列从 Shot_05 开始，只做章节正文的科学机制、证据、实验或结构图解；C 为结尾品牌页，但 C 的 raw 背景也必须是本章全章总结背景，回扣本章核心问题、机制/证据链与结论边界，不得退化为品牌氛围图、泛脑科学背景或柔和装饰图。所有图片提示词都必须可解析 Page Type，并保持无字 raw image。
"""

SCIENCE_CLASSIC_POLISH_PROMPT = "请在不改变原意和科学边界的前提下润色台词；完整可调模板见 quanlan_prompt_fragments/voiceover_polish.md。\n\n{voiceover_text}"

def _minimal_style_templates(style_key: str) -> dict:
    """兜底模板：锁定科学经典解读，不再提供其它风格模板。"""
    base = builtin_prompt_templates()
    base["script_generation"] = load_prompt_fragment("script_generation.md", (SCIENCE_CLASSIC_SCRIPT_PROMPT + "\n\n" + SCIENCE_ONLY_OUTPUT_STABILITY_SUPPLEMENT).strip())
    base["voiceover_polish"] = load_prompt_fragment("voiceover_polish.md", SCIENCE_CLASSIC_POLISH_PROMPT)
    return _normalize_prompt_templates(base, builtin_prompt_templates())


def _upgrade_builtin_style_templates(style_key: str, templates: dict) -> tuple[dict, bool]:
    """科学著作解读单风格：任何旧风格模板都归一到科学模板，不再迁移/保留其它内容分支。"""
    style_key = DEFAULT_CONTENT_STYLE
    cleaned = _normalize_prompt_templates(templates or {}, _minimal_style_templates(style_key))
    # 只要模板里出现旧风格品牌或非科学风格痕迹，就直接回落到科学外置模板。
    probe = "\n".join(str(cleaned.get(k, "")) for k in ("script_generation", "voiceover_polish", "postprocess_requirements"))
    required_markers = (
        "顶级审片身份",
        "正确废话",
        "每张 B 图必须有可见的机制对象",
    )
    if re.search(r"非科学著作解读|剧情流水账", probe) or any(marker not in probe for marker in required_markers):
        return _minimal_style_templates(style_key), True
    return cleaned, False


def _load_content_style_store() -> dict:
    data = _read_prompt_template_json(CONTENT_STYLE_FILE)
    if not isinstance(data, dict):
        data = {}
    styles = data.get("styles") if isinstance(data.get("styles"), dict) else {}
    changed = False
    for style_key in CONTENT_STYLE_OPTIONS:
        if style_key not in styles or not isinstance(styles.get(style_key), dict):
            styles[style_key] = {"label": style_key, "templates": _minimal_style_templates(style_key)}
            changed = True
        else:
            templates = styles[style_key].get("templates") if isinstance(styles[style_key].get("templates"), dict) else styles[style_key]
            templates, upgraded = _upgrade_builtin_style_templates(style_key, templates)
            normalized = _normalize_prompt_templates(templates, _minimal_style_templates(style_key))
            if upgraded or styles[style_key].get("templates") != normalized:
                styles[style_key]["templates"] = normalized
                changed = True
    store = {"version": data.get("version", 1), "styles": styles}
    if changed or not os.path.exists(CONTENT_STYLE_FILE):
        try:
            with open(CONTENT_STYLE_FILE, "w", encoding="utf-8") as f:
                json.dump(store, f, ensure_ascii=False, indent=2)
        except Exception:
            pass
    return store


def get_content_style_templates(style_key: str | None = None) -> dict:
    style_key = normalize_content_style(style_key or get_active_content_style())
    try:
        store = _load_content_style_store()
        style_data = (store.get("styles") or {}).get(style_key, {})
        templates = style_data.get("templates") if isinstance(style_data.get("templates"), dict) else style_data
        return _normalize_prompt_templates(templates, _minimal_style_templates(style_key))
    except Exception:
        return _minimal_style_templates(style_key)


def save_content_style_templates(style_key: str | None, templates: dict) -> bool:
    style_key = normalize_content_style(style_key or get_active_content_style())
    cleaned = _normalize_prompt_templates(templates, get_content_style_templates(style_key))
    try:
        store = _load_content_style_store()
        styles = store.setdefault("styles", {})
        current = styles.get(style_key, {}) if isinstance(styles.get(style_key), dict) else {}
        current["label"] = style_key
        current["templates"] = cleaned
        styles[style_key] = current
        with open(CONTENT_STYLE_FILE, "w", encoding="utf-8") as f:
            json.dump(store, f, ensure_ascii=False, indent=2)
        return True
    except Exception:
        return False


def ensure_default_prompt_template_file(style_key: str | None = None) -> dict:
    """
    确保默认提示词可用。新版优先使用 quanlan_content_styles.json 中的当前风格模板；
    旧版 quanlan_default_prompt_templates.json 继续作为兼容兜底。
    """
    style_key = normalize_content_style(style_key or get_active_content_style())
    style_templates = get_content_style_templates(style_key)
    if style_templates:
        return style_templates
    builtin = builtin_prompt_templates()
    data = _read_prompt_template_json(DEFAULT_PROMPT_TEMPLATE_FILE)
    if data is None:
        _write_prompt_template_json(DEFAULT_PROMPT_TEMPLATE_FILE, builtin)
        return builtin
    defaults = _upgrade_visual_prompt_template_if_needed(_normalize_prompt_templates(data, builtin))
    if defaults != data:
        _write_prompt_template_json(DEFAULT_PROMPT_TEMPLATE_FILE, defaults)
    return defaults


def default_prompt_templates(style_key: str | None = None) -> dict:
    """读取指定内容风格的默认提示词配置。"""
    return ensure_default_prompt_template_file(style_key)


def load_prompt_templates(style_key: str | None = None) -> dict:
    """读取当前风格提示词模板；缺失字段自动回补该风格默认模板。"""
    style_key = normalize_content_style(style_key or get_active_content_style())
    templates = default_prompt_templates(style_key)
    data = _read_prompt_template_json(PROMPT_TEMPLATE_FILE)
    if data is not None:
        marker = normalize_content_style(data.get("_content_style")) if data.get("_content_style") else ""
        # 当前程序只做科学著作解读；旧版无标记模板也只能并入科学模板，禁止恢复其它内容风格。
        if marker == DEFAULT_CONTENT_STYLE or not marker:
            templates = _normalize_prompt_templates(data, templates)
    templates = _upgrade_visual_prompt_template_if_needed(templates)
    return templates


def save_prompt_templates(templates: dict, style_key: str | None = None) -> bool:
    """保存当前风格的运行提示词模板，同时写回风格配置。"""
    style_key = normalize_content_style(style_key or get_active_content_style())
    cleaned = _normalize_prompt_templates(templates, default_prompt_templates(style_key))
    ok_style = save_content_style_templates(style_key, cleaned)
    ok_current = _write_prompt_template_json(PROMPT_TEMPLATE_FILE, cleaned, content_style=style_key)
    return bool(ok_style and ok_current)


def save_default_prompt_templates(templates: dict, style_key: str | None = None) -> bool:
    """把当前提示词写入当前内容风格的默认模板配置。"""
    style_key = normalize_content_style(style_key or get_active_content_style())
    cleaned = _normalize_prompt_templates(templates, _minimal_style_templates(style_key))
    return save_content_style_templates(style_key, cleaned)


def render_prompt_template(template: str, values: dict) -> str:
    """用简单替换渲染模板，避免 str.format 误伤提示词里的花括号。支持 {{key}} 和 {key} 两种占位符。"""
    result = str(template or "")
    for key, value in (values or {}).items():
        value = str(value if value is not None else "")
        result = result.replace("{{" + key + "}}", value)
        result = result.replace("{" + key + "}", value)
    return result.strip()
