# Auto-generated split runtime module.
# Source: backup/AutoMediaProducer_integrated_postprocess_spec.py lines 768-2234.
# Do not edit this file alone; edit the canonical source and run tools/sync_split_runtime.py.



# ================== 运行稳定性参数：集中管理，避免散落的魔法数字 ==================
# ================== 省 token 模式：默认开启 ==================
# 关闭方法：运行前设置 QUANLAN_TOKEN_SAVER_MODE=0
TOKEN_SAVER_MODE = os.environ.get("QUANLAN_TOKEN_SAVER_MODE", "1").strip().lower() in {"1", "true", "yes", "y", "on"}

# v97：绘图提示词省 token。公共元素由后处理统一绘制，所以 API 只需要“主体画面 + 短硬规则”。
# 可用环境变量调节：QUANLAN_IMAGE_API_PROMPT_BUDGET_CHARS=820/1000/1400。
IMAGE_API_PROMPT_BUDGET_CHARS = int(os.environ.get("QUANLAN_IMAGE_API_PROMPT_BUDGET_CHARS", "1800" if TOKEN_SAVER_MODE else "2400"))
IMAGE_BODY_PROMPT_BUDGET_CHARS = int(os.environ.get("QUANLAN_IMAGE_BODY_PROMPT_BUDGET_CHARS", str(max(900, IMAGE_API_PROMPT_BUDGET_CHARS - 420))))

SCRIPT_CONTEXT_CHAR_LIMIT = int(os.environ.get("QUANLAN_SCRIPT_CONTEXT_CHAR_LIMIT", "18000" if TOKEN_SAVER_MODE else "36000"))
NEXT_CHAPTER_CONTEXT_CHAR_LIMIT = int(os.environ.get("QUANLAN_NEXT_CHAPTER_CONTEXT_CHAR_LIMIT", "6000" if TOKEN_SAVER_MODE else "16000"))
IMAGE_PROMPT_COMPACT_MODE = os.environ.get("QUANLAN_IMAGE_PROMPT_COMPACT_MODE", "1" if TOKEN_SAVER_MODE else "0").strip().lower() in {"1", "true", "yes", "y", "on"}
IMAGE_PROMPT_MAX_CHARS = int(os.environ.get("QUANLAN_IMAGE_PROMPT_MAX_CHARS", "0"))  # v8.2: 0 = compact模式也不按字符截断
# v6.6：提示词长度硬约束。脚本模型输出、落盘提示词、最终 API Prompt 三层都限制长度，避免长提示词稀释语义锁。
IMAGE_PROMPT_SOURCE_MAX_CHARS = int(os.environ.get("QUANLAN_IMAGE_PROMPT_SOURCE_MAX_CHARS", "0"))  # v8.2: 0 = 不截断落盘绘图提示词
IMAGE_PROMPT_B_SOURCE_MAX_CHARS = int(os.environ.get("QUANLAN_IMAGE_PROMPT_B_SOURCE_MAX_CHARS", "0"))  # v8.2: 0 = B图提示词不截断
IMAGE_PROMPT_AC_SOURCE_MAX_CHARS = int(os.environ.get("QUANLAN_IMAGE_PROMPT_AC_SOURCE_MAX_CHARS", "0"))  # v8.2: 0 = A/C提示词不截断
IMAGE_API_HARD_MAX_CHARS = int(os.environ.get("QUANLAN_IMAGE_API_HARD_MAX_CHARS", "0"))  # v8.2: 0 = 最终API提示词不硬截断
OPENAI_TEXT_MAX_OUTPUT_TOKENS = int(os.environ.get("OPENAI_TEXT_MAX_OUTPUT_TOKENS", "8000" if TOKEN_SAVER_MODE else "16000"))
CHATSHARE_TEXT_MAX_OUTPUT_TOKENS = int(os.environ.get("CHATSHARE_TEXT_MAX_OUTPUT_TOKENS", str(OPENAI_TEXT_MAX_OUTPUT_TOKENS)))
GROK_TEXT_MAX_OUTPUT_TOKENS = int(os.environ.get("GROK_TEXT_MAX_OUTPUT_TOKENS", str(OPENAI_TEXT_MAX_OUTPUT_TOKENS)))
OPENAI_REASONING_EFFORT = os.environ.get("OPENAI_REASONING_EFFORT", "medium" if TOKEN_SAVER_MODE else "high")
# LRC 只负责最终字幕时间戳；默认按 30 秒写时间点，方便剪辑软件留出手动调整空间；不参与镜头/台词切分。
LRC_INTERVAL_SECONDS = int(os.environ.get("QUANLAN_LRC_INTERVAL_SECONDS", "30"))

# 分镜密度控制：脚本阶段按 3~8 秒/镜头同步规划台词和医学配图；LRC 时间戳不参与切分。
TARGET_SECONDS_PER_IMAGE = float(os.environ.get("QUANLAN_TARGET_SECONDS_PER_IMAGE", "4.0"))
MIN_SECONDS_PER_IMAGE = float(os.environ.get("QUANLAN_MIN_SECONDS_PER_IMAGE", "3.0"))
MAX_SECONDS_PER_IMAGE = float(os.environ.get("QUANLAN_MAX_SECONDS_PER_IMAGE", "8.0"))
MIN_CHAPTER_TOTAL_SECONDS = int(os.environ.get("QUANLAN_MIN_CHAPTER_TOTAL_SECONDS", "180"))
MAX_CHAPTER_TOTAL_SECONDS = int(os.environ.get("QUANLAN_MAX_CHAPTER_TOTAL_SECONDS", "300"))
MIN_TOTAL_IMAGE_COUNT = int(os.environ.get("QUANLAN_MIN_TOTAL_IMAGE_COUNT", "45"))
MAX_TOTAL_IMAGE_COUNT = int(os.environ.get("QUANLAN_MAX_TOTAL_IMAGE_COUNT", "72"))
FIXED_NON_CONTENT_IMAGE_COUNT = 4  # A1 封面 + A2 首页 + C 微信短视频品牌页 + C B站品牌页
MIN_B_CONTENT_IMAGE_COUNT = int(os.environ.get("QUANLAN_MIN_B_CONTENT_IMAGE_COUNT", "42"))
DYNAMIC_VISUAL_DENSITY_BOOST = int(os.environ.get("QUANLAN_VISUAL_DENSITY_BOOST", "20"))
IMAGE_SUCCESS_SLEEP_SECONDS = float(os.environ.get("QUANLAN_IMAGE_SUCCESS_SLEEP_SECONDS", "4"))
IMAGE_FAILURE_SLEEP_SECONDS = float(os.environ.get("QUANLAN_IMAGE_FAILURE_SLEEP_SECONDS", "2"))
LOCAL_IMAGE_SUCCESS_SLEEP_SECONDS = float(os.environ.get("QUANLAN_LOCAL_IMAGE_SUCCESS_SLEEP_SECONDS", "1"))
LOCAL_IMAGE_FAILURE_SLEEP_SECONDS = float(os.environ.get("QUANLAN_LOCAL_IMAGE_FAILURE_SLEEP_SECONDS", "1"))


def format_elapsed_time(seconds: float) -> str:
    """把秒数格式化为适合日志阅读的用时文本。"""
    try:
        total = max(0, int(round(float(seconds))))
    except Exception:
        total = 0
    hours, rem = divmod(total, 3600)
    minutes, secs = divmod(rem, 60)
    if hours:
        return f"{hours}小时{minutes}分{secs}秒"
    if minutes:
        return f"{minutes}分{secs}秒"
    return f"{secs}秒"


def save_timing_summary(out_dir: str, title: str, records: list, overall_seconds: float, logger=None) -> str:
    """保存按章运行计时摘要，便于复盘每个章节总耗时。"""
    os.makedirs(out_dir, exist_ok=True)
    summary_path = os.path.join(out_dir, "运行计时摘要.txt")
    lines = []
    lines.append(f"任务：{title}")
    lines.append(f"生成时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"总用时：{format_elapsed_time(overall_seconds)}")
    lines.append("")
    lines.append("章节用时：")
    for rec in records:
        lines.append(
            f"{rec.get('index', '')}. {rec.get('title', '')} | "
            f"状态：{rec.get('status', '完成')} | "
            f"用时：{format_elapsed_time(rec.get('seconds', 0))}"
        )
    with open(summary_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    if logger:
        logger(f"📝 计时摘要已保存：{summary_path}")
    return summary_path


def is_nonempty_file(path: str, min_bytes: int = 20) -> bool:
    """判断文件是否存在且不是空文件，用于断点续跑。"""
    try:
        return bool(path) and os.path.exists(path) and os.path.getsize(path) >= min_bytes
    except Exception:
        return False


def _env_bool(name: str, default: bool = True) -> bool:
    """读取布尔环境变量；用于控制断点续作是否跳过已有产物。"""
    raw = os.environ.get(name)
    if raw is None:
        return bool(default)
    return str(raw).strip().lower() in {"1", "true", "yes", "y", "on"}


def unified_intermediate_files_enabled() -> bool:
    """默认合并冗余中间文件：最终台词直接复用主脚本文件，不再另存同义副本。"""
    return _env_bool("QUANLAN_UNIFIED_INTERMEDIATE_FILES", True)


def save_raw_script_backup_enabled() -> bool:
    """完整原稿较长且可由模型提示复现，默认不落盘；排查时可设为 1。"""
    return _env_bool("QUANLAN_SAVE_RAW_SCRIPT_BACKUP", False)


def save_image_api_prompt_sidecars_enabled() -> bool:
    """每张图的完整 API 提示词副本体积较大，默认只保存 hash 用于断点校验。"""
    return _env_bool("QUANLAN_SAVE_IMAGE_API_PROMPT_SIDECARS", False)


def resume_skip_existing_enabled() -> bool:
    """默认开启：已有有效文件直接复用，不重复解析/生成/后处理。"""
    return _env_bool("QUANLAN_RESUME_SKIP_EXISTING", True)


def resume_force_rebuild_enabled() -> bool:
    """默认关闭：需要强制重跑已有产物时，把环境变量设为 1/true。"""
    return _env_bool("QUANLAN_FORCE_REBUILD_EXISTING", False) or _env_bool("QUANLAN_FORCE_REBUILD", False)


def resume_strict_image_prompt_match_enabled() -> bool:
    """默认关闭：已有图片即视为完成；开启后才按 Prompt 指纹不一致重绘。"""
    return _env_bool("QUANLAN_RESUME_STRICT_IMAGE_PROMPT_MATCH", False)


def resume_touch_existing_images_enabled() -> bool:
    """默认关闭：断点续作时不重新后处理已有图片，避免改动旧文件。"""
    return _env_bool("QUANLAN_RESUME_TOUCH_EXISTING_IMAGES", False)


def should_reuse_existing_file(path: str, min_bytes: int = 20) -> bool:
    """统一的断点续作文件复用判断。"""
    return resume_skip_existing_enabled() and (not resume_force_rebuild_enabled()) and is_nonempty_file(path, min_bytes=min_bytes)


def _read_simple_kv_value(text: str, key: str) -> str:
    try:
        m = re.search(rf"(?im)^\s*{re.escape(str(key or ''))}\s*[：:]\s*(.+?)\s*$", str(text or ""))
        return m.group(1).strip() if m else ""
    except Exception:
        return ""


def load_cover_home_metadata_value(ch_dir: str, key: str) -> str:
    """从已有封面/首页元信息缓存读取字段，避免断点续作时再次调用翻译模型。

    章节名缓存必须防污染：如果旧缓存误把“20_分镜图片_最终输出”等流程目录名
    当成 Chapter Title CN/EN，直接视为无效，触发重新写入。
    """
    try:
        path = os.path.join(ch_dir, "0_封面首页元信息.txt")
        if not is_nonempty_file(path, min_bytes=20):
            return ""
        value = _read_simple_kv_value(read_text_file(path), key)
        artifact_check = globals().get("_is_cover_home_workflow_title_artifact")
        key_l = str(key or "").lower()
        if callable(artifact_check) and any(x in key_l for x in ("chapter title", "章节名")) and artifact_check(value):
            return ""
        return value
    except Exception:
        return ""


def safe_filename(text: str, max_len: int = 180, fallback: str = "untitled") -> str:

    """生成 Windows/macOS/Linux 都安全的文件夹名，避免章节标题中的非法字符破坏输出路径。"""
    name = re.sub(r'[\\/*?:"<>|]', "_", str(text or "")).strip(' ._')
    name = re.sub(r"\s+", " ", name).strip()

    return (name[:max_len].strip(' ._') or fallback)


def decode_text_bytes(raw: bytes, default: str = "") -> str:
    """多编码兜底解码，优先保证中文 Markdown / OCR 文本不乱码。"""
    if raw is None:
        return default
    if isinstance(raw, str):
        return raw
    if not isinstance(raw, (bytes, bytearray)):
        try:
            return str(raw)
        except Exception:
            return default
    data = bytes(raw)
    if not data:
        return default
    # 先处理 BOM / 常见 Unicode 编码，再尝试中文环境常见编码。
    encodings = [
        "utf-8-sig", "utf-8", "gb18030", "gbk", "big5", "utf-16", "utf-16-le", "utf-16-be", "cp1252", "latin-1"
    ]
    best_text = None
    best_score = -10**9
    for enc in encodings:
        try:
            txt = data.decode(enc, errors="replace")
        except Exception:
            continue
        # 评分：少替换字符、少控制字符、有中文/英文可读字符、不过度乱码。
        replacement_count = txt.count("�")
        control_count = sum(1 for ch in txt if ord(ch) < 32 and ch not in "\n\r\t")
        cn_count = len(re.findall(r"[\u4e00-\u9fff]", txt))
        ascii_word_count = len(re.findall(r"[A-Za-z]{2,}", txt))
        printable_count = sum(1 for ch in txt if ch.isprintable() or ch in "\n\r\t")
        score = cn_count * 3 + ascii_word_count + printable_count * 0.01 - replacement_count * 80 - control_count * 10
        if score > best_score:
            best_score = score
            best_text = txt
        # UTF-8 无替换通常已经最可信。
        if enc in {"utf-8-sig", "utf-8"} and replacement_count == 0 and txt.strip():
            return txt
    return best_text if best_text is not None else default


def read_text_file(path: str, default: str = "") -> str:
    """统一文本读取，自动尝试 utf-8 / gb18030 / gbk / big5 等多种编码。"""
    try:
        with open(path, "rb") as f:
            return decode_text_bytes(f.read(), default=default)
    except Exception:
        return default


def write_text_file(path: str, text: str) -> None:
    """统一文本写入，自动创建父目录。"""
    folder = os.path.dirname(os.path.abspath(path))
    if folder:
        os.makedirs(folder, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(str(text or ""))


def safe_remove_file(path: str, logger=None, *, retries: int | None = None, sleep_seconds: float | None = None) -> bool:
    """Windows 友好的安全删除：外部 PDF 解析器短暂占用文件时，不让流程崩溃。"""
    if not path or not os.path.exists(path):
        return True
    retries = WINDOWS_FILE_CLEANUP_RETRIES if retries is None else max(1, int(retries))
    sleep_seconds = WINDOWS_FILE_CLEANUP_SLEEP if sleep_seconds is None else max(0.05, float(sleep_seconds))
    last_err = None
    for i in range(retries):
        try:
            os.remove(path)
            return True
        except PermissionError as e:
            last_err = e
            time.sleep(min(5.0, sleep_seconds * (i + 1)))
        except FileNotFoundError:
            return True
        except Exception as e:
            last_err = e
            time.sleep(min(5.0, sleep_seconds * (i + 1)))
    if logger:
        logger(f"⚠️ 临时文件暂时无法删除，可能仍被外部解析器占用；已跳过，不影响后续流程：{path}；原因：{str(last_err)[:120]}")
    return False


def safe_rmtree(path: str, logger=None, *, retries: int | None = None, sleep_seconds: float | None = None) -> bool:
    """Windows 友好的目录删除：PermissionError/WinError 32 时重试，最终失败也不抛出。"""
    if not path or not os.path.exists(path):
        return True
    retries = WINDOWS_FILE_CLEANUP_RETRIES if retries is None else max(1, int(retries))
    sleep_seconds = WINDOWS_FILE_CLEANUP_SLEEP if sleep_seconds is None else max(0.05, float(sleep_seconds))
    last_err = None

    def _onerror(func, p, exc_info):
        try:
            os.chmod(p, 0o700)
            func(p)
        except Exception:
            pass

    for i in range(retries):
        try:
            shutil.rmtree(path, onerror=_onerror)
            return True
        except PermissionError as e:
            last_err = e
            time.sleep(min(5.0, sleep_seconds * (i + 1)))
        except FileNotFoundError:
            return True
        except Exception as e:
            last_err = e
            time.sleep(min(5.0, sleep_seconds * (i + 1)))
    if logger:
        logger(f"⚠️ 临时目录暂时无法清理，可能有文件句柄未释放；已跳过，不影响后续流程：{path}；原因：{str(last_err)[:120]}")
    return False



def ascii_safe_filename(text: str, max_len: int = 80, fallback: str = "upload.pdf") -> str:
    """生成只含 ASCII 的上传文件名，避免 Windows 中文路径/文件名进入 multipart header 后触发 ascii codec 错误。"""
    raw = str(text or "").strip() or fallback
    stem, ext = os.path.splitext(raw)
    if not ext:
        ext = os.path.splitext(fallback)[1] or ".pdf"
    # 去除重音并转 ASCII；中文会被丢弃，因此再兜底。
    stem_ascii = unicodedata.normalize("NFKD", stem).encode("ascii", "ignore").decode("ascii", "ignore")
    stem_ascii = re.sub(r"[^A-Za-z0-9._-]+", "_", stem_ascii).strip("._-")
    if not stem_ascii:
        stem_ascii = os.path.splitext(fallback)[0] or "upload"
    ext_ascii = re.sub(r"[^A-Za-z0-9.]", "", ext) or ".pdf"
    if not ext_ascii.startswith("."):
        ext_ascii = "." + ext_ascii
    name = (stem_ascii[:max_len].strip("._-") or "upload") + ext_ascii.lower()
    try:
        name.encode("ascii")
    except Exception:
        name = fallback
    return name


class AsciiUploadCopy:
    """为云端文件上传创建 ASCII 文件名副本；退出时安全清理。"""
    def __init__(self, source_path: str, suffix: str = ".pdf", logger=None):
        self.source_path = source_path
        self.suffix = suffix if suffix.startswith(".") else "." + suffix
        self.logger = logger
        self.temp_dir = ""
        self.path = source_path
        self.upload_name = ascii_safe_filename(os.path.basename(source_path), fallback="chapter_upload" + self.suffix)

    def __enter__(self):
        # 只要原始路径或文件名包含非 ASCII，就复制到 ASCII-only 临时路径；否则也返回安全上传名给 SDK。
        try:
            str(self.source_path).encode("ascii")
            os.path.basename(self.source_path).encode("ascii")
            self.path = self.source_path
            self.upload_name = ascii_safe_filename(os.path.basename(self.source_path), fallback="chapter_upload" + self.suffix)
            return self
        except Exception:
            pass
        self.temp_dir = tempfile.mkdtemp(prefix="quanlan_upload_")
        self.upload_name = "chapter_upload" + self.suffix
        self.path = os.path.join(self.temp_dir, self.upload_name)
        shutil.copy2(self.source_path, self.path)
        return self

    def __exit__(self, exc_type, exc, tb):
        if self.temp_dir:
            safe_rmtree(self.temp_dir, self.logger)
        return False


def build_utf8_subprocess_env() -> dict:
    """构造 UTF-8 子进程环境；保留给通用扩展使用，PDF 解析不再调用本地解析器。"""
    env = os.environ.copy()
    env.setdefault("PYTHONUTF8", "1")
    env.setdefault("PYTHONIOENCODING", "utf-8")
    env.setdefault("LC_ALL", "C.UTF-8")
    env.setdefault("LANG", "C.UTF-8")
    return env


def compact_instruction_prompt(prompt: str) -> str:
    """只压缩系统/任务提示词中的完全重复段落与多余空白；不处理参考原文，避免损失内容。"""
    raw = str(prompt or "").replace("\r\n", "\n").replace("\r", "\n")
    paragraphs = re.split(r"\n{2,}", raw)
    seen = set()
    kept = []
    for para in paragraphs:
        cleaned_lines = [re.sub(r"[ \t]+", " ", ln).strip() for ln in para.split("\n")]
        cleaned = "\n".join([ln for ln in cleaned_lines if ln]).strip()
        if not cleaned:
            continue
        key = re.sub(r"\s+", " ", cleaned)
        if key in seen:
            continue
        seen.add(key)
        kept.append(cleaned)
    return "\n\n".join(kept).strip()


def get_voiceover_text_path(script_path: str) -> str:
    """最终口播台词路径。

    精简模式下，主脚本文件本身就是最终口播台词，避免同一内容同时保存
    “导读脚本最终版.txt”和“口播台词最终版.txt”两个副本。
    """
    if unified_intermediate_files_enabled():
        return script_path
    base, _ = os.path.splitext(script_path)
    return base + "_11_口播台词_逐句锁定_最终版.txt"


def get_image_prompt_text_path(script_path: str) -> str:
    """同一脚本基名下，保存逐图对应、台词驱动的最终绘图提示词文件。"""
    base, _ = os.path.splitext(script_path)
    return base + "_12_绘图提示词_逐图对应_台词驱动.txt"

def get_image_prompt_hash_path(image_path: str) -> str:
    return str(image_path or "") + ".prompt.sha256"


def get_image_prompt_api_text_path(image_path: str) -> str:
    return str(image_path or "") + ".api_prompt.txt"


def compute_image_prompt_api_text(prompt_name: str, prompt_text: str) -> str:
    try:
        return prepare_image_prompt_for_api(prompt_text, prompt_name=f"{prompt_name}.png" if prompt_name and not str(prompt_name).lower().endswith(".png") else str(prompt_name or ""), logger=None)
    except Exception:
        return str(prompt_text or "")


def compute_image_prompt_hash(prompt_name: str, prompt_text: str) -> str:
    import hashlib
    api_text = compute_image_prompt_api_text(prompt_name, prompt_text)
    return hashlib.sha256(api_text.encode("utf-8", errors="ignore")).hexdigest()


def write_image_prompt_sidecars(image_path: str, prompt_name: str, prompt_text: str, logger=None) -> None:
    try:
        api_text = compute_image_prompt_api_text(prompt_name, prompt_text)
        import hashlib
        digest = hashlib.sha256(api_text.encode("utf-8", errors="ignore")).hexdigest()
        if save_image_api_prompt_sidecars_enabled():
            write_text_file(get_image_prompt_api_text_path(image_path), api_text.strip() + "\n")
        write_text_file(get_image_prompt_hash_path(image_path), digest + "\n")
    except Exception as e:
        if logger:
            logger(f"⚠️ 写入配图 Prompt 指纹失败：{os.path.basename(str(image_path or ''))}；{str(e)[:100]}")


def image_prompt_sidecar_matches(image_path: str, prompt_name: str, prompt_text: str) -> bool:
    try:
        hp = get_image_prompt_hash_path(image_path)
        if not is_nonempty_file(hp, min_bytes=16):
            return False
        saved = read_text_file(hp).strip().split()[0]
        return bool(saved and saved == compute_image_prompt_hash(prompt_name, prompt_text))
    except Exception:
        return False


def get_voiceover_script_alias_path(script_path: str) -> str:
    """用户可直接识别的纯台词便捷入口文件名。精简模式下复用主脚本。"""
    if unified_intermediate_files_enabled():
        return get_voiceover_text_path(script_path)
    base, _ = os.path.splitext(script_path)
    return base + "_11_口播台词_便捷入口.txt"


def get_drawing_script_alias_path(script_path: str) -> str:
    """用户可直接识别的绘图提示词便捷入口文件名。精简模式下复用唯一绘图提示词文件。"""
    if unified_intermediate_files_enabled():
        return get_image_prompt_text_path(script_path)
    base, _ = os.path.splitext(script_path)
    return base + "_12_绘图提示词_便捷入口.txt"


def get_video_description_text_path(script_path: str) -> str:
    """保存单独的视频简介文件，约150字，用于发布文案。"""
    base, _ = os.path.splitext(script_path)
    return base + "_15_视频简介.txt"


def get_short_video_summary_text_path(script_path: str) -> str:
    """新增输出：短视频总结文件，包含中文章节名和约150字务实总结。"""
    base, _ = os.path.splitext(script_path)
    return base + "_14_短视频总结.txt"


def clean_video_description_text(text: str, max_chars: int = 260) -> str:
    """清理视频简介：只保留正文，不混入标题、关注语、绘图提示词或代码围栏。"""
    raw = str(text or "").replace("\r\n", "\n").replace("\r", "\n")
    raw = re.sub(r"```[a-zA-Z0-9_-]*", "", raw)
    raw = raw.replace("```", "")
    lines = []
    for line in raw.splitlines():
        t = line.strip()
        if not t:
            continue
        t = re.sub(r"^\s*(?:视频简介|简介|发布文案|Description)\s*[：:]\s*", "", t, flags=re.I).strip()
        if not t:
            continue
        if re.match(r"^\s*(?:提示词|Prompt|Image Prompt|绘图提示词)\s*[：:]", t, flags=re.I):
            continue
        if is_visual_prompt_contamination(t):
            continue
        lines.append(t)
    text = "".join(lines).strip()
    # 视频简介不承载关注动作；关注提示统一交给尾页品牌页。
    cta_patterns = [
        r"了解更多[，,、 ]*请点击下方关注《?全澜脑科学》?公众号[。.!！]*",
        r"请点击下方关注《?全澜脑科学》?公众号[。.!！]*",
        r"关注我们[，,、 ]*",
        r"更多信息[，,、 ]*请关注《?全澜脑科学》?公众号[。.!！]*",
    ]
    for pat in cta_patterns:
        text = re.sub(pat, "", text)
    text = re.sub(r"\s+", "", text).strip(" ，,。；;：:\n\t")
    # 保守截断，避免模型输出长文；尽量在句号处结束。
    if max_chars and len(text) > max_chars:
        cut = text[:max_chars]
        last_punct = max(cut.rfind("。"), cut.rfind("！"), cut.rfind("？"), cut.rfind("；"))
        if last_punct >= 120:
            cut = cut[:last_punct + 1]
        text = cut.rstrip("，,；;：:")
        if text and text[-1] not in "。！？；":
            text += "。"
    return text + ("\n" if text else "")


def extract_video_description_from_text(text: str) -> str:
    """从模型完整输出中提取“视频简介”区块，作为无模型兜底。"""
    raw = str(text or "").replace("\r\n", "\n").replace("\r", "\n")
    m = re.search(r"(?is)(?:^|\n)\s*(?:【\s*)?(?:4[.、．]\s*)?视频简介(?:\s*】)?\s*[：:]?\s*(.*)$", raw)
    if not m:
        return ""
    body = m.group(1)
    # 遇到后续明显章节/提示词字段就停止。
    stop = re.search(r"(?im)^\s*(?:【|#{1,6}|Shot[_\- ]?\d+|Final\s+Shot|Page Type|Prompt|提示词|绘图提示词|检查|审校)", body)
    if stop:
        body = body[:stop.start()]
    return clean_video_description_text(body)


def build_video_description_prompt(voiceover_text: str, book_name: str = "", chapter_title: str = "", chapter_number: str = "") -> str:
    """硬编码视频简介生成提示词已删除；保留兼容入口。"""
    return ""


def save_video_description_file(script_path: str, description_text: str, logger=None) -> str:
    """保存视频简介 txt。"""
    desc = clean_video_description_text(description_text)
    if not desc.strip():
        return ""
    path = get_video_description_text_path(script_path)
    write_text_file(path, desc)
    if logger:
        logger(f"📝 视频简介已保存：{os.path.basename(path)}")
    return path


def _split_author_names_for_voiceover(author_block: str) -> list[str]:
    """把作者字段拆成作者列表；仅用于口播压缩，不影响封面/首页完整作者显示。"""
    s = str(author_block or "").replace("\u00a0", " ")
    s = re.sub(r"（[^）]*）|\([^)]*\)", " ", s)
    s = re.sub(r"\b(?:authors?|edited\s+by|editor|by|written\s+by)\b\s*[：:=]?", " ", s, flags=re.I)
    s = re.sub(r"(?:作者|著者|主编|编著|合著|等著|等编|著|编)\s*$", " ", s)
    s = re.sub(r"\s+", " ", s).strip(" ，,、;；:/")
    if not s:
        return []

    s = re.sub(r"\bet\s+al\.?\b", " 等人", s, flags=re.I)
    s = re.sub(r"\s+(?:and|&|和|与|及)\s+", "、", s, flags=re.I)
    s = re.sub(r"\s*(?:;|；|、|/|\\+)\s*", "、", s)

    comma_parts = re.split(
        r"\s*,\s*(?=(?:[A-Z][A-Z.\-']*\s+){0,4}[A-Z][A-Z.\-']{2,}|(?:[A-Z][a-zA-Z'’.-]+\s+){1,4}[A-Z][a-zA-Z'’.-]+|[\u4e00-\u9fff])",
        s,
    )
    names = []
    for part in comma_parts:
        for item in re.split(r"[、]+", part):
            item = item.strip(" ，,、;；")
            if not item:
                continue
            if re.fullmatch(r"(?:等|等人|et\s*al\.?)", item, flags=re.I):
                continue
            names.append(item)

    deduped = []
    seen = set()
    for name in names:
        key = re.sub(r"[\W_]+", "", name).lower()
        if key and key not in seen:
            seen.add(key)
            deduped.append(name)
    return deduped


def _normalize_english_name_piece_for_voiceover(value: str) -> str:
    token = str(value or "").strip(" .,'’\"“”")
    if not token:
        return ""
    if re.fullmatch(r"[A-Z][A-Z'’.-]+", token):
        return token[:1].upper() + token[1:].lower()
    return token[:1].upper() + token[1:] if token.islower() else token


def _extract_first_author_short(author_block: str) -> str:
    """口播只取第一作者简名：英文取姓氏，中文保留姓名。"""
    authors = _split_author_names_for_voiceover(author_block)
    first = authors[0] if authors else str(author_block or "")
    first = re.sub(r"（[^）]*）|\([^)]*\)", " ", first)
    first = re.sub(r"\b(?:editor|edited\s+by|authors?|by|written\s+by)\b", " ", first, flags=re.I)
    first = re.sub(r"(?:作者|著者|主编|编著|合著|著|编|等人|等)", " ", first)
    first = first.strip(" ，,、;；")
    if not first:
        return ""

    cjk_match = re.search(r"[\u4e00-\u9fff]{2,6}", first)
    if cjk_match and not re.search(r"[A-Za-z]", first):
        return cjk_match.group(0)

    words = re.findall(r"[A-Za-z][A-Za-z'’.-]*", first)
    words = [w for w in words if not re.fullmatch(r"[A-Z]\.?,?", w)]
    if not words:
        return first.strip()
    return _normalize_english_name_piece_for_voiceover(words[-1])


def format_voiceover_author_credit(author_block: str) -> str:
    """口播作者格式：单作者念简名；多作者念“第一作者简名等人合著”。"""
    raw = str(author_block or "")
    first = _extract_first_author_short(raw)
    if not first:
        return ""
    authors = _split_author_names_for_voiceover(raw)
    multiple = len(authors) >= 2 or bool(re.search(r"\bet\s*al\.?\b|等人|等著|合著", raw, flags=re.I))
    return f"{first}等人合著" if multiple else first



def simplify_voiceover_book_title(book_title: str) -> str:
    """台词开头只使用简要中文书名，避免念英文长题名、版本、出版社和 ISBN。"""
    raw = str(book_title or "").strip()
    if not raw:
        return "这本书"
    # 特例：Principles of Neural Science / 神经科学原理，台词只念简名。
    if re.search(r"principles\s+of\s+neural\s+science|神经科学原理", raw, flags=re.I):
        return "神经科学原理"
    text = re.sub(r"（[^）]*(?:版|edition|isbn|出版|出版社)[^）]*）|\([^)]*(?:版|edition|isbn|出版|出版社)[^)]*\)", "", raw, flags=re.I)
    text = re.sub(r"[,，;；:].*$", "", text).strip()
    text = re.sub(r"第[一二三四五六七八九十0-9]+版|\b\d+(?:st|nd|rd|th)?\s+edition\b|isbn(?:-?13)?\s*[:：]?\s*\d[\d-]*", "", text, flags=re.I).strip()
    # 保留中文主标题；没有中文时保留短英文主标题。
    m = re.search(r"[\u4e00-\u9fff][\u4e00-\u9fffA-Za-z0-9·：:《》\-— ]{1,40}", text)
    if m:
        return m.group(0).strip("《》 ：:-—") or "这本书"
    words = re.findall(r"[A-Za-z][A-Za-z'’.-]*", text)
    if words:
        return " ".join(words[:6])
    return text[:40] or "这本书"

def format_voiceover_book_intro(book_title: str, author_block: str = "", chapter_number: str = "") -> str:
    """生成口播章节引入句前缀：在由Kandel等人合著《神经科学原理》的第32章中。

    - 书名只保留中文简名，避免英文长书名、editor、出版社、ISBN 进入旁白。
    - 多作者统一写成“首位作者简名等人合著”，不在中文词组中间插空格。
    - 无作者时退回“在《书名》的第X章中”。
    """
    book = simplify_voiceover_book_title(book_title)
    chapter = str(chapter_number or "").strip()
    chapter = re.sub(r"^第\s*", "", chapter)
    chapter = re.sub(r"\s*章$", "", chapter)
    chapter_part = f"第{chapter}章" if chapter else "本章"
    credit = format_voiceover_author_credit(author_block)
    if credit:
        return f"在由{credit}《{book}》的{chapter_part}中"
    return f"在《{book}》的{chapter_part}中"


def simplify_bibliographic_voiceover(text: str) -> str:
    """把口播中的书目信息压缩成：由作者合著《中文简名》的第X章。"""
    raw = str(text or "")
    chapter_re = r"[一二三四五六七八九十百千万零〇两\d]{1,12}"

    def make_intro(book: str, authors: str = "", chapter: str = "") -> str:
        return format_voiceover_book_intro(book, authors, chapter)

    pat = re.compile(
        rf"在由(?P<authors>[^。！？\n]{{1,220}}?)(?:主编|编著|著|合著)[^。！？\n]{{0,260}}?《(?P<book>[^》]{{1,260}})》[^。！？\n]{{0,260}}?第(?P<chapter>{chapter_re})章中"
    )

    def repl_by(m):
        return make_intro(m.group('book'), m.group('authors'), m.group('chapter'))

    raw = pat.sub(repl_by, raw)

    def repl_inline(m):
        book, authors, chapter = m.group(1), m.group(2), m.group(3)
        return make_intro(book, authors, chapter)

    # 形如：在《英文长书名...》Kandel等人合著的第32章中
    raw = re.sub(
        rf"在《([^》]{{1,320}})》\s*([^。！？\n]{{1,180}}?(?:等人合著|等著|合著|主编|编著|著|编))(?:的)?第({chapter_re})章中",
        repl_inline,
        raw,
        flags=re.I,
    )

    # 形如：在《英文长书名...》作者 Kandel 等人的第32章中
    raw = re.sub(
        rf"在《([^》]{{1,320}})》\s*作者\s*([^。！？\n]{{1,260}}?)(?:的)?第({chapter_re})章中",
        repl_inline,
        raw,
        flags=re.I,
    )

    # 书名中混入 ISBN / 出版社 / editor 等书目噪声，但没有可靠作者时，至少保留中文简名与章节号。
    def repl_no_author(m):
        return make_intro(m.group(1), "", m.group(2))

    raw = re.sub(
        rf"在《([^》]{{1,320}})》[^。！？\n]{{0,220}}?(?:ISBN(?:-?13)?[:：]?\s*\d[\d-]*|isbn13\s*\d[\d-]*|editor|New York|McGraw|纽约出版|于\d{{4}}年|第六版|第[一二三四五六七八九十0-9]+版)[^。！？\n]{{0,220}}?第({chapter_re})章中",
        repl_no_author,
        raw,
        flags=re.I,
    )

    raw = re.sub(rf"在《([^》]{{1,320}})》第({chapter_re})章中", lambda m: make_intro(m.group(1), "", m.group(2)), raw)
    raw = re.sub(r"作者([^，。；；\n]{1,80})等的的", r"作者\1等的", raw)
    raw = re.sub(r"([^，。；；\n]{1,80})等人合著的的", r"\1等人合著的", raw)
    raw = re.sub(r"由\s+([A-Za-z])", r"由\1", raw)
    raw = re.sub(r"([A-Za-z])\s+等人合著", r"\1等人合著", raw)
    return raw


def write_separated_voiceover_files(script_path: str, voiceover_text: str) -> None:
    """精简输出：只保留最终台词文件，避免同义副本堆积。"""
    cleaned = simplify_bibliographic_voiceover(voiceover_text)
    write_text_file(get_voiceover_text_path(script_path), cleaned)

def write_separated_drawing_files(script_path: str, drawing_text: str) -> None:
    """精简输出：只保留最终绘图提示词文件；文件头内置手动命名规则与后处理说明。"""
    body = str(drawing_text or "").strip()
    text = DRAWING_PROMPT_FILE_MANUAL_HEADER
    if body:
        text += body + "\n"
    write_text_file(get_image_prompt_text_path(script_path), text)

LRC_IMAGE_MARKER_RE = re.compile(r"【\s*(?:图\s*\d+|A1|A2|A01|A02|B\d{1,3}|C)\s*】", re.I)
LRC_IMAGE_MARKER_CAPTURE_RE = re.compile(r"【\s*(图\s*\d+|A1|A2|A01|A02|B\d{1,3}|C)\s*】", re.I)


def lrc_image_label_for_index(image_no: int, total_images: int = 0, page_type: str = "", prompt_name: str = "") -> str:
    """把内部图片顺序号转换为公开 LRC 锚点：A1/A2/B01.../C。"""
    try:
        n = int(image_no or 0)
    except Exception:
        n = 0
    try:
        total = int(total_images or 0)
    except Exception:
        total = 0
    combined = f"{prompt_name or ''}\n{page_type or ''}"
    if re.search(r"\bA01\b|Bilibili\s*Cover|B站封面|哔哩哔哩封面", combined, flags=re.I) or n == 3:
        return "A01"
    if re.search(r"\bA02\b|Bilibili\s*Home|B站首页|哔哩哔哩首页", combined, flags=re.I) or n == 4:
        return "A02"
    if re.search(r"\bA1\b|Video\s*Cover|WeChat\s*Cover|微信封面|封面", combined, flags=re.I) or n == 1:
        return "A1"
    if re.search(r"\bA2\b|Home\s*Page|WeChat\s*Home|微信首页|首页", combined, flags=re.I) or n == 2:
        return "A2"
    if re.search(r"\bC\b|Brand\s*Page|Final|Ending|品牌|结尾|尾页", combined, flags=re.I) or (total and n == total):
        return "C"
    if n > 4:
        return f"B{max(1, n - 4):02d}"
    return ""


def lrc_image_index_for_label(label: str, total_images: int = 0) -> int:
    """把 A1/A2/B01/C 或旧图N标签转换回内部图片顺序号。"""
    raw = re.sub(r"\s+", "", str(label or "")).upper()
    raw = raw.strip("【】")
    m = re.match(r"图0*(\d+)$", raw, flags=re.I)
    if m:
        return int(m.group(1))
    if raw == "A1":
        return 1
    if raw == "A2":
        return 2
    if raw == "A01":
        return 3
    if raw == "A02":
        return 4
    m = re.match(r"B0*(\d+)$", raw)
    if m:
        return int(m.group(1)) + 4
    if raw == "C":
        try:
            return int(total_images or 0) or 9999
        except Exception:
            return 9999
    return 0


def normalize_lrc_marker_label(label: str, total_images: int = 0) -> str:
    """兼容旧【图N】并统一成 A1/A2/B01/C。"""
    n = lrc_image_index_for_label(label, total_images=total_images)
    if not n:
        return ""
    return lrc_image_label_for_index(n, total_images=total_images)


def lrc_image_label_sort_key(label: str, total_images: int = 0) -> int:
    return lrc_image_index_for_label(label, total_images=total_images)


def normalize_lrc_markers_in_text(text: str, total_images: int = 0) -> str:
    """把 LRC 里的旧数字图号改为 A1/A2/B01/C；A1 封面不生成台词锚点。"""
    def repl(m):
        label = normalize_lrc_marker_label(m.group(1), total_images=total_images)
        if not label or label in {"A1", "A01", "A02"}:
            return ""
        return f"【{label}】"
    return LRC_IMAGE_MARKER_CAPTURE_RE.sub(repl, str(text or ""))


def split_lrc_marker_and_voiceover_text(text: str, total_images: int = 0):
    """最终导出 .lrc 时使用：配图锚点独占一行，台词正文独占另一行。

    内部台词文件仍允许“【B01】台词”这种同一行绑定，便于逐句润色校验；
    但写入 LRC 时必须拆成：
    [00:00.00]【B01】
    [00:00.00]对应台词
    """
    s = normalize_lrc_markers_in_text(str(text or "").strip(), total_images=total_images).strip()
    if not s:
        return [], ""

    markers = []

    def repl(m):
        label = normalize_lrc_marker_label(m.group(1), total_images=total_images)
        if label and label != "A1":
            marker = f"【{label}】"
            if marker not in markers:
                markers.append(marker)
        return " "

    voiceover = LRC_IMAGE_MARKER_CAPTURE_RE.sub(repl, s)
    voiceover = re.sub(r"\s+", " ", voiceover).strip()
    return markers, voiceover


def get_lrc_image_marker_map_path(script_path: str) -> str:
    """保存 LRC 配图锚点与台词首句的对应表，便于复盘。"""
    base, _ = os.path.splitext(script_path)
    return base + "_13_LRC配图ABC映射表.txt"


def extract_lrc_image_marker_lines(voiceover_text: str) -> list:
    """从带【A2】/【B01】/【C】等锚点的台词中提取配图-台词对应行。"""
    rows = []
    for raw in str(voiceover_text or "").splitlines():
        line = normalize_lrc_markers_in_text(raw).strip()
        if not line:
            continue
        ms = LRC_IMAGE_MARKER_CAPTURE_RE.findall(line)
        if not ms:
            continue
        clean = strip_lrc_image_markers(line)
        for label in ms:
            norm = normalize_lrc_marker_label(label)
            if norm and norm != "A1":
                rows.append((norm, clean))
    rows.sort(key=lambda x: lrc_image_label_sort_key(x[0]))
    return rows


def write_lrc_image_marker_map(script_path: str, voiceover_text: str) -> str:
    """记录配图锚点-台词关系。

    精简模式下不再单独落盘映射表，因为同样的锚点已经内嵌在最终台词和 LRC 中；
    需要排查时可设置 QUANLAN_UNIFIED_INTERMEDIATE_FILES=0 恢复旧映射表。
    """
    if unified_intermediate_files_enabled():
        return ""
    rows = extract_lrc_image_marker_lines(voiceover_text)
    path = get_lrc_image_marker_map_path(script_path)
    if not rows:
        write_text_file(path, "未识别到 LRC 配图锚点。\n")
        return path
    lines = ["LRC 配图台词对应表", "说明：LRC 锚点使用 A2/B01/B02.../C 对应配图；A1 封面页不生成台词锚点；最终 .lrc 中锚点独占一行，台词正文另起一行。", ""]
    for label, text in rows:
        lines.append(f"{label}: {text}")
    write_text_file(path, "\n".join(lines).rstrip() + "\n")
    return path


def _looks_like_image_prompt_source_text(text: str) -> bool:
    raw = str(text or "")[:20000]
    if not raw.strip():
        return False
    # 最终绘图提示词文件、图文一一对应脚本、网页手动绘图索引都应命中这些结构信号。
    signals = [
        r"手动绘图使用说明",
        r"逐图对应",
        r"台词驱动",
        r"Source\s+Prompt\s+Name\s*:",
        r"Page\s+Type\s*:",
        r"A1[_\s-]*(?:封面|cover)",
        r"A2[_\s-]*(?:首页|home)",
        r"VOICEOVER-DRIVEN\s+IMAGE\s+BRIEF",
        r"Prompt\s*:",
    ]
    hit = sum(1 for pat in signals if re.search(pat, raw, flags=re.I))
    return hit >= 2



def _find_nearby_image_prompt_source_path(script_path: str) -> str:
    """按内容查找同章节目录里的绘图提示词文件，兼容 ZIP/Windows 环境把中文文件名转成 #Uxxxx。"""
    try:
        ch_dir = os.path.dirname(os.path.abspath(str(script_path or "")))
        if not ch_dir or not os.path.isdir(ch_dir):
            return ""
        candidates = []
        for name in os.listdir(ch_dir):
            if not str(name).lower().endswith('.txt'):
                continue
            path = os.path.join(ch_dir, name)
            if not is_nonempty_file(path, min_bytes=50):
                continue
            try:
                if os.path.getsize(path) > 800000:
                    continue
            except Exception:
                pass
            txt = _read_text_if_exists(path, max_chars=20000) if '_read_text_if_exists' in globals() else read_text_file(path)[:20000]
            if not _looks_like_image_prompt_source_text(txt):
                continue
            low = name.lower()
            score = 0
            if "_12_" in low or "#u7ed8#u56fe" in low or "绘图" in name:
                score += 40
            if "逐图" in name or "#u9010#u56fe" in low:
                score += 20
            if "台词驱动" in name or "#u53f0#u8bcd" in low:
                score += 20
            if "_08_" in low or "_09_" in low:
                score += 8
            if "最终" in name or "#u6700#u7ec8" in low:
                score += 5
            candidates.append((-score, name, path))
        if not candidates:
            return ""
        candidates.sort(key=lambda x: (x[0], x[1]))
        return candidates[0][2]
    except Exception:
        return ""



def get_preferred_prompt_source_path(script_path: str) -> str:
    """配图优先读取独立绘图提示词文件；若中文文件名被转义，则按内容自动查找。"""
    prompt_path = get_image_prompt_text_path(script_path)
    if is_nonempty_file(prompt_path):
        return prompt_path
    return _find_nearby_image_prompt_source_path(script_path)

def compact_model_input_document(text: str, *, keep_chars: int | None = None) -> str:
    """精简传给大模型的本地解析文本，降低 token 消耗。

    只删除明显不参与内容理解的噪声：HTML/Markdown 注释、图片链接、URL、页眉页脚、
    页码、重复行、参考文献/索引等尾部材料。正文段落和表格文字尽量保留。
    """
    raw = str(text or "").replace("\r\n", "\n").replace("\r", "\n")
    if not raw.strip():
        return ""

    # 去掉 HTML / Markdown 注释、常见解析器控制标记和图片链接。
    raw = re.sub(r"<!--.*?-->", "\n", raw, flags=re.S)
    raw = re.sub(r"(?im)^\s*//\s*(?:TODO|NOTE|注释|comment|remark)[:：].*$", "", raw)
    raw = re.sub(r"(?im)^\s*#\s*(?:TODO|NOTE|注释|comment|remark)[:：].*$", "", raw)
    raw = re.sub(r"!\[[^\]]*\]\([^)]*\)", " ", raw)
    raw = re.sub(r"<img\b[^>]*>", " ", raw, flags=re.I)
    raw = re.sub(r"https?://\S+", " ", raw)

    # 去掉参考文献/索引/版权/致谢等通常不需要送入脚本模型的尾部区块。
    tail_cut = re.search(
        r"(?im)^\s*(?:references|bibliography|selected readings?|further readings?|suggested readings?|index|glossary|acknowledg(?:e)?ments?|版权|参考文献|延伸阅读|推荐阅读|索引|术语表|致谢)\s*$",
        raw,
    )
    if tail_cut and tail_cut.start() > max(1500, len(raw) * 0.45):
        raw = raw[:tail_cut.start()]

    lines = []
    seen_recent = []
    for ln in raw.split("\n"):
        line = re.sub(r"[ \t]+", " ", ln).strip()
        if not line:
            lines.append("")
            continue
        low = line.casefold()
        # 页码、页眉页脚、出版社水印、Markdown 页面分隔符。
        if re.fullmatch(r"(?:page\s*)?\d{1,4}", low):
            continue
        if re.fullmatch(r"[-—–_\s]{3,}", line):
            continue
        if re.search(r"copyright|all rights reserved|mcgraw[-\s]*hill|isbn", low) and len(line) < 160:
            continue
        if re.match(r"^#{1,6}\s*$", line):
            continue
        # 解析器常见坐标/块编号/图片占位。
        if re.match(r"^(?:figure|fig\.|table)\s*\d+(?:[-. ]\d+)?\s*$", low) and len(line) < 30:
            continue
        if re.match(r"^\[?(?:image|figure|table|page|block)[-_ ]?\d+\]?\s*$", low):
            continue

        # 去掉短窗口内重复行，保留第一次出现。
        key = re.sub(r"\W+", "", low)
        if key and len(key) >= 8 and key in seen_recent:
            continue
        seen_recent.append(key)
        if len(seen_recent) > 160:
            seen_recent = seen_recent[-120:]
        lines.append(line)

    compact = "\n".join(lines)
    compact = re.sub(r"\n{3,}", "\n\n", compact).strip()
    if keep_chars is not None:
        try:
            n = max(1000, int(keep_chars))
            compact = compact[:n]
        except Exception:
            pass
    return compact


def truncate_context(text: str, limit: int = SCRIPT_CONTEXT_CHAR_LIMIT) -> str:
    """限制并精简传给大模型的原文长度；集中管理，减少无效 token。"""
    try:
        n = max(1000, int(limit))
    except Exception:
        n = 50000
    return compact_model_input_document(text, keep_chars=n)


def count_pdf_pages_safe(pdf_path: str) -> int:
    """安全读取 PDF 页数；用于 PDF 直传模式下估算更密的分镜数量。"""
    if not pdf_path or not os.path.exists(pdf_path):
        return 0
    try:
        from pypdf import PdfReader
        reader = PdfReader(pdf_path)
        return int(len(reader.pages))
    except Exception:
        return 0



AUTHOR_LABEL_RE = r"(?:by|authors?|edited\\s+by|written\\s+by|作者|著者|主编|编著)"


def _normalize_author_separators(value: str) -> str:
    """统一作者分隔符；只做格式清理，不把多作者压缩成 et al."""
    s = str(value or "").replace("\u00a0", " ")
    s = re.sub(r"\s+", " ", s).strip(" \t-—–:：,，.;；")
    if not s:
        return ""
    s = re.sub(r"\s*(?:;|；|、|/|\\+)\s*", ", ", s)
    s = re.sub(r"\s+(?:and|&|和|与|及)\s+", ", ", s, flags=re.I)
    s = re.sub(r"\s*,\s*", ", ", s)
    s = re.sub(r"(?:,\s*){2,}", ", ", s)
    return s.strip(" ,，;；")


def _clean_pdf_author_candidate(line: str) -> str:
    """清洗从 PDF 封面/title page 固定区域提取出的作者候选行。"""
    s = str(line or "").replace("\u00a0", " ")
    s = re.sub(r"\s+", " ", s).strip(" \t-—–:：,，.;；")
    # 只去掉字段标签，不吞掉作者本身；支持 "By A, B" / "Authors: A; B" / "作者：甲、乙"。
    s = re.sub(rf"^(?:{AUTHOR_LABEL_RE})\s*[：:=]?\s*", "", s, flags=re.I).strip()
    s = re.sub(r"\s*(?:著|编著|主编|编)\s*$", "", s).strip(" ,，;；")
    s = _dedupe_repeated_text(s)
    return _normalize_author_separators(s)


def _looks_like_author_line(line: str, book_title: str = "") -> bool:
    """启发式判断一行 PDF 文本是否像作者名，而不是出版社/目录/版权/营销句。"""
    original = str(line or "").strip()
    s = _clean_pdf_author_candidate(original)
    label_hint = bool(re.search(rf"^(?:{AUTHOR_LABEL_RE})\b", original, flags=re.I))
    if not s or len(s) < 3 or len(s) > 240:
        return False
    norm_title = re.sub(r"[\W_]+", "", str(book_title or "")).lower()
    if norm_title and norm_title in re.sub(r"[\W_]+", "", s).lower():
        return False

    bad = (
        r"(?:copyright|isbn|library|catalog|contents|preface|foreword|chapter|edition|volume|press|publisher|"
        r"university|department|school|institute|rights|reserved|printed|translated|translator|review|glossary|index|mcgraw|pearson|wiley|springer|elsevier|routledge|cengage|prentice|sage|oxford|cambridge|"
        r"corporate|training|programs?|contact|representative|sales|bulk|special\s+sales|permission|permissions|"
        r"request|website|www\.|https?://|e-?mail|email|phone|fax|customer|service|course|courses|"
        r"目录|版权|出版社|出版|译者|前言|序言|章节|第.+版|扫描|下载)"
    )
    if re.search(bad, s, flags=re.I):
        return False
    if "@" in s or re.search(r"\d", s):
        return False
    # 作者行通常不是完整营销/版权句。允许姓名缩写里的句点，但排除普通句子。
    if re.search(r"[!?！？。]", s) or ("." in s and not re.search(r"\b[A-Z]\.", s) and not re.search(r"\bet\s*al\.", s, flags=re.I)):
        return False

    words = re.findall(r"[A-Za-z][A-Za-z'’.-]*", s)
    word_count = len(words)
    if word_count > 32:
        return False

    english_name = bool(re.search(r"\b[A-Z][a-zA-Z'’.-]{1,}\s+(?:[A-Z]\.\s+)?[A-Z][a-zA-Z'’.-]{1,}\b", s))
    capitalized_words = re.findall(r"\b[A-Z][a-zA-Z'’.-]{2,}\b", s)
    has_initial = bool(re.search(r"\b[A-Z]\.\s*(?:[A-Z]\.)?\s*[A-Z][a-zA-Z'’.-]+|\b[A-Z][a-zA-Z'’.-]+\s+[A-Z]\.", s))
    has_joiner = bool(re.search(r"(?:,|，|;|；|\band\b|&|、)", s, flags=re.I))
    cjk_name = bool(re.search(r"[\u4e00-\u9fff]{2,4}(?:\s*[、，,和与及]\s*[\u4e00-\u9fff]{2,4})*", s))
    has_et_al = bool(re.search(r"\bet\s*al\.?\b", s, flags=re.I))

    # 没有字段标签时，避免把书名/副标题误当作者。
    title_like_terms = r"\b(?:principles|science|neuroscience|biology|physiology|psychology|medicine|manual|handbook|textbook|introduction|guide|atlas|methods|clinical|basic|learning|memory|brain|neural|cognitive|systems?)\b"
    original_has_author_separator = bool(re.search(r"(?:,|，|;|；|&|、)", original)) or bool(re.search(r"\s+(?:and|和|与|及)\s+", original)) and len(re.findall(r"\b[A-Z][a-zA-Z'’.-]{2,}\b", original)) >= 3
    if not label_hint and re.search(title_like_terms, s, flags=re.I) and not (has_initial or has_et_al or original_has_author_separator):
        return False

    name_signal = english_name or cjk_name or has_et_al or has_initial or (has_joiner and len(capitalized_words) >= 2) or len(capitalized_words) >= 2
    if label_hint:
        return bool(name_signal)
    return bool(name_signal and (english_name or cjk_name or has_joiner or has_initial or has_et_al))


def _collect_pdf_fixed_region_lines(pdf_path: str, *, max_pages: int = 6) -> list[dict]:
    """从 PDF 前几页的固定书目信息区域读取文本行，保留 page/x/y，用于稳定提取作者。"""
    rows = []
    if not pdf_path or not os.path.exists(pdf_path):
        return rows
    try:
        from pypdf import PdfReader
        reader = PdfReader(pdf_path)
        for page_index, page in enumerate(reader.pages[:max_pages]):
            try:
                w = float(page.mediabox.width or 1)
                h = float(page.mediabox.height or 1)
            except Exception:
                w, h = 1.0, 1.0
            fragments = []
            def visitor_text(text, cm, tm, font_dict, font_size):
                try:
                    t = str(text or "").strip()
                    if not t:
                        return
                    x = float(tm[4]) if tm and len(tm) > 4 else 0.0
                    y = float(tm[5]) if tm and len(tm) > 5 else 0.0
                    if 0.05 * w <= x <= 0.95 * w and 0.14 * h <= y <= 0.86 * h:
                        fragments.append((round(y / 4) * 4, x, t))
                except Exception:
                    return
            try:
                page.extract_text(visitor_text=visitor_text)
            except Exception:
                fragments = []
            if fragments:
                by_y = {}
                for y, x, t in fragments:
                    by_y.setdefault(y, []).append((x, t))
                for y in sorted(by_y.keys(), reverse=True):
                    parts = [t for _x, t in sorted(by_y[y], key=lambda z: z[0])]
                    line = re.sub(r"\s+", " ", " ".join(parts)).strip()
                    if line:
                        rows.append({"page": page_index, "x": min(x for x, _ in by_y[y]), "y": y, "w": w, "h": h, "line": line})
            else:
                try:
                    text = page.extract_text() or ""
                    for i, line in enumerate([ln.strip() for ln in text.splitlines() if ln.strip()]):
                        rows.append({"page": page_index, "x": 0, "y": h * (0.80 - min(i, 25) * 0.025), "w": w, "h": h, "line": line})
                except Exception:
                    continue
    except Exception:
        return rows
    return rows


def _page_looks_like_bibliographic_noise(page_text: str) -> bool:
    """判断页面是否更像版权页/目录页；这些页面不作为作者优先来源。"""
    t = str(page_text or "")
    return bool(re.search(
        r"(copyright|all rights reserved|isbn|library of congress|cataloging|permissions?|printed in|contents|table of contents|"
        r"版权|版权所有|目录|出版社|出版发行|印刷|版次)",
        t,
        flags=re.I,

    ))


def _page_has_titlepage_signal(page_text: str, book_title: str = "") -> bool:

    """判断页面是否像前封面或 title page。"""
    t = str(page_text or "")
    norm_page = re.sub(r"[\W_]+", "", t).lower()
    norm_book = re.sub(r"[\W_]+", "", str(book_title or "")).lower()
    if norm_book and norm_book in norm_page:
        return True
    return bool(re.search(rf"\b(?:{AUTHOR_LABEL_RE})\b|title\s*page|封面|题名页", t, flags=re.I))


def _merge_author_lines_for_display(lines: list[str]) -> str:
    """把同一 title page 上的多行作者合并，保留全部作者，不转换为 et al."""
    cleaned = []
    seen = set()
    for line in lines:
        c = _clean_pdf_author_candidate(line)
        if not c:
            continue
        key = re.sub(r"[\W_]+", "", c).lower()
        if not key or key in seen:
            continue
        seen.add(key)
        cleaned.append(c)
    return _normalize_author_separators(", ".join(cleaned))


def _collect_author_group_around_line(page_rows: list[dict], start_idx: int, book_title: str = "") -> tuple[list[str], bool]:
    """从某一行向后收集连续作者行；返回作者行列表和是否由 By/Author 标签触发。"""
    if start_idx < 0 or start_idx >= len(page_rows):
        return [], False
    line = str(page_rows[start_idx].get("line") or "").strip()
    label_hint = bool(re.search(rf"^(?:{AUTHOR_LABEL_RE})\b\s*[：:=]?", line, flags=re.I))
    group = []

    # 当前行可能是 "By A, B"，也可能只是单独一个作者姓名。
    current_clean = _clean_pdf_author_candidate(line)
    if current_clean and _looks_like_author_line(line, book_title=book_title):
        group.append(current_clean)

    # 若当前行只是 "By" / "Authors"，继续取后面连续作者名。
    for nxt in page_rows[start_idx + 1:start_idx + 8]:
        nxt_line = str(nxt.get("line") or "").strip()
        if not nxt_line:
            continue
        if re.search(r"(?:edition|press|publisher|copyright|isbn|department|university|mcgraw|pearson|wiley|springer|elsevier|routledge|cengage|prentice|sage|出版社|出版|版权|第.+版)", nxt_line, flags=re.I):
            break
        if _looks_like_author_line(nxt_line, book_title=book_title):
            group.append(_clean_pdf_author_candidate(nxt_line))
            continue
        # 已经拿到作者后，遇到非作者行就停止，避免串到出版社或副标题。
        if group:
            break
        # 标签触发但第一行为空时，允许跳过一行短装饰/空标签。
        if not label_hint:
            break

    return group, label_hint


def extract_book_author_from_pdf_fixed_region(pdf_path: str, book_title: str = "", logger=None) -> str:
    """优先从 PDF 前封面 / title page 提取完整作者列表；失败时返回空，不写死任何默认作者。"""
    try:
        max_pages = int(os.environ.get("QUANLAN_AUTHOR_SCAN_PAGES", "8"))
    except Exception:
        max_pages = 8
    rows = _collect_pdf_fixed_region_lines(pdf_path, max_pages=max_pages)
    if not rows:
        return ""

    pages: dict[int, list[dict]] = {}
    for row in rows:
        pages.setdefault(int(row.get("page") or 0), []).append(row)

    candidates = []
    norm_book = re.sub(r"[\W_]+", "", str(book_title or "")).lower()
    for page, page_rows in sorted(pages.items()):
        # 视觉顺序：从页面上方到下方。
        page_rows = sorted(page_rows, key=lambda r: (-float(r.get("y") or 0), float(r.get("x") or 0)))
        page_text = "\n".join(str(r.get("line") or "") for r in page_rows)
        bibliographic_noise = _page_looks_like_bibliographic_noise(page_text)
        titlepage_signal = _page_has_titlepage_signal(page_text, book_title=book_title)

        for idx, row in enumerate(page_rows):
            group, label_hint = _collect_author_group_around_line(page_rows, idx, book_title=book_title)
            if not group:
                continue
            author = _merge_author_lines_for_display(group)
            if not author or not _looks_like_author_line(author, book_title=book_title):
                continue

            y = float(row.get("y") or 0)
            h = float(row.get("h") or 1)
            y_ratio = y / max(1.0, h)
            score = 0
            # 明确优先：封面和 title page，而不是版权页。
            score += max(0, 20 - page * 3)
            if titlepage_signal:
                score += 12
            if bibliographic_noise:
                score -= 18
            if label_hint:
                score += 14
            if norm_book and norm_book in re.sub(r"[\W_]+", "", page_text).lower():
                score += 10
            if 0.22 <= y_ratio <= 0.78:
                score += 4
            if len(group) >= 2:
                score += min(8, len(group) * 2)
            if re.search(r"(?:,|，|;|；|\band\b|&|、)", author, flags=re.I):
                score += 3
            if re.search(r"\bet\s*al\.?\b", author, flags=re.I):
                score -= 3  # 不是禁止；只是如果同页有完整名单，优先完整名单。
            candidates.append((score, -page, -abs(y_ratio - 0.50), author))

    if not candidates:
        # 兜底：只在前两页里找最高质量的单行作者，仍避免版权/目录页。
        for page, page_rows in sorted(pages.items()):
            if page > 1:
                break
            page_text = "\n".join(str(r.get("line") or "") for r in page_rows)
            if _page_looks_like_bibliographic_noise(page_text):
                continue
            for row in page_rows:
                line = str(row.get("line") or "").strip()
                if _looks_like_author_line(line, book_title=book_title):
                    author = _clean_pdf_author_candidate(line)
                    candidates.append((1, -page, 0, author))

    if not candidates:
        return ""

    candidates.sort(reverse=True)
    author = _merge_author_lines_for_display([candidates[0][3]])
    if not _looks_like_author_line(author, book_title=book_title):
        return ""
    if logger:
        logger(f"👤 已从 PDF 前封面/title page 提取作者：{author}")
    return author



def _normalize_cover_home_cache_book_fields(book_title: str, book_title_cn: str, version_text: str, author_line: str) -> tuple[str, str, str, str]:
    """封面/首页缓存字段规范化：Kandel 书籍使用固定中文书名、版本、作者简写。"""
    bt = str(book_title or "").strip()
    btc = str(book_title_cn or "").strip()
    ver = str(version_text or "").strip()
    author = str(author_line or "").strip()
    joined = " ".join([bt, btc, ver, author])
    if re.search(r"principles\s+of\s+neural\s+science|神经科学原理", joined, flags=re.I):
        bt = "Principles of Neural Science"
        btc = "神经科学原理"
        if not ver:
            ver = "第六版"
        if not author:
            author = "ERIC R. KANDEL 等人合著"
    return bt, btc, ver, author

def save_cover_home_metadata_cache(ch_dir: str, *, book_title: str = "", book_title_cn: str = "", version_text: str = "", author_line: str = "", chapter_number: str = "", chapter_title: str = "", chapter_title_cn: str = "", chapter_title_en: str = "") -> str:
    """保存封面/首页后处理用元信息，供后续图片重绘时稳定读取。

    科学著作封面必须同时保留中文章名与英文章名。旧缓存如果缺少 Chapter Title EN、
    或把中文章名误写到英文位置，会被自动刷新，避免封面继续沿用旧错误。
    """
    if not ch_dir:
        return ""
    path = os.path.join(ch_dir, "0_封面首页元信息.txt")

    book_title, book_title_cn, version_text, author_line = _normalize_cover_home_cache_book_fields(book_title, book_title_cn, version_text, author_line)

    clean_en_func = globals().get("clean_chapter_title_english_text")
    choose_en_func = globals().get("choose_complete_chapter_title_english_text")
    clean_cn_func = globals().get("clean_chapter_title_translation_text")
    contains_cjk = globals().get("contains_cjk_text")
    try:
        if callable(choose_en_func):
            chapter_title_en_value = choose_en_func(chapter_title_en, chapter_title)
        else:
            chapter_title_en_value = clean_en_func(chapter_title_en or chapter_title, fallback=chapter_title or "") if callable(clean_en_func) else str(chapter_title_en or chapter_title or "").strip()
    except Exception:
        chapter_title_en_value = str(chapter_title_en or chapter_title or "").strip()
    try:
        chapter_title_cn_value = clean_cn_func(chapter_title_cn, fallback="") if callable(clean_cn_func) else str(chapter_title_cn or "").strip()
    except Exception:
        chapter_title_cn_value = str(chapter_title_cn or "").strip()

    def _cache_has_complete_required_fields() -> bool:
        """已有 0_封面首页元信息.txt 是封面权威文件。

        只要字段完整且章节中英文名合法，就保留用户/历史缓存内容；不要因为文件夹名、
        短视频小标题或本轮翻译结果不同而覆盖它。字段缺失或明显污染时才重写。
        """
        if not should_reuse_existing_file(path, min_bytes=20):
            return False
        try:
            old = read_text_file(path)
        except Exception:
            return False
        required = [
            "Book Title", "Book Title CN", "Version", "Author",
            "Chapter Number", "Chapter Title EN", "Chapter Title CN",
        ]
        values = {key: _read_simple_kv_value(old, key) for key in required}
        artifact_check = globals().get("_is_cover_home_workflow_title_artifact")
        old_en = values.get("Chapter Title EN", "")
        old_cn = values.get("Chapter Title CN", "")
        if callable(artifact_check) and (artifact_check(old_en) or artifact_check(old_cn)):
            return False
        if not all(str(values.get(key, "")).strip() for key in required):
            return False
        if callable(contains_cjk) and contains_cjk(old_en):
            return False
        if callable(contains_cjk) and not contains_cjk(old_cn):
            return False
        return True

    def _cache_has_both_titles() -> bool:
        return _cache_has_complete_required_fields()

    if _cache_has_both_titles():
        return path

    lines = [
        "封面页/首页元信息：",
        f"Book Title: {book_title}",
        f"Book Title CN: {book_title_cn}",
        f"Version: {version_text}",
        f"Author: {author_line}",
        f"Chapter Number: {chapter_number}",
        f"Chapter Title: {chapter_title_en_value or chapter_title}",
        f"Chapter Title EN: {chapter_title_en_value or chapter_title}",
        f"Chapter Title CN: {chapter_title_cn_value or chapter_title_cn}",
    ]
    write_text_file(path, "\n".join(lines).rstrip() + "\n")
    return path

def estimate_dynamic_image_plan(source_text: str, chapter_title: str = "", chapter_number: str = "", source_pdf_path: str = "") -> dict:
    """返回章节配图上下文；不按 PDF 页数凑图，但脚本阶段必须按 3~8 秒镜头规划。"""
    raw = str(source_text or "").replace("\r\n", "\n").replace("\r", "\n")
    paras = [ln.strip() for ln in raw.split("\n") if ln.strip()]
    cjk_chars = len(re.findall(r"[\u4e00-\u9fff]", raw))
    en_words = len(re.findall(r"[A-Za-z]+", raw))
    pdf_page_count = count_pdf_pages_safe(source_pdf_path)
    return {
        "chapter_number": str(chapter_number or "").strip(),
        "chapter_title": str(chapter_title or "").strip(),
        "paragraph_count": len(paras),
        "cjk_chars": cjk_chars,
        "en_words": en_words,
        "pdf_page_count": pdf_page_count,
        "planning_mode": "llm_3_8s_shot_level_script_design",
    }


def build_dynamic_image_count_instruction(plan: dict) -> str:
    pdf_page_count = int((plan or {}).get("pdf_page_count") or 0)
    pdf_hint = f"本章章节 PDF 约 {pdf_page_count} 页；此信息仅供模型理解章节体量，不得用于按页数凑图。\n" if pdf_page_count else ""
    return (
        "【3~8 秒镜头制：要求 Gemini / 大模型在脚本生成阶段同步设计】\n"
        "程序不再用 LRC 的时间戳、PDF 页数或旧的自然段均分方式切画面；LRC 只负责最终字幕时间戳。\n"
        "脚本生成模型必须先把 Part One 旁白在内部规划成连续镜头，再输出 Part Two；不能先写一整段长旁白、再只给少量 B 图。\n"
        "每个非封面镜头必须对应 3~8 秒可朗读台词，并同步生成一张强相关医学配图；按中文科普口播约 5–6 个汉字/秒估算。\n"
        "每个镜头只能承载一个清晰科学命题：一个对象、一个机制、一个证据、一个对比、一个步骤、一个因果关系或一个层级关系。\n"
        "B 系列必须按 3~8 秒/镜头展开主体内容：超过 8 秒必须拆分；短于 3 秒且语义未变化可与相邻句合并，但合并后不得超过 8 秒。\n"
        "如果一句或一段包含两个以上机制/证据/对比/步骤，即使不足 8 秒，也必须按语义焦点拆成多张 B 图。\n"
        "不要预设固定总图数，也不要凑图；总图数应由旁白总时长按 3~8 秒/镜头自然展开，并由语义焦点校正。\n"
        + pdf_hint +
        "禁止使用 30 秒 LRC 间隔来生成或切分镜头；30 秒只用于 LRC 时间戳留白，不代表镜头时长；禁止输出与台词无关的过渡图、空白 B 页、泛医学壁纸或科技氛围图。\n"
        "A1 是封面无口播；A2 对应章节提要句；A01/A02 只复用 A1 母图裁切；B 系列从正文第一组语义开始按 3~8 秒/镜头连续编号；C 对应结尾总结/下一章标题级预告/关注语，也按 3~8 秒可朗读台词规划。"
    )


def clean_script_text_for_output(script_text: str) -> str:
    """保存脚本与生成 LRC 前的统一保守清洗链。"""
    return sanitize_final_chinese_logic_and_professional_expression(
        sanitize_sentence_clarity_and_redundancy(
            sanitize_scientific_chinese_style(
                apply_professional_terminology_cleanup(script_text or "")
            )
        )
    )


def ensure_lrc_for_existing_script(script_path: str, logger=None) -> str:
    """脚本已存在时，先确保独立台词/绘图提示词文件存在，再从台词文件重建 LRC。"""
    lrc_path = os.path.splitext(script_path)[0] + ".lrc"
    if not is_nonempty_file(script_path):
        return lrc_path
    try:
        script_text = read_text_file(script_path)
        voiceover_path = get_voiceover_text_path(script_path)
        prompt_path = get_image_prompt_text_path(script_path)
        marker_map_path = get_lrc_image_marker_map_path(script_path)
        if (
            resume_skip_existing_enabled()
            and not resume_force_rebuild_enabled()
            and is_nonempty_file(lrc_path, min_bytes=20)
            and is_nonempty_file(voiceover_path, min_bytes=20)
            and is_nonempty_file(prompt_path, min_bytes=20)
            and (unified_intermediate_files_enabled() or is_nonempty_file(marker_map_path, min_bytes=5))
        ):
            if logger:
                logger(f"♻️ 已存在 LRC/台词/绘图提示词/配图锚点，跳过重建：{os.path.basename(lrc_path)}")
            return lrc_path
        if not is_nonempty_file(voiceover_path) or not is_nonempty_file(prompt_path):
            voiceover_text, image_prompt_text = split_final_script_to_voiceover_and_prompts(script_text)
            if voiceover_text and (not is_nonempty_file(voiceover_path) or not is_nonempty_file(get_voiceover_script_alias_path(script_path))):
                write_separated_voiceover_files(script_path, voiceover_text)
            if image_prompt_text and (not is_nonempty_file(prompt_path) or not is_nonempty_file(get_drawing_script_alias_path(script_path))):
                write_separated_drawing_files(script_path, image_prompt_text)
        voiceover_source = read_text_file(voiceover_path) if is_nonempty_file(voiceover_path) else script_text
        prompt_source = read_text_file(get_image_prompt_text_path(script_path)) if is_nonempty_file(get_image_prompt_text_path(script_path)) else script_text
        raw_backup_path = os.path.splitext(script_path)[0] + "_完整脚本原稿.txt"
        if not has_lrc_image_marker(voiceover_source) and is_nonempty_file(raw_backup_path):
            raw_text = read_text_file(raw_backup_path)
            rebuilt_voiceover, rebuilt_prompts = split_initial_script_to_two_small_files(raw_text, logger=logger)
            if rebuilt_voiceover.strip():
                voiceover_source = purge_visual_prompt_contamination_from_voiceover(rebuilt_voiceover)
                write_separated_voiceover_files(script_path, voiceover_source)
                write_text_file(script_path, voiceover_source)
            if rebuilt_prompts.strip() and not is_nonempty_file(get_image_prompt_text_path(script_path)):
                prompt_source = rebuilt_prompts
                write_separated_drawing_files(script_path, rebuilt_prompts)
        lrc_text = generate_lrc_text(voiceover_source, interval_seconds=LRC_INTERVAL_SECONDS, image_prompt_text=prompt_source)
        write_text_file(lrc_path, lrc_text)
        write_lrc_image_marker_map(script_path, voiceover_source)
        if logger:
            logger(f"✅ 已从独立台词文件重建 LRC：{os.path.basename(lrc_path)}")
    except Exception as e:
        if logger:
            logger(f"⚠️ 已有脚本 LRC 更新失败：{str(e)[:120]}")
    return lrc_path


def _find_existing_image_for_prompt(images_dir: str, prompt_name: str) -> str:
    """在配图目录及其子目录中查找已经存在的指定图片，兼容网页手动下载/拖入子文件夹的情况。"""
    try:
        if not images_dir or not os.path.isdir(images_dir) or not prompt_name:
            return ""
        target_names = {
            f"{prompt_name}.png", f"{prompt_name}.jpg", f"{prompt_name}.jpeg", f"{prompt_name}.webp",
        }
        # 兼容用户手动保存时把中文页名改成英文别名。
        low = str(prompt_name).lower()
        if re.search(r"(?:^|[^a-z])a1(?:[^a-z]|$)|封面", low, flags=re.I):
            target_names.update({"A1.png", "A1_cover.png", "A1_封面页.png", "cover.png", "封面页.png"})
        if re.search(r"(?:^|[^a-z])a2(?:[^a-z]|$)|首页", low, flags=re.I):
            target_names.update({"A2.png", "A2_home.png", "A2_首页.png", "home.png", "首页.png"})
        if re.search(r"(?:^|[^a-z])c(?:[^a-z]|$)|品牌|尾页|结束", low, flags=re.I):
            target_names.update({"C.png", "C_brand.png", "C_品牌页.png", "brand.png", "品牌页.png"})

        exact_hits = []
        fuzzy_hits = []
        for cur, dirs, files in os.walk(images_dir):
            parts = set(os.path.normpath(cur).split(os.sep))
            if "_raw" in parts:
                dirs[:] = []
                continue
            dirs[:] = [d for d in dirs if not d.startswith('.') and d != '_raw']
            for name in files:
                if not name or name.startswith('.'):
                    continue
                ext = os.path.splitext(name)[1].lower()
                if ext not in SUPPORTED_POSTPROCESS_IMAGE_EXTS:
                    continue
                path = os.path.join(cur, name)
                if not is_nonempty_file(path, min_bytes=1000):
                    continue
                if name in target_names:
                    exact_hits.append(path)
                else:
                    base = os.path.splitext(name)[0].lower()
                    # A/B/C 页名的兜底匹配，避免手动保存时多了空格、编号或英文后缀。
                    if re.search(r"(?:^|[^a-z])a1(?:[^a-z]|$)|封面", low, flags=re.I) and re.search(r"(?:^|[^a-z])a1(?:[^a-z]|$)|cover|封面", base, flags=re.I):
                        fuzzy_hits.append(path)
                    elif re.search(r"(?:^|[^a-z])a2(?:[^a-z]|$)|首页", low, flags=re.I) and re.search(r"(?:^|[^a-z])a2(?:[^a-z]|$)|home|首页", base, flags=re.I):
                        fuzzy_hits.append(path)
                    elif re.search(r"(?:^|[^a-z])c(?:[^a-z]|$)|品牌|尾页|结束", low, flags=re.I) and re.search(r"(?:^|[^a-z])c(?:[^a-z]|$)|brand|ending|尾页|品牌", base, flags=re.I):
                        fuzzy_hits.append(path)
        hits = exact_hits or fuzzy_hits
        if not hits:
            return ""
        # 离 images_dir 最近、路径最短的优先。
        hits.sort(key=lambda x: (len(os.path.relpath(x, images_dir).split(os.sep)), os.path.relpath(x, images_dir).lower()))
        return hits[0]
    except Exception:
        return ""



def summarize_image_resume_state(script_path: str, images_dir: str, logger=None):
    """根据已有脚本和图片，计算配图断点续跑状态。优先从独立绘图提示词文件读取。"""
    prompt_source_path = get_preferred_prompt_source_path(script_path)
    if not is_nonempty_file(prompt_source_path):
        if logger:
            logger("⚠️ 找不到可用脚本或独立绘图提示词文件，无法提取配图提示词。")
        return [], [], 0
    prompts = ScriptParser.extract_image_prompts(read_text_file(prompt_source_path), logger)
    os.makedirs(images_dir, exist_ok=True)
    pending = []
    done_count = 0
    for p_name, p_text in prompts:
        img_save_path = os.path.join(images_dir, f"{p_name}.png")
        existing_path = img_save_path if is_nonempty_file(img_save_path, min_bytes=1000) else _find_existing_image_for_prompt(images_dir, p_name)
        if existing_path and is_nonempty_file(existing_path, min_bytes=1000):
            # v8.0 断点续作：默认只要目标图片已经存在，就视为完成，不再因为 Prompt
            # 指纹缺失/不一致而重绘，也不重新后处理，避免已有文件被重复消耗或覆盖。
            if resume_skip_existing_enabled() and not resume_force_rebuild_enabled():
                if resume_strict_image_prompt_match_enabled() and not image_prompt_sidecar_matches(existing_path, p_name, p_text):
                    pending.append((p_name, p_text, img_save_path))
                    if logger:
                        logger(f"♻️ {p_name} 已有图片但 Prompt 指纹不匹配；因已开启严格匹配，将重新生成。")
                    continue
                if resume_touch_existing_images_enabled():
                    postprocess_generated_image(existing_path, p_text, logger=logger, prompt_name=p_name)
                done_count += 1
                if logger and os.path.abspath(existing_path) != os.path.abspath(img_save_path):
                    logger(f"📁 已在子目录发现已有图片并跳过重做：{os.path.relpath(existing_path, images_dir)}")
                continue

            if not image_prompt_sidecar_matches(existing_path, p_name, p_text):
                pending.append((p_name, p_text, img_save_path))
                if logger:
                    logger(f"♻️ {p_name} 已有图片但缺少/不匹配当前 API Prompt 指纹，将按新版提示词重新生成。")
                continue
            postprocess_generated_image(existing_path, p_text, logger=logger, prompt_name=p_name)
            done_count += 1
            if logger and os.path.abspath(existing_path) != os.path.abspath(img_save_path):
                logger(f"📁 已在子目录发现并后处理已有图片：{os.path.relpath(existing_path, images_dir)}")
        else:
            pending.append((p_name, p_text, img_save_path))
    if logger and prompts:
        logger(f"🎨 配图状态：共 {len(prompts)} 张，已完成 {done_count} 张，待生成 {len(pending)} 张。")
    return prompts, pending, done_count


def _sync_cover_home_metadata_to_images_dir(script_path: str, images_dir: str, logger=None) -> str:
    """把章节根目录的封面/首页元信息同步到配图目录，确保 A1/A2 后处理一定能就近读取。"""
    try:
        if not script_path or not images_dir:
            return ""
        ch_dir = os.path.dirname(os.path.abspath(script_path))
        src = _find_cover_home_metadata_file_near_dir(ch_dir, max_depth=2)
        if not is_nonempty_file(src):
            return ""
        os.makedirs(images_dir, exist_ok=True)
        dst = os.path.join(images_dir, "0_封面首页元信息.txt")
        try:
            if os.path.abspath(src) != os.path.abspath(dst):
                src_txt = read_text_file(src)
                if src_txt and (not os.path.exists(dst) or read_text_file(dst) != src_txt):
                    write_text_file(dst, src_txt)
                    if logger:
                        logger("📌 已同步封面/首页元信息到配图目录，供 A1/A2 后处理就近读取。")
            return dst
        except Exception:
            return src
    except Exception:
        return ""



def ensure_all_generated_images_postprocessed(script_path: str, images_dir: str, logger=None) -> dict:
    """对已生成图片再做一遍幂等后处理，保证断点续跑/网页手动图也能统一盖章。"""
    prompt_source_path = get_preferred_prompt_source_path(script_path)
    if not images_dir or not os.path.isdir(images_dir):
        return {"ok": 0, "failed": 0, "skipped": 0}
    _sync_cover_home_metadata_to_images_dir(script_path, images_dir, logger=logger)
    result = postprocess_image_folder(
        images_dir,
        role="auto",
        prompt_file=prompt_source_path if is_nonempty_file(prompt_source_path) else "",
        recursive=True,
        logger=logger,
    )
    return result


def infer_resume_status(md_path: str, script_path: str, images_dir: str, logger=None) -> dict:
    """汇总当前章节的断点状态，用于日志提示和自动跳步。v113 不再依赖 Markdown 解析结果。"""
    ch_dir = os.path.dirname(os.path.abspath(script_path)) if script_path else ""
    chapter_pdf_path = os.path.join(ch_dir, "00_章节原文_PDF直传模型.pdf") if ch_dir else ""
    status = {
        "chapter_pdf": is_nonempty_file(chapter_pdf_path, min_bytes=1000),
        "legacy_md": is_nonempty_file(md_path),
        "script": is_nonempty_file(script_path),
        "lrc": is_nonempty_file(os.path.splitext(script_path)[0] + ".lrc"),
        "images_total": 0,
        "images_done": 0,
        "images_pending": 0,
    }
    if status["script"]:
        try:
            prompts, pending, done_count = summarize_image_resume_state(script_path, images_dir, logger=None)
            status["images_total"] = len(prompts)
            status["images_done"] = done_count
            status["images_pending"] = len(pending)
        except Exception:
            pass
    if logger:
        logger(
            "📌 当前文件状态："
            f"章节PDF={'已准备' if status['chapter_pdf'] else '未准备'}，"
            f"脚本={'已完成' if status['script'] else '未完成'}，"
            f"LRC={'已完成' if status['lrc'] else '未完成'}，"
            f"配图={status['images_done']}/{status['images_total']}"
        )
    return status


def _normalize_chapter_dir_key(text: str) -> str:
    """把目录名/章节标题标准化，用于识别旧版本输出目录。"""
    s = unicodedata.normalize("NFKC", str(text or "")).lower()
    s = re.sub(r"[\s_\-—–:：、,，.．/\\()（）\[\]【】'\"“”‘’]+", "", s)
    return s.strip()


def _chapter_output_marker_paths(ch_dir: str) -> list:
    """断点续跑判定用的稳定输出文件。"""
    return [
        os.path.join(ch_dir, "parsed_content.md"),
        os.path.join(ch_dir, "00_章节原文_PDF直传模型.pdf"),
        os.path.join(ch_dir, "10_导读脚本_最终版.txt"),
        os.path.join(ch_dir, "1_导读脚本.lrc"),
        os.path.join(ch_dir, "1_导读脚本_台词.txt"),
        os.path.join(ch_dir, "1_导读脚本_纯台词脚本.txt"),
        os.path.join(ch_dir, "10_导读脚本_最终版_12_绘图提示词_逐图对应_台词驱动.txt"),
        os.path.join(ch_dir, "1_导读脚本_绘图脚本.txt"),
        os.path.join(ch_dir, "1_导读脚本_视频简介.txt"),
        os.path.join(ch_dir, "1_导读脚本_短视频总结.txt"),
        os.path.join(ch_dir, "10_导读脚本_最终版_08_图文对齐脚本_审阅版.txt"),
        os.path.join(ch_dir, "10_导读脚本_最终版_09_图文对齐总脚本_拆分依据.txt"),
        os.path.join(ch_dir, "1_导读脚本_初稿绘图脚本.txt"),
        os.path.join(ch_dir, "1_导读脚本_初稿台词_未标图号.txt"),
        os.path.join(ch_dir, "1_导读脚本_初稿台词_已标图号.txt"),
    ]


def chapter_output_has_progress(ch_dir: str) -> bool:
    """只要章节目录中已有任一阶段产物，就认为可断点续跑。"""
    if not ch_dir or not os.path.isdir(ch_dir):
        return False
    for marker in _chapter_output_marker_paths(ch_dir):
        if is_nonempty_file(marker, min_bytes=20):
            return True
    for sub in ("2_分镜配图", "单独生成的配图"):
        img_dir = os.path.join(ch_dir, sub)
        if os.path.isdir(img_dir):
            try:
                for name in os.listdir(img_dir):
                    if name.lower().endswith((".png", ".jpg", ".jpeg", ".webp")) and is_nonempty_file(os.path.join(img_dir, name), min_bytes=1000):
                        return True
            except Exception:
                pass
    # 网页手动模式可能只生成了桥接提示词/手动配图提示词，也应显示为可续跑，避免用户误以为没做过。
    for bridge_name in ("90_网页手动输入桥接_legacy", "90_网页手动输入桥接"):
        bridge_dir = os.path.join(ch_dir, bridge_name)
        if os.path.isdir(bridge_dir):
            try:
                for root, _dirs, files in os.walk(bridge_dir):
                    for name in files:
                        if name.lower().endswith((".txt", ".md")) and is_nonempty_file(os.path.join(root, name), min_bytes=20):
                            return True
            except Exception:
                pass
    return False


def build_chapter_output_dir_candidates(out_dir: str, title: str, idx_in_toc: int, meta: dict | None = None) -> list:
    """生成新旧版本都可能使用过的章节目录名候选。"""
    meta = dict(meta or parse_chapter_title_metadata(title, idx_in_toc))
    clean_title = str(meta.get("title_clean") or title or "").strip()
    raw_title = str(title or "").strip()
    prefix_values = []

    def _add_prefix(value):
        value = str(value or "").strip()
        if not value:
            return
        m = re.search(r"\d+", value)
        if m:
            n = int(m.group(0))
            for item in (f"{n:02d}", f"{n:03d}", str(n)):
                if item not in prefix_values:
                    prefix_values.append(item)
        elif value not in prefix_values:
            prefix_values.append(value)

    _add_prefix(meta.get("number_raw"))
    _add_prefix(meta.get("chapter_number"))
    _add_prefix(idx_in_toc + 1)  # 兼容旧版：用 PDF 目录下标做前缀，Part 会把序号顶偏。
    canonical_prefix = chapter_dir_prefix_from_meta(meta, idx_in_toc)
    if canonical_prefix not in prefix_values:
        prefix_values.insert(0, canonical_prefix)

    safe_titles = []
    # 新目录名保留更完整的章节标题；同时加入旧版 35 字符截断候选，保证断点续跑能找到旧目录。
    for t in (clean_title, raw_title):
        for limit in (180, 90, 35):
            st = safe_filename(t, max_len=limit)
            if st and st not in safe_titles:
                safe_titles.append(st)
    candidates = []
    for prefix in prefix_values:
        for st in safe_titles:
            p = os.path.join(out_dir, f"{prefix}_{st}")
            if p not in candidates:
                candidates.append(p)
    return candidates


def resolve_chapter_output_dir(out_dir: str, title: str, idx_in_toc: int, meta: dict | None = None, logger=None) -> str:
    """定位章节输出目录；优先复用已有产物所在的旧目录，实现真正断点续跑。"""
    meta = dict(meta or parse_chapter_title_metadata(title, idx_in_toc))
    candidates = build_chapter_output_dir_candidates(out_dir, title, idx_in_toc, meta)
    canonical = candidates[0] if candidates else os.path.join(out_dir, f"{idx_in_toc + 1:02d}_{safe_filename(title)}")

    # 1) 精确候选目录中，只要已有产物就直接复用。
    for cand in candidates:
        if chapter_output_has_progress(cand):
            if logger and os.path.abspath(cand) != os.path.abspath(canonical):
                logger(f"♻️ 检测到旧版已操作目录，继续复用：{os.path.basename(cand)}")
            return cand

    # 2) 如果候选目录已存在但暂时没有阶段产物，优先使用第一个已存在候选，避免重复建目录。
    for cand in candidates:
        if os.path.isdir(cand):
            return cand

    # 3) 扫描输出根目录，兼容历史版本的不同前缀/标题清洗方式。
    clean_title = str(meta.get("title_clean") or title or "").strip()
    raw_title = str(title or "").strip()
    title_keys = [
        _normalize_chapter_dir_key(clean_title),
        _normalize_chapter_dir_key(raw_title),
    ]
    title_keys = [k for i, k in enumerate(title_keys) if k and k not in title_keys[:i]]
    number_candidates = set()
    for value in (meta.get("number_raw"), meta.get("chapter_number"), idx_in_toc + 1):
        m = re.search(r"\d+", str(value or ""))
        if m:
            number_candidates.add(int(m.group(0)))
    # 3) 扫描输出根目录，兼容历史版本的不同前缀/标题清洗方式。
    # 先按“章节序号 + 已有产物”匹配。每集小标题/短视频总结可能会因提示词变化而不同，
    # 但章节序号是断点续跑的稳定锚点；因此已有章节优先按序号跳过/续跑。
    number_only_matches = []
    best = None
    best_score = -1
    try:
        for name in os.listdir(out_dir):
            path = os.path.join(out_dir, name)
            if not os.path.isdir(path):
                continue
            key = _normalize_chapter_dir_key(name)
            if not key:
                continue
            m = re.match(r"^(\d{1,4})[_\-\s]", name)
            has_number = bool(m and int(m.group(1)) in number_candidates)
            has_progress = chapter_output_has_progress(path)
            if has_number and has_progress:
                try:
                    mtime = os.path.getmtime(path)
                except Exception:
                    mtime = 0
                # 完整标题目录优先，其次旧目录；同序号多目录时选已有产物更新的目录。
                completeness = len(str(name or ""))
                number_only_matches.append((mtime, completeness, path))
            score = 0
            if title_keys and any(tk and tk in key for tk in title_keys):
                score += 10
            if has_number:
                score += 5
            if has_progress:
                score += 4
            # 必须至少命中标题或真实章节号；已有产物的同序号目录允许直接复用。
            if score > best_score and score >= 9:
                best = path
                best_score = score
    except Exception:
        best = None
        number_only_matches = []
    if number_only_matches:
        number_only_matches.sort(key=lambda item: (item[0], item[1]), reverse=True)
        best_num_path = number_only_matches[0][2]
        if logger and os.path.abspath(best_num_path) != os.path.abspath(canonical):
            logger(f"♻️ 按章节序号识别到已有输出，继续断点续跑：{os.path.basename(best_num_path)}")
        return best_num_path
    if best:
        if logger and os.path.abspath(best) != os.path.abspath(canonical):
            logger(f"♻️ 检测到历史输出目录，继续断点续跑：{os.path.basename(best)}")
        return best
    return canonical
