# Auto-generated split runtime module.
# Source: backup/AutoMediaProducer_integrated_postprocess_spec.py lines 2235-3528.
# Do not edit this file alone; edit the canonical source and run tools/sync_split_runtime.py.



def sanitize_grok_api_key(api_key: str) -> str:
    """清洗 Grok/x.ai API Key，避免请求头里出现换行、空格、引号或误粘贴的 Bearer 前缀。"""
    key = api_key or ""
    key = key.replace("\ufeff", "").replace("\u200b", "").replace("\u200c", "").replace("\u200d", "")
    key = key.strip().strip('\'"')
    if key.lower().startswith("bearer "):
        key = key[7:]
    # requests 的 Header value 不能包含换行、回车、制表符或前后空格；这里直接删除所有空白字符。
    key = re.sub(r"\s+", "", key)
    return key


def is_valid_grok_api_key(api_key: str) -> bool:
    key = sanitize_grok_api_key(api_key)
    return key.startswith("xai-") and len(key) >= 40 and " " not in key and "\n" not in key and "\r" not in key


def load_grok_api_key() -> str:
    """按安全优先级读取 Grok/x.ai API Key：环境变量 > 本地密钥文件 > 空。"""
    env_key = sanitize_grok_api_key(os.environ.get("XAI_API_KEY", ""))
    if env_key:
        return env_key
    for key_path in (GROK_KEY_FILE, os.path.join(os.getcwd(), "xai_api_key.txt")):
        try:
            if os.path.exists(key_path):
                return sanitize_grok_api_key(open(key_path, "r", encoding="utf-8").read())
        except Exception:
            continue
    return ""


def save_grok_api_key(api_key: str) -> bool:
    """把清洗后的 Key 保存到脚本同目录的本地文件，避免写死在源码里。"""
    api_key = sanitize_grok_api_key(api_key)
    if not api_key:
        return False
    with open(GROK_KEY_FILE, "w", encoding="utf-8", newline="") as f:
        f.write(api_key)
    try:
        os.chmod(GROK_KEY_FILE, 0o600)
    except Exception:
        pass
    return True


def sanitize_gemini_api_key(api_key: str) -> str:
    """清洗 Gemini API Key，避免请求头或 SDK 参数里混入换行、空格、引号或误粘贴的 Bearer 前缀。"""
    key = api_key or ""
    key = key.replace("\ufeff", "").replace("\u200b", "").replace("\u200c", "").replace("\u200d", "")
    key = key.strip().strip('\'"')
    if key.lower().startswith("bearer "):
        key = key[7:]
    key = re.sub(r"\s+", "", key)
    return key


def is_valid_gemini_api_key(api_key: str) -> bool:
    key = sanitize_gemini_api_key(api_key)
    # Google AI Studio keys usually start with AIza, but keep this tolerant for workspace/project keys.
    return len(key) >= 20 and " " not in key and "\n" not in key and "\r" not in key


def load_gemini_api_key() -> str:
    """按安全优先级读取 Gemini API Key：环境变量 > 本地密钥文件 > 空。"""
    env_key = sanitize_gemini_api_key(os.environ.get("GEMINI_API_KEY", ""))
    if env_key:

        return env_key
    for key_path in (GEMINI_KEY_FILE, os.path.join(os.getcwd(), "gemini_api_key.txt")):
        try:
            if os.path.exists(key_path):
                return sanitize_gemini_api_key(open(key_path, "r", encoding="utf-8").read())

        except Exception:
            continue
    return ""


def save_gemini_api_key(api_key: str) -> bool:
    """把清洗后的 Gemini Key 保存到脚本同目录的本地文件，避免写死在源码里。"""
    api_key = sanitize_gemini_api_key(api_key)
    if not api_key:
        return False
    with open(GEMINI_KEY_FILE, "w", encoding="utf-8", newline="") as f:
        f.write(api_key)
    try:
        os.chmod(GEMINI_KEY_FILE, 0o600)
    except Exception:
        pass
    return True


def sanitize_openai_api_key(api_key: str) -> str:
    """清洗 OpenAI API Key，避免 SDK 参数里混入换行、空格、引号或误粘贴的 Bearer 前缀。"""
    key = api_key or ""
    key = key.replace("\ufeff", "").replace("\u200b", "").replace("\u200c", "").replace("\u200d", "")
    key = "".join(ch for ch in key if ord(ch) >= 32 and ord(ch) != 127)
    key = key.strip().strip('"\'')
    if key.lower().startswith("bearer "):
        key = key[7:]
    key = re.sub(r"\s+", "", key)
    return key


def is_valid_openai_api_key(api_key: str) -> bool:
    key = sanitize_openai_api_key(api_key)
    return len(key) >= 20 and " " not in key and "\n" not in key and "\r" not in key


def load_openai_api_key() -> str:
    """按安全优先级读取 OpenAI API Key：环境变量 > 本地密钥文件 > 空。"""
    env_key = sanitize_openai_api_key(os.environ.get("OPENAI_API_KEY", ""))
    if env_key:
        return env_key
    for key_path in (OPENAI_KEY_FILE, os.path.join(os.getcwd(), "openai_api_key.txt")):
        try:
            if os.path.exists(key_path):
                return sanitize_openai_api_key(open(key_path, "r", encoding="utf-8").read())
        except Exception:
            continue
    return ""


def save_openai_api_key(api_key: str) -> bool:
    """把清洗后的 OpenAI Key 保存到脚本同目录的本地文件，避免写死在源码里。"""
    api_key = sanitize_openai_api_key(api_key)
    if not api_key:
        return False
    with open(OPENAI_KEY_FILE, "w", encoding="utf-8", newline="") as f:
        f.write(api_key)
    try:
        os.chmod(OPENAI_KEY_FILE, 0o600)
    except Exception:
        pass
    return True


def load_image_api_key() -> str:
    """读取 GPT Image 2 独立中转 Key。"""
    env_key = sanitize_openai_api_key(os.environ.get("IMAGE_API_KEY", "") or os.environ.get("OPENAI_IMAGE_API_KEY", ""))
    if env_key:
        return env_key
    for key_path in (globals().get("IMAGE_KEY_FILE", os.path.join(SCRIPT_DIR, "image_api_key.txt")), os.path.join(os.getcwd(), "image_api_key.txt"), os.path.join(os.getcwd(), "openai_image_api_key.txt")):
        try:
            if os.path.exists(key_path):
                return sanitize_openai_api_key(open(key_path, "r", encoding="utf-8").read())
        except Exception:
            continue
    return ""


def save_image_api_key(api_key: str) -> bool:
    """把 GPT Image 2 独立中转 Key 保存到 image_api_key.txt。"""
    api_key = sanitize_openai_api_key(api_key)
    if not api_key:
        return False
    path = globals().get("IMAGE_KEY_FILE", os.path.join(SCRIPT_DIR, "image_api_key.txt"))
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(api_key)
    try:
        os.chmod(path, 0o600)
    except Exception:
        pass
    return True


def sanitize_chatshare_api_key(api_key: str) -> str:
    """清洗 ChatShare API Key，避免 Authorization 请求头里出现换行、空格或误粘贴的 Bearer 前缀。"""
    return sanitize_openai_api_key(api_key)


def is_valid_chatshare_api_key(api_key: str) -> bool:
    key = sanitize_chatshare_api_key(api_key)
    return len(key) >= 10 and " " not in key and "\n" not in key and "\r" not in key


def load_chatshare_api_key() -> str:
    """ChatShare has been removed from the merged app; never load legacy keys."""
    return ""


def save_chatshare_api_key(api_key: str) -> bool:
    """ChatShare has been removed from the merged app; do not persist keys."""
    return False


def sanitize_deepseek_api_key(api_key: str) -> str:
    """清洗 DeepSeek 官方 API Key。"""
    return sanitize_openai_api_key(api_key)


def is_valid_deepseek_api_key(api_key: str) -> bool:
    key = sanitize_deepseek_api_key(api_key)
    return len(key) >= 20 and " " not in key and "\n" not in key and "\r" not in key


def load_deepseek_api_key() -> str:
    """按安全优先级读取 DeepSeek API Key：环境变量 > 本地密钥文件 > 空。"""
    env_key = sanitize_deepseek_api_key(os.environ.get("DEEPSEEK_API_KEY", ""))
    if env_key:
        return env_key
    for key_path in (DEEPSEEK_KEY_FILE, os.path.join(os.getcwd(), "deepseek_api_key.txt")):
        try:
            if os.path.exists(key_path):
                return sanitize_deepseek_api_key(open(key_path, "r", encoding="utf-8").read())
        except Exception:
            continue
    return ""


def save_deepseek_api_key(api_key: str) -> bool:
    """把清洗后的 DeepSeek Key 保存到脚本同目录的本地文件。"""
    api_key = sanitize_deepseek_api_key(api_key)
    if not api_key:
        return False
    with open(DEEPSEEK_KEY_FILE, "w", encoding="utf-8", newline="") as f:
        f.write(api_key)
    try:
        os.chmod(DEEPSEEK_KEY_FILE, 0o600)
    except Exception:
        pass
    return True


def sanitize_doubao_api_key(api_key: str) -> str:
    """清洗豆包/火山方舟 API Key。"""
    return sanitize_openai_api_key(api_key)


def is_valid_doubao_api_key(api_key: str) -> bool:
    key = sanitize_doubao_api_key(api_key)
    return key.startswith("ark-") and len(key) >= 20 and " " not in key and "\n" not in key and "\r" not in key


def sanitize_doubao_endpoint_id(endpoint_id: str) -> str:
    """清洗并提取火山方舟推理接入点 ID。

    允许用户从代码片段、日志或说明文字中粘贴，例如：
    model="ep-20260531xxxx"，会自动提取 ep-...。
    但不会接受中文占位符，例如 ep-请填写推理接入点ID。
    """
    ep = str(endpoint_id or "")
    ep = ep.replace("\ufeff", "").replace("\u200b", "").replace("\u200c", "").replace("\u200d", "")
    ep = ep.strip().strip('"\'')
    # 从粘贴的代码 / 日志 / URL 参数中提取第一个看起来像 Endpoint ID 的片段。
    m = re.search(r"(?<![A-Za-z0-9_-])(ep-[A-Za-z0-9][A-Za-z0-9_-]{5,127})(?![A-Za-z0-9_-])", ep)
    if m:
        return m.group(1)
    ep = re.sub(r"\s+", "", ep)
    return ep


def is_valid_doubao_endpoint_id(endpoint_id: str) -> bool:
    ep = sanitize_doubao_endpoint_id(endpoint_id)
    # Endpoint ID 只允许 ASCII 字母、数字、下划线、连字符；拒绝中文占位符。
    return bool(re.fullmatch(r"ep-[A-Za-z0-9][A-Za-z0-9_-]{5,127}", ep or ""))


def load_doubao_api_key() -> str:
    env_key = sanitize_doubao_api_key(os.environ.get("ARK_API_KEY", "") or os.environ.get("DOUBAO_API_KEY", ""))
    if env_key:
        return env_key
    for key_path in (DOUBAO_KEY_FILE, os.path.join(os.getcwd(), "doubao_api_key.txt"), os.path.join(os.getcwd(), "ark_api_key.txt")):
        try:
            if os.path.exists(key_path):
                return sanitize_doubao_api_key(open(key_path, "r", encoding="utf-8").read())
        except Exception:
            continue
    return ""


def save_doubao_api_key(api_key: str) -> bool:
    api_key = sanitize_doubao_api_key(api_key)
    if not is_valid_doubao_api_key(api_key):
        return False
    with open(DOUBAO_KEY_FILE, "w", encoding="utf-8", newline="") as f:
        f.write(api_key)
    try:
        os.chmod(DOUBAO_KEY_FILE, 0o600)
    except Exception:
        pass
    return True


def load_doubao_endpoint_id() -> str:
    env_ep = sanitize_doubao_endpoint_id(os.environ.get("ARK_ENDPOINT_ID", "") or os.environ.get("DOUBAO_ENDPOINT_ID", ""))
    if env_ep:
        return env_ep
    for ep_path in (DOUBAO_ENDPOINT_FILE, os.path.join(os.getcwd(), "doubao_endpoint_id.txt"), os.path.join(os.getcwd(), "ark_endpoint_id.txt")):
        try:
            if os.path.exists(ep_path):
                return sanitize_doubao_endpoint_id(open(ep_path, "r", encoding="utf-8").read())
        except Exception:
            continue
    return ""


def save_doubao_endpoint_id(endpoint_id: str) -> bool:
    endpoint_id = sanitize_doubao_endpoint_id(endpoint_id)
    if not is_valid_doubao_endpoint_id(endpoint_id):
        return False
    with open(DOUBAO_ENDPOINT_FILE, "w", encoding="utf-8", newline="") as f:
        f.write(endpoint_id)
    try:
        os.chmod(DOUBAO_ENDPOINT_FILE, 0o600)
    except Exception:
        pass
    return True


def save_doubao_settings(api_key: str, endpoint_id: str) -> bool:
    ok_key = save_doubao_api_key(api_key)
    ok_ep = save_doubao_endpoint_id(endpoint_id)
    return bool(ok_key and ok_ep)


# ================== 任务状态 / 后处理配置 ==================
task_queue = queue.Queue()

def make_book_task_state(slot_index: int = 0) -> dict:
    slot_index = max(0, min(MAX_PARALLEL_BOOK_TASKS - 1, int(slot_index or 0)))
    return {
        "slot_index": slot_index,
        "slot_label": f"任务{slot_index + 1}",
        "is_running": False,
        "current_toc": [],
        "current_pdf_path": "",
        "pdf_path": "",
        "out_dir": BASE_SAVE_FOLDER,
        "log_lines": [],
    }

state = make_book_task_state(0)
ui_manager = None

# ================== 全局视觉硬约束：字体体系、字号、神经科学教材风格与科学插图防伪 ==================
# 精简锁定版：所有公共元素只从这里取规格。绘图提示词可描述画面内容，但不得改公共元素规格。
FINAL_ONLY_OUTPUT_MODE = os.environ.get("QUANLAN_FINAL_ONLY_OUTPUT_MODE", "1").strip().lower() in {"1", "true", "yes", "y", "on"}

PUBLIC_BRAND_TEXT = "QuanLan BrainScience®"
PUBLIC_PALETTE = {
    "background": "#EEF5FB",
    "main_text": "#132A52",
    "brand": "#132A52",
    "accent": "#9CB3CC",
    "divider": "#C9D8E8",
}

LOCKED_MOBILE_FONT_SPEC = (
    "Mobile vertical output only. Use a unified soft rigorous flat medical illustration style typography system: one Chinese sans-serif family and one English sans-serif family; "
    "rounded, calm, academic, readable; no decorative lettering and no random font changes."
)

LOCKED_MEDICAL_FONT_STYLE_SPEC = (
    "Explanation-first biomedical illustration style: light neutral background, clean biomedical linework, restrained but vivid color blocks, soft gradients, subtle depth, "
    "matte editorial texture, no sci-fi glow, no cyber grid, no neon, no HUD, no hologram, no futuristic interface."
)

LOCKED_CENTERED_LAYOUT_SPEC = (
    "Every cover/title/brand public element is centered by default. "
    "Diagram labels may align to anatomy, but public elements must never drift."
)

PUBLIC_ELEMENT_STYLE_LOCK = (
    "Use exactly this public palette on every image: background #EEF5FB, main text #132A52, "
    "brand/logo #132A52, accent #9CB3CC, divider #C9D8E8. "
    "Bottom 10% of canvas should stay visually calm: no dense labels or hard visual clutter."
)


# ================== v119：封面 / 首页 / 结尾页参考图排版 + 提示词中心可配置后处理规范 ==================
# 核心原则：AI 只生成无文字背景图；所有文字、遮罩、透明度、字号和位置全部由 Pillow 后处理控制。
AI_BACKGROUND_PROMPT_COMMON = (
    "Create a clean explanatory biomedical education illustration with slight dimensional depth for a neuroscience vertical video. "
    "Use soft light blue-white academic colors, gentle editorial contrast, matte surfaces, clean vector-like biomedical linework, medically plausible neurons, synapses, receptors, circuits, cells, or chapter-supported structures. "
    "The atmosphere should feel like a high-quality life-science explanatory figure, not a technology advertisement, flashy CGI close-up, or sci-fi interface. "
    "Do not plan fixed text space inside the raw image; fixed typography is handled only after generation. "
    "No visible text, no letters, no numbers, no logo, no captions, no labels, no watermark, no pseudo-text. "
    "Strictly no sci-fi, no cyberpunk, no neon, no HUD, no hologram, no futuristic panels, no data streams, no cinematic 3D, no metal/mecha aesthetics."
)
AI_BACKGROUND_PROMPT_COVER_HOME_IDENTICAL = (
    "Create ONE shared no-text Master Background for all four A pages: A1 WeChat cover, A2 WeChat home, A01 Bilibili cover, and A02 Bilibili home. Only A1 is allowed to be a real image-generation prompt. A2, A01 and A02 must be derived by software crop from the exact same master image; do not separately generate them. "
    "Design the master with square-safe composition from the whole-chapter summary: the core biomedical subject and chapter-level relationship stay in the central 60% area, and all four edges remain low-information extendable background. Final software crops are A1=3:4, A2=9:16, A01=4:3, A02=16:9. "
    "This must be a theme-specific biomedical key visual summarizing the chapter/script, based on the GLOBAL SCRIPT THEME in the prompt; never use a generic neuron wallpaper or decorative DNA background. "
    "Use concrete chapter-related biological structures, pathways, mechanisms, brain regions, cells, synapses, receptors, circuits, experiments, or disease processes when they are mentioned by the script theme. "
    "explanation-first biomedical illustration style medical education illustration, light neutral background, restrained blue-white palette, slight dimensional depth, concrete chapter-specific biomedical motif; post-processing handles all typography and masks. "
    "No visible text, no letters, no numbers, no logo, no captions, no labels, no watermark, no pseudo-text. "
    "No sci-fi HUD, no cyberpunk lighting, no neon neural webs, no glowing brain core, no holographic anatomy, no futuristic interface, no space/cosmic feeling."
)
AI_BACKGROUND_PROMPT_ENDING = (
    "Create a 9:16 no-text explanatory biomedical closing-page key visual with slight dimensional depth that summarizes and resolves the same GLOBAL SCRIPT THEME; never use a generic decorative end-card background. "
    "Use concrete chapter-related biological motifs or mechanisms from the script theme, soft light blue-white matte background, low contrast, and no card or typography drawn by the image model. "
    "No visible text, no letters, no numbers, no logo, no captions, no labels, no watermark, no pseudo-text. "
    "No sci-fi HUD, no cyberpunk, no neon, no holographic brain, no futuristic UI, no data streams, no cinematic 3D."
)

LAYERED_PRODUCTION_CONTRACT = """
【分层生产总规范：必须遵守】
你不是单纯写图像生成 Prompt，而是生成“可执行的分层生产方案”。

核心原则：
1. 图像模型只生成无文字医学背景图或无文字医学基础结构图。
2. 所有文字、品牌、书名、作者、章节号、章节标题、科学标签、箭头、图例、坐标、字号、字体、颜色、对齐方式，全部由后处理程序确定性渲染。
3. A/C 页面禁止把任何可读文字交给图像模型绘制；图像 Prompt 必须包含 No visible text / no letters / no numbers / no logo / no labels / no watermark / no pseudo-text。B 页面例外：允许为教学清晰度直接绘制简短英文科学标签与箭头，但不得出现中文、品牌标识、水印或伪文字。
4. A1、A2、A01、A02 四张 A 图必须来自同一张“全章总结”无字 Master Background：只允许 A1 写真实生图 Prompt；A2/A01/A02 只能写“同 A1_Master_Background，由程序裁切得到”，不得写独立画面、独立构图、独立风格或新增元素。母图按方形安全构图设计，中心 60% 保留核心视觉，四边为低信息量延展背景；程序裁切为 A1=3:4、A2=9:16、A01=4:3、A02=16:9。
5. B 系列内容页优先采用“平面教学图 / 综述图”结构；AI 层可以直接生成关键英文科学标签、短注释、离子/受体/递质名称、简洁箭头和小标题，但不得出现中文、品牌标识、水印或无意义伪文字。后处理仍可补充少量统一标签与遮罩。
6. 所有基础图必须是柔和 严谨医学插画风格 / 医学教育插画 / 生物医学综述图版审美：crisp line/form definition, light neutral background, restrained academic colors, soft dimensional shading, medically plausible morphology, explanation-first clarity。
7. 严禁 sci-fi brain、neon neural network、HUD、cyberpunk、hologram、glassmorphism card、digital dashboard、data streams、cosmic particles、cinematic 3D、fantasy anatomy、金属机甲、霓虹科技广告感。
8. 配图与口播文案必须高度相关：每个 Shot 的画面主体必须直接服务对应 Voiceover 的核心概念、机制、对象、证据或问题，不得使用泛泛的神经元/脑科学装饰背景代替具体内容；如果旁白讲受体、突触、神经环路、记忆、动作电位、细胞、疾病机制或实验发现，AI Prompt 必须把这些对象转化为明确的医学视觉主体。
9. 配图不仅要与台词中的元素相呼应，还必须与台词的逻辑关系相呼应：因果关系要画出原因到结果的方向；对比关系要画出差异或并列；递进关系要画出层级推进；转折关系要画出前后变化；时序关系要画出过程步骤；机制解释要画出结构之间的功能联系。

输出结构必须分成两部分：
====================
【Part One: Pure Voiceover Script】
只输出中文旁白。不要镜头说明、不要视觉提示、不要引用。

====================
【Part Two: Production Asset Plan】
每张图必须使用以下结构：
Shot_01:
Page Type:
Purpose:
AI Image Layer:
  Image Role:
  Aspect Ratio:
  Actual Generation Resolution Rule:
  Prompt:
  Negative Prompt:
Post-processing Layer:
  Final Canvas:
  Source Background:
  Crop / Scale / Extend Rule:
  Text Overlay Spec:
  Vector Overlay Spec:
  Safe Area:
  Bottom Empty Zone:
Quality Control:

A1 页面：Page Type 必须是 A1. Video Cover Page；AI Prompt 必须描述同一张 9:16 Master Background，无文字。
A2 页面：Page Type 必须是 A2. Home Page；Source Background 必须说明复用 A1 的 Master Background，无文字。
B 页面：Page Type 必须是 B. Main Content Page；AI Prompt 只描述无文字医学基础图；标签和箭头写入 Post-processing Layer。
C 页面：Page Type 必须是 C. Brand Page；AI Prompt 只描述无文字结尾背景；品牌文字写入 Post-processing Layer。

图文相关性硬规则：
- 每个 Shot 的 Purpose 必须明确说明它服务哪一句/哪一组 Voiceover 的核心意思。
- 每个 AI Image Layer > Prompt 必须优先写出该图的 biomedical visual subject，并与对应 Voiceover 一致。
- B 系列内容页禁止只写 generic neurons / abstract brain background / decorative particles；必须画出与文案直接相关的结构、流程、因果关系或实验对象。
- 逻辑关系必须可视化：不能只把台词里的名词元素堆在同一张图中；要让构图体现该句的因果、对比、递进、转折、时序、层级或机制关系。
- 画面不需要把台词写成文字；相关性体现在医学对象、构图和机制表达上，文字仍由后处理或字幕承担。

变量规则：不得输出未替换变量；不得自行编造未知书名、作者、版次、章节名。缺失时写空字段或说明缺失，不要猜测。
""".strip()




def _style_specific_layered_contract_base(style_key: str) -> str:
    """科学经典单风格：Production Asset Plan 只保留科学/医学图解协议。"""
    return LAYERED_PRODUCTION_CONTRACT


def build_layered_production_contract(style_key: str | None = None) -> str:
    """返回科学经典解读的 Production Asset Plan 硬结构。"""
    visual_line = (
        "B 系列内容页采用“无字科学/医学基础图 + 后处理简短英文关键词图注 + 后处理矢量标签/箭头”结构。"
        "AI 层必须画出与文案直接相关的科学结构、流程、因果、实验或机制关系，不得用泛泛装饰背景代替具体内容。"
        "A1/A2/A01/A02 使用同一张整章内容总结无字 Master Background：A1 是唯一真实生图 Prompt，A2/A01/A02 只允许写“同 A1 母图、裁切输出”，并由程序裁切为 3:4、9:16、4:3、16:9；该背景必须由本章全章总结生成，不能使用无关章节素材、泛脑图或装饰背景。C 品牌页也必须使用本章全章总结型背景。"
        "公共元素只属于全澜脑科学 / QuanLan BrainScience；整体为干净克制的科学教育插图/严谨医学插画风格；严禁科幻 HUD、霓虹神经网络、全息界面、金属机甲和泛泛科技广告感。"
    )
    return (LAYERED_PRODUCTION_CONTRACT + "\n\n【科学经典补充】\n" + visual_line).strip()


def build_content_style_script_quality_block(style_key: str | None = None) -> str:
    return (
        "【科学经典审校硬性约束】\n"
        "科学概念、实验、机制、结构、疾病或历史发现必须依据章节 PDF；不能凭空扩写、不能把推测说成定论。"
        "章节介绍前必须先用生活化科学钩子疑问吸引读者，再过渡到本章核心问题；A2 章节提要句必须作为第3句。"
        "如果原文证据不足，必须用‘更稳妥的理解是’或‘这一点不能从本章直接推出’进行边界提示；输出前内部自检问题、机制、证据、边界之间是否衔接，不能突然跳结论。"
    )

# ================== v119：后处理参数默认规范源（提示词中心可覆盖） ==================
# 坐标全部按相对百分比从左上角计算；AI 只生成无文字背景图。
POSTPROCESS_STABLE_SPEC = {'coordinate_system': {'type': 'relative_percent', 'origin': 'top_left', 'width': 'W', 'height': 'H'},
 'cover_page': {'ratio': '3:4', 'recommended_size_token_saver': '768x1024', 'recommended_size_high': '1440x1920'},
 'home_page': {'ratio': '9:16', 'recommended_size_token_saver': '1080x1920', 'recommended_size_high': '2160x3840'},
 'bilibili_cover_page': {'ratio': '4:3', 'recommended_size_token_saver': '1024x768', 'recommended_size_high': '1920x1440'},
 'bilibili_home_page': {'ratio': '16:9', 'recommended_size_token_saver': '1024x576', 'recommended_size_high': '1920x1080'},
 'ending_page': {'ratio': '9:16', 'recommended_size_token_saver': '1080x1920', 'recommended_size_high': '1440x2560'},
 'background_opacity': {'cover': 0.22, 'home': 0.2, 'ending': 0.2, 'range': [0.12, 0.3]},
  'center_mask': {'cover': {'enabled': False, 'fill': '#FFFFFF', 'opacity': 0.0, 'blur': 0},
                  'home': {'enabled': False, 'fill': '#FFFFFF', 'opacity': 0.0, 'blur': 0},
                  'ending': {'enabled': False,
                             'fill': '#FFFFFF',
                             'opacity': 0.0,
                             'border_radius_ratio_w': 0.0,
                             'blur': 0}},
 'cover_home_readability_layer': {'all': {'enabled': True,
                                          'edge_vignette_opacity': 0.10,
                                          'top_gradient_opacity': 0.08,
                                          'bottom_gradient_opacity': 0.10,
                                          'center_glow_opacity': 0.08,
                                          'center_glow_width': 0.84,
                                          'center_glow_height': 0.70}},
  'content_safe_zone_mask': {'enabled': True, 'top_ratio': 0.20, 'bottom_ratio': 0.20, 'fill': 'auto', 'opacity': 0.96, 'edge_fade_ratio': 0.0, 'boundary_line_opacity': 0.0},
 'cover_layout': {'brand_y': 0.055,
                  'brand_center_x': 0.5,
                  'book_title_cn_y': 0.25,
                  'book_title_en_y': 0.335,
                  'edition_y': 0.43,
                  'author_y': 0.475,
                  'chapter_no_y': 0.615,
                  'chapter_title_cn_y': 0.695,
                  'chapter_title_en_y': 0.78},
 'home_layout': {'brand_y': 0.055,
                 'brand_center_x': 0.5,
                 'book_title_cn_y': 0.285,
                 'book_title_en_y': 0.355,
                 'edition_y': 0.43,
                 'author_y': 0.47,
                 'chapter_no_y': 0.585,
                 'chapter_title_cn_y': 0.655,
                 'chapter_title_en_y': 0.725},
 'cover_font_size': {'brand': 0.048,
                     'book_title_cn': 0.073,
                     'book_title_en': 0.037,
                     'edition': 0.026,
                     'author': 0.022,
                     'chapter_no': 0.031,
                     'chapter_title_cn_max': 0.062,
                     'chapter_title_cn_min': 0.038,
                     'chapter_title_en': 0.028},
 'home_font_size': {'brand': 0.048,
                    'book_title_cn': 0.056,
                    'book_title_en': 0.03,
                    'edition': 0.02,
                    'author': 0.0185,
                    'chapter_no': 0.025,
                    'chapter_title_cn_max': 0.048,
                    'chapter_title_cn_min': 0.029,
                    'chapter_title_en': 0.022},
 'chapter_title_cn_dynamic_font': {'max_width_ratio': 0.72,
                                   'line_height': 1.12,
                                   'align': 'center',
                                   'wrap': True,
                                   'max_lines': 2},
 'ending_layout': {'card_x': 0.14,
                   'card_y': 0.14,
                   'card_width': 0.72,
                   'card_height': 0.68,
                   'brand_cn_y': 0.29,
                   'brand_en_y': 0.37,
                   'divider_1_y': 0.46,
                   'slogan_cn_y': 0.54,
                   'slogan_en_y': 0.6,
                   'divider_2_y': 0.69,
                   'follow_text_y': 0.77},
 'ending_font_size': {'brand_cn': 0.058, 'brand_en': 0.03, 'slogan_cn': 0.036, 'slogan_en': 0.025, 'follow_text': 0.03},
 'ending_card_style': {'fill': '#FFFFFF',
                       'opacity': 0.0,
                       'border_radius_ratio_w': 0.0,
                       'blur': 0,
                       'shadow': {'enabled': False, 'opacity': 0.0, 'blur': 0, 'offset_y_ratio_h': 0.0}},
 'ornaments': {'cover_brand': {'enabled': False,
                               'y_offset_ratio_h': 0.02,
                               'outer_margin_ratio_w': 0.06,
                               'gap_ratio_w': 0.03,
                               'dot_radius_ratio_w': 0.0032},
               'home_brand': {'enabled': False,
                              'y_offset_ratio_h': 0.014,
                              'outer_margin_ratio_w': 0.15,
                              'gap_ratio_w': 0.03,
                              'dot_radius_ratio_w': 0.0032},
               'home_dividers': {'enabled': True, 'ys': [0.535], 'width_ratio_w': 0.28, 'dot_radius_ratio_w': 0.003},
               'ending_dividers': {'enabled': True, 'width_ratio_w': 0.5, 'dot_radius_ratio_w': 0.0036},
               'cover_dividers': {'enabled': True, 'ys': [0.57], 'width_ratio_w': 0.34, 'dot_radius_ratio_w': 0.0032}},
 'colors': {'primary_text': '#132A52',
            'secondary_text': '#223A5F',
            'light_line': '#9CB3CC',
            'background_tint': '#EEF5FB',
            'brand_text': '#2D4467'},
 'font_weight': {'brand': 400,
                 'book_title_cn': 700,
                 'book_title_en': 500,
                 'edition': 500,
                 'author': 400,
                 'chapter_no': 500,
                 'chapter_title_cn': 700,
                 'chapter_title_en': 500,
                 'ending_brand_cn': 700,
                 'ending_slogan_cn': 600}}
# 运行时后处理规范：默认使用 POSTPROCESS_STABLE_SPEC；“提示词中心 > 后处理参数”可覆盖任意字段。
POSTPROCESS_BASE_SPEC = json.loads(json.dumps(POSTPROCESS_STABLE_SPEC, ensure_ascii=False))
POSTPROCESS_ACTIVE_SPEC = None


def _deep_merge_dict(base: dict, override: dict) -> dict:
    """递归合并后处理参数；只覆盖用户写到的字段，未写字段保持默认稳定值。"""
    result = dict(base or {})
    for key, value in (override or {}).items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = _deep_merge_dict(result.get(key, {}), value)
        else:
            result[key] = value
    return result


def _parse_scalar_config_value(value: str):
    text = str(value or "").strip().strip(",")
    if not text:
        return ""
    if (text.startswith('"') and text.endswith('"')) or (text.startswith("'") and text.endswith("'")):
        return text[1:-1]
    low = text.lower()
    if low in {"true", "yes", "on"}:
        return True
    if low in {"false", "no", "off"}:
        return False
    if low in {"none", "null"}:
        return None
    m = re.match(r"^(-?\d+(?:\.\d+)?)\s*%\s*(?:of\s*)?[WHwh]?\s*$", text)
    if m:
        try:
            return float(m.group(1)) / 100.0
        except Exception:
            return text
    try:
        if re.match(r"^-?\d+$", text):
            return int(text)
        if re.match(r"^-?\d+\.\d+$", text):
            return float(text)
    except Exception:
        pass
    return text


def _normalize_postprocess_config_value(value):
    """允许用户粘贴 4.5%H / 6%W / 80%W 这类写法，内部统一转为 0.045 / 0.06 / 0.80。"""
    if isinstance(value, dict):
        out = {}
        for key, sub in value.items():
            norm_key = str(key)
            # 兼容用户自然写法：border_radius / offset_y 转为程序实际字段。

            if norm_key == "border_radius":
                norm_key = "border_radius_ratio_w"
            elif norm_key == "offset_y":
                norm_key = "offset_y_ratio_h"
            out[norm_key] = _normalize_postprocess_config_value(sub)
        return out

    if isinstance(value, list):
        return [_normalize_postprocess_config_value(v) for v in value]
    if isinstance(value, str):
        return _parse_scalar_config_value(value)
    return value


def _extract_first_json_object(text: str) -> str:
    raw = str(text or "").strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.I).strip()
    raw = re.sub(r"\s*```$", "", raw).strip()
    if raw.startswith("{") and raw.endswith("}"):
        return raw
    start = raw.find("{")
    end = raw.rfind("}")
    if start >= 0 and end > start:
        return raw[start:end + 1]
    return ""


def parse_postprocess_requirements_text(text: str) -> dict:
    """解析提示词中心里的后处理参数。
    支持两种方式：
    1) JSON 对象；
    2) 简写覆盖行，如：cover_layout.brand_y = 0.045 或 ending_card_style.shadow.opacity = 0.02。
    无法解析的自然语言会被保留在配置文件里，但不会改变确定性后处理，避免凭空猜测。
    """
    raw = str(text or "").strip()
    if not raw:
        return {}
    json_part = _extract_first_json_object(raw)
    if json_part:
        try:
            data = json.loads(json_part)
            return _normalize_postprocess_config_value(data if isinstance(data, dict) else {})
        except Exception:
            pass

    data = {}
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith(("#", "//")):
            continue
        m = re.match(r"^([A-Za-z0-9_\.]+)\s*(?:=|:)\s*(.+?)\s*$", line)
        if not m:
            continue
        path, value = m.group(1), _normalize_postprocess_config_value(_parse_scalar_config_value(m.group(2)))
        cur = data
        parts = [p for p in path.split(".") if p]
        for part in parts[:-1]:
            cur = cur.setdefault(part, {})
        if parts:
            cur[parts[-1]] = value
    return data



def _compact_json_for_prompt(value, max_chars: int = 9000) -> str:
    """给大模型看的紧凑 JSON；超过长度时保守截断，避免 UI 规范化调用过重。"""
    try:
        text = json.dumps(value, ensure_ascii=False, indent=2)
    except Exception:
        text = str(value or "")
    if len(text) > max_chars:
        return text[:max_chars].rstrip() + "\n...（后续字段已截断；未提到的字段保持当前值）"
    return text



def _strip_prompt_text_from_llm(raw: str) -> str:
    """清理大模型返回的提示词文本，去掉代码围栏和解释性包裹。"""
    s = str(raw or "").strip()
    if not s:
        return ""
    s = re.sub(r"^```(?:text|markdown|md|prompt)?\s*", "", s, flags=re.I).strip()
    s = re.sub(r"\s*```\s*$", "", s).strip()
    # 部分模型会加“以下是优化后的提示词：”，只去掉开头一行，不碰正文结构。
    s = re.sub(r"^(?:以下是|这是|优化后的|整合后的).{0,24}(?:提示词|模板)[:：]\s*\n", "", s).strip()
    return s


def build_prompt_template_normalization_prompt(natural_request: str, current_template: str, template_key: str, style_key: str) -> str:
    """把用户对脚本/润色提示词的模糊要求转换为可直接替换的完整提示词模板。"""
    template_key = str(template_key or "").strip()
    style_key = normalize_content_style(style_key)
    kind = "脚本生成提示词" if template_key == "script_generation" else "润色提示词"
    required_placeholders = "{source_text}、{book_name_cn}、{book_name_en}、{chapter_title_cn}、{chapter_title_en}、{chapter_number}、{authors_en}、{version}、{toc_text}、{next_theme}" if template_key == "script_generation" else "{voiceover_text}、{source_text}、{toc_text}"
    extra_rules = """
【脚本生成提示词特别要求】
1. 必须保留程序可解析结构：Part One: Pure Voiceover Script 与 Part Two: Production Asset Plan。
2. 必须保留 Part One / Part Two、A1/A2/B/C、无字图片和图文对应结构；脚本生成模型必须按 5~9 秒/镜头同步规划台词与 B 系列配图；成片默认 90–150 秒、最高不超过 180 秒；每个 B Shot 的可朗读台词不得超过 9 秒。
3. 不要把具体书名、章节、作者写死；必须继续使用占位符。
4. 优化应优先提高微信视频号前 60 秒留存：开头更快进入问题、句子更短、技术密度更低；不能虚构原文事实，也不能强行制造浮夸反转。
5. 必须加入“输出前内部自检脚本逻辑是否跳跃”的要求：主线清楚、段落有承接、概念转场有桥、结尾回扣开头；自检结果不输出。
""" if template_key == "script_generation" else """
【润色提示词特别要求】
1. 必须保留逐句锁定、不能增删句、不能合并句、不能移动图号/LRC 锚点等安全规则。
2. 可以强化故事感、钩子、节奏、共鸣、去除解读腔，但只能在原句含义范围内润色。
3. 不要输出示例成稿；要输出一份可复用的润色系统提示词模板。
4. 必须继续使用占位符，不要写死具体书名、章节、人物或原文观点。
"""
    return f"""你是一个严格的提示词工程师，正在为一个“书籍解读短视频自动生产程序”改写{kind}。

当前内容风格：{style_key}

你的任务：把用户的模糊要求转换成一份可以直接替换程序当前模板的【完整{kind}】。不是补丁，不是摘要，而是完整新版模板。

【输出硬规则】
1. 只输出完整提示词正文，不要 Markdown 标题、不要解释、不要代码围栏。
2. 必须把用户新要求和当前模板整合，不要只重复用户的话。
3. 必须保留当前模板中对程序解析至关重要的结构、占位符和边界条件。
4. 必须保留这些占位符中当前模板已经使用到的部分，并优先保留可用占位符：{required_placeholders}。
5. 不要添加程序无法识别的新占位符；如果需要表达变量，只能使用当前模板已有占位符或普通中文说明。
6. 不要写死某一本书、某一章、某个作者、某个具体 PDF 内容。
7. 如果用户要求含糊，例如“更抓人”“更高级”“更像爆款”“更有故事感”，请自动转成具体可执行的提示词规则。
{extra_rules}

【当前完整模板】
{str(current_template or '').strip()}

【用户新的模糊要求】
{str(natural_request or '').strip()}
"""


def normalize_prompt_template_with_llm(
    natural_request: str,
    current_template: str,
    template_key: str,
    style_key: str,
    engine: str,
    logger=None,
    check_cancel=None,
    *,
    grok_key: str = "",
    gemini_key: str = "",
    openai_key: str = "",
    chatshare_key: str = "",
) -> str:
    """调用 GPT 文本模型，把模糊脚本/润色要求转换为完整可替换提示词模板。"""
    natural_request = str(natural_request or "").strip()
    current_template = str(current_template or "").strip()
    if not natural_request:
        return ""
    prompt = build_prompt_template_normalization_prompt(natural_request, current_template, template_key, style_key)
    label = "脚本提示词" if template_key == "script_generation" else "润色提示词"
    if logger:
        logger(f"🧠 正在调用 {describe_text_engine(engine)} 优化{label}...")
    raw = generate_text_by_engine(
        engine,
        prompt,
        logger or print,
        check_cancel=check_cancel,
        grok_key=grok_key,
        gemini_key=gemini_key,
        openai_key=openai_key,
        chatshare_key=chatshare_key,
    )
    cleaned = _strip_prompt_text_from_llm(raw)
    if not cleaned or len(cleaned) < 200:
        if logger:
            logger(f"⚠️ 大模型没有返回可用的{label}；未修改当前模板。")
        return ""
    if template_key == "script_generation":
        must_have = ["Part One", "Part Two", "{source_text}"]
    else:
        must_have = ["{voiceover_text}"]
    missing = [x for x in must_have if x not in cleaned]
    if missing:
        if logger:
            logger(f"⚠️ 大模型返回的{label}缺少关键结构/占位符：{', '.join(missing)}；未修改当前模板。")
        return ""
    if logger:
        logger(f"✅ {label}已由大模型整合为完整模板，可保存后立即用于运行。")
    return cleaned


def build_postprocess_normalization_prompt(natural_request: str, current_config_text: str = "") -> str:
    """把用户的模糊后处理要求交给文本大模型，要求它输出程序可解析的固定 JSON 覆盖对象。"""
    current_override = parse_postprocess_requirements_text(current_config_text)
    current_effective = _deep_merge_dict(POSTPROCESS_BASE_SPEC, current_override)
    allowed_schema = _compact_json_for_prompt(POSTPROCESS_BASE_SPEC, max_chars=11000)
    current_effective_text = _compact_json_for_prompt(current_effective, max_chars=11000)
    return (
        "你是一个严格的自动化排版参数转换器。你的任务是把用户对封面页、首页图、结尾页的自然语言后处理要求，"
        "转换成程序可以直接解析的 JSON 覆盖对象。\n\n"
        "【输出硬规则】\n"
        "1. 只输出 JSON object，不要 Markdown、不要解释、不要代码围栏。\n"
        "2. 只能使用【已支持字段结构】里出现过的字段；不要发明新字段。\n"
        "3. 只输出需要修改的字段；没有提到的字段不要输出。\n"
        "4. 百分比坐标和字号必须转成 0~1 小数，例如 7.8%H 写 0.078，80%W 写 0.8。\n"
        "5. 颜色必须使用 #RRGGBB。布尔值用 true/false。\n"
        "6. 遮罩、透明度、玻璃卡片、装饰线、字号、坐标都必须落到确定数值，不能写“更大一点”“靠上一些”等模糊词。\n"
        "7. 如果用户要求和现有字段无关，忽略该部分，不要编造。\n"
        "8. 书名、作者、章节名属于动态内容，不要写死；除非用户明确要求修改 ending_public_text。\n\n"
        "【已支持字段结构 / 默认值】\n"
        f"{allowed_schema}\n\n"
        "【当前有效后处理配置】\n"
        f"{current_effective_text}\n\n"
        "【用户新的模糊后处理要求】\n"
        f"{str(natural_request or '').strip()}\n"
    )


def normalize_postprocess_requirements_with_llm(
    natural_request: str,
    current_config_text: str,
    engine: str,
    logger=None,
    check_cancel=None,
    *,
    grok_key: str = "",
    gemini_key: str = "",
    openai_key: str = "",
    chatshare_key: str = "",
) -> str:
    """调用 GPT 文本模型，把自然语言后处理要求转换为完整固定 JSON 配置文本。"""
    natural_request = str(natural_request or "").strip()
    if not natural_request:
        return ""
    prompt = build_postprocess_normalization_prompt(natural_request, current_config_text=current_config_text)
    if logger:
        logger(f"🧠 正在调用 {describe_text_engine(engine)} 规范化后处理要求...")
    raw = generate_text_by_engine(
        engine,
        prompt,
        logger or print,
        check_cancel=check_cancel,
        grok_key=grok_key,
        gemini_key=gemini_key,
        openai_key=openai_key,
        chatshare_key=chatshare_key,
    )
    patch = parse_postprocess_requirements_text(raw)
    if not patch:
        if logger:
            logger("⚠️ 大模型没有返回可解析的后处理 JSON；未修改当前后处理参数。")
        return ""
    current_override = parse_postprocess_requirements_text(current_config_text)
    current_effective = _deep_merge_dict(POSTPROCESS_BASE_SPEC, current_override)
    merged = _deep_merge_dict(current_effective, patch)
    merged = _normalize_postprocess_config_value(merged)
    if logger:
        logger("✅ 后处理要求已由大模型转换为固定 JSON，可保存后立即用于运行。")
    return json.dumps(merged, ensure_ascii=False, indent=2)


def _hex_to_rgb_tuple(value, fallback=(0, 0, 0)) -> tuple[int, int, int]:
    try:
        text = str(value or "").strip()
        if text.startswith("#"):
            text = text[1:]
        if len(text) == 3:
            text = "".join(ch * 2 for ch in text)
        if len(text) >= 6:
            return (int(text[0:2], 16), int(text[2:4], 16), int(text[4:6], 16))
    except Exception:
        pass
    return tuple(fallback[:3])


def _rgba_from_hex(value, fallback_rgb, alpha=255):
    rgb = _hex_to_rgb_tuple(value, fallback_rgb)
    return (*rgb, int(alpha))


def _enforce_current_cover_home_layout_spec(spec: dict) -> dict:
    """科学著作解读单模板：封面/首页/结尾页只使用全澜脑科学视觉系统。"""
    spec = dict(spec or {})
    style_key = DEFAULT_CONTENT_STYLE
    spec["coordinate_system"] = {"type": "relative_percent", "origin": "top_left", "width": "W", "height": "H"}
    spec.setdefault("cover_page", {}).update({"ratio": "3:4", "recommended_size_token_saver": "768x1024", "recommended_size_high": "1440x1920"})
    spec.setdefault("home_page", {}).update({"ratio": "9:16", "recommended_size_token_saver": "1080x1920", "recommended_size_high": "2160x3840"})
    spec.setdefault("bilibili_cover_page", {}).update({"ratio": "4:3", "recommended_size_token_saver": "1024x768", "recommended_size_high": "1920x1440"})
    spec.setdefault("bilibili_home_page", {}).update({"ratio": "16:9", "recommended_size_token_saver": "1024x576", "recommended_size_high": "1920x1080"})
    spec.setdefault("ending_page", {}).update({"ratio": "9:16", "recommended_size_token_saver": "1080x1920", "recommended_size_high": "1440x2560"})

    # 科学经典解读：保持既有 严谨医学插画风格固定规范不动。
    spec["background_opacity"] = {"cover": 0.38, "home": 0.36, "ending": 0.40, "range": [0.22, 0.52]}
    spec.setdefault("center_mask", {}).update({
        "cover": {"enabled": True, "fill": "#FFFFFF", "opacity": 0.72, "blur": 0, "mode": "full_canvas"},
        "home": {"enabled": True, "fill": "#FFFFFF", "opacity": 0.68, "blur": 0, "mode": "full_canvas"},
        "ending": {"enabled": True, "fill": "#FFFFFF", "opacity": 0.76, "border_radius_ratio_w": 0.0, "blur": 0, "mode": "full_canvas"},
    })
    spec["cover_layout"] = {"brand_y": 0.055, "brand_center_x": 0.50, "book_title_cn_y": 0.250, "book_title_en_y": 0.335, "edition_y": 0.430, "author_y": 0.475, "chapter_no_y": 0.615, "chapter_title_cn_y": 0.695, "chapter_title_en_y": 0.780}
    spec["home_layout"] = {"brand_y": 0.055, "brand_center_x": 0.50, "book_title_cn_y": 0.285, "book_title_en_y": 0.355, "edition_y": 0.430, "author_y": 0.470, "chapter_no_y": 0.585, "chapter_title_cn_y": 0.655, "chapter_title_en_y": 0.725}
    spec["cover_font_size"] = {"brand": 0.048, "book_title_cn": 0.073, "book_title_en": 0.037, "edition": 0.026, "author": 0.022, "chapter_no": 0.031, "chapter_title_cn_max": 0.062, "chapter_title_cn_min": 0.038, "chapter_title_en": 0.028}
    spec["home_font_size"] = {"brand": 0.048, "book_title_cn": 0.056, "book_title_en": 0.030, "edition": 0.020, "author": 0.0185, "chapter_no": 0.025, "chapter_title_cn_max": 0.048, "chapter_title_cn_min": 0.029, "chapter_title_en": 0.022}
    spec.setdefault("chapter_title_cn_dynamic_font", {}).update({"max_width_ratio": 0.72, "line_height": 1.12, "align": "center", "wrap": True, "max_lines": 2})
    spec["ending_layout"] = {"card_x": 0.14, "card_y": 0.14, "card_width": 0.72, "card_height": 0.68, "brand_cn_y": 0.345, "brand_en_y": 0.418, "divider_1_y": 0.470, "slogan_cn_y": 0.522, "slogan_en_y": 0.572, "divider_2_y": 0.620, "follow_text_y": 0.674, "center_x": 0.50, "text_align": "center"}
    spec["ending_font_size"] = {"brand_cn": 0.058, "brand_en": 0.030, "slogan_cn": 0.036, "slogan_en": 0.025, "follow_text": 0.030}
    spec.setdefault("ending_card_style", {}).update({"fill": "#FFFFFF", "opacity": 0.12, "border_radius_ratio_w": 0.045, "blur": 18, "shadow": {"enabled": True, "opacity": 0.10, "blur": 26, "offset_y_ratio_h": 0.008}})
    ornaments = spec.setdefault("ornaments", {})
    ornaments["cover_brand"] = {"enabled": False, "y_offset_ratio_h": 0.020, "outer_margin_ratio_w": 0.06, "gap_ratio_w": 0.030, "dot_radius_ratio_w": 0.0032}
    ornaments["home_brand"] = {"enabled": False, "y_offset_ratio_h": 0.014, "outer_margin_ratio_w": 0.15, "gap_ratio_w": 0.030, "dot_radius_ratio_w": 0.0032}
    ornaments["cover_dividers"] = {"enabled": True, "ys": [0.570], "width_ratio_w": 0.34, "dot_radius_ratio_w": 0.0032}
    ornaments["home_dividers"] = {"enabled": True, "ys": [0.535], "width_ratio_w": 0.28, "dot_radius_ratio_w": 0.0030}
    ornaments["ending_dividers"] = {"enabled": True, "width_ratio_w": 0.50, "dot_radius_ratio_w": 0.0036}
    spec["colors"] = {"primary_text": "#132A52", "secondary_text": "#223A5F", "light_line": "#9CB3CC", "background_tint": "#EEF5FB", "brand_text": "#2D4467"}
    spec["font_weight"] = {"brand": 400, "book_title_cn": 700, "book_title_en": 500, "edition": 500, "author": 400, "chapter_no": 500, "chapter_title_cn": 700, "chapter_title_en": 500, "ending_brand_cn": 800, "ending_slogan_cn": 800, "ending_slogan_en": 700, "ending_follow_text": 700}
    spec["ending_public_text"] = {"brand_cn": "全澜脑科学®", "brand_en": "QuanLan BrainScience®", "slogan_cn": "更强大脑 更美生活", "slogan_en": "Stronger Brains, Better Lives", "follow_text": ""}
    spec["ending_template_variant"] = "science_brainscience_clean"
    spec["public_brand"] = {"top_logo": "QuanLan BrainScience®", "content_logo": "QuanLan BrainScience®", "brand_color": "#132A52", "render_mode": "image_asset"}
    spec["logo_image_assets"] = {
        "en": {"file": "assets/logos/en/logo_en_tight.png", "text": "QuanLan BrainScience®", "reference_size": [559, 45]},
        "zh": {"file": "assets/logos/zh/logo_zh_tight.png", "text": "全澜脑科学®", "reference_size": [280, 45]},
        "reference_canvas": [1024, 1360],
        "standard_top_left": [233, 82],
        "standard_visible_size": [553, 45],
        "render_contract": "PNG image scaling and coordinate placement only; no font/text layout for logo."
    }
    spec["cover_logo_style"] = {"mode": "top_center", "x_ratio": 0.50, "y_ratio": 0.0603, "font_ratio_h": 0.0331, "visual_height_ratio_h": 0.0331, "opacity": 245, "max_width_ratio": 0.54, "render_mode": "image_asset", "asset_lang": "en"}
    spec["brand_logo_overlay"] = {
        "enabled": True,
        "applies_to": ["cover", "home"],
        "render_layer": "post_processing_only",
        "render_mode": "image_asset",
        "asset_lang": "en",
        "asset_path": "assets/logos/en/logo_en_tight.png",
        "anchor": "top_center",
        "reference_canvas": "1024x1360",
        "bbox_ratio": {"left": 0.2275, "top": 0.0603, "width": 0.54, "height": 0.0331, "center_x": 0.5, "center_y": 0.0769},
        "position": {"center_x": 0.5, "center_y": 0.0769, "top_y": 0.0603, "max_width_ratio_w": 0.54, "visual_height_ratio_h": 0.0331},
        "centering_rule": {"enabled": True, "center_by": "transparent_png_final_bbox", "main_text_and_registered_mark_as_one_visual_group": True, "do_not_center_by_text_start_x": True, "final_group_center_x_must_equal": 0.5, "horizontal_error_tolerance_ratio_w": 0.001},
        "color": "#2D4467",
        "opacity": 0.96,
        "effects": {"stroke": False, "shadow": False, "glow": False, "gradient": False, "background_box": False}
    }
    spec["font_family"] = {"brand": []}
    spec["text_opacity"] = {"brand": 0.96}
    spec["letter_spacing"] = {"brand_em": 0.0}

    spec["content_logo_style"] = {"mode": "top_left", "x_ratio": 0.0556, "y_ratio": 0.0313, "font_ratio_h": 0.0229, "visual_height_ratio_h": 0.0229, "opacity": 230, "max_width_ratio": 0.42, "render_mode": "image_asset", "asset_lang": "en"}
    spec["subtitle_guide_line"] = {"y_ratio": 0.80, "margin_x_ratio": 0.08, "width_ratio": 0.0014, "dash_ratio": 0.018, "gap_ratio": 0.010, "color": "#6B8FAE", "opacity": 108}
    # 科学封面强制同时显示中文章名和英文章名；提示词中心或旧配置不得关闭 Chapter Title EN。
    spec["cover_home_visibility"] = {"show_book_en": True, "show_chapter_en": True, "show_author": True, "show_version": True, "show_chapter_no": True}
    spec["cover_template_variant"] = "science_cell"
    return spec


def refresh_postprocess_runtime_config(logger=None) -> dict:
    """从提示词中心加载后处理参数，并刷新所有后处理全局变量。"""
    global POSTPROCESS_STABLE_SPEC, POSTPROCESS_ACTIVE_SPEC
    global POSTPROCESS_BACKGROUND_TINT_RGB, POSTPROCESS_PRIMARY_TEXT, POSTPROCESS_SECONDARY_TEXT, POSTPROCESS_LIGHT_LINE, POSTPROCESS_MASK_WHITE
    global POSTPROCESS_BG_OPACITY, COVER_MASK_SPEC, HOME_MASK_SPEC, ENDING_MASK_SPEC, ENDING_CARD_SHADOW_SPEC
    global COVER_LAYOUT_SPEC, HOME_LAYOUT_SPEC, COVER_FONT_RATIO_SPEC, HOME_FONT_RATIO_SPEC, CHAPTER_TITLE_CN_DYNAMIC_SPEC
    global ENDING_LAYOUT_SPEC, ENDING_FONT_RATIO_SPEC, ENDING_PUBLIC_TEXT
    global PUBLIC_TOP_LOGO_TEXT, CONTENT_LOGO_TEXT, PUBLIC_BRAND_TEXT, PUBLIC_LOGO_COLOR, CONTENT_LOGO_COLOR

    override = {}
    try:
        templates = load_prompt_templates(prompt_scope=DEFAULT_PROMPT_SCOPE)
        override = parse_postprocess_requirements_text(templates.get("postprocess_requirements", ""))
    except Exception as e:
        if logger:
            logger(f"⚠️ 后处理参数读取失败，使用内置默认：{str(e)[:120]}")
        override = {}

    spec = _deep_merge_dict(POSTPROCESS_BASE_SPEC, override)
    spec = _enforce_current_cover_home_layout_spec(spec)
    spec = _normalize_postprocess_config_value(spec)
    POSTPROCESS_STABLE_SPEC = spec
    POSTPROCESS_ACTIVE_SPEC = spec

    colors = spec.get("colors", {}) or {}
    POSTPROCESS_BACKGROUND_TINT_RGB = _hex_to_rgb_tuple(colors.get("background_tint"), (238, 245, 251))
    POSTPROCESS_PRIMARY_TEXT = _rgba_from_hex(colors.get("primary_text"), (19, 42, 82), 248)
    POSTPROCESS_SECONDARY_TEXT = _rgba_from_hex(colors.get("secondary_text"), (34, 58, 95), 238)
    POSTPROCESS_LIGHT_LINE = _rgba_from_hex(colors.get("light_line"), (156, 179, 204), 130)
    POSTPROCESS_MASK_WHITE = _hex_to_rgb_tuple("#FFFFFF", (255, 255, 255))

    POSTPROCESS_BG_OPACITY = {
        "tweet_cover_27_36": float((spec.get("background_opacity", {}) or {}).get("cover", 0.30)),
        "cover_27_48": float((spec.get("background_opacity", {}) or {}).get("cover", 0.30)),
        "bilibili_cover_4_3": float((spec.get("background_opacity", {}) or {}).get("cover", 0.30)),
        "home_page_27_48": float((spec.get("background_opacity", {}) or {}).get("home", 0.28)),
        "bilibili_home_16_9": float((spec.get("background_opacity", {}) or {}).get("home", 0.28)),
        "brand_end_page_27_48": float((spec.get("background_opacity", {}) or {}).get("ending", 0.30)),
    }

    masks = spec.get("center_mask", {}) or {}
    COVER_MASK_SPEC = dict(masks.get("cover", {}) or {})
    HOME_MASK_SPEC = dict(masks.get("home", {}) or {})
    ENDING_MASK_SPEC = dict(masks.get("ending", {}) or {})
    ENDING_CARD_SHADOW_SPEC = dict(((spec.get("ending_card_style", {}) or {}).get("shadow", {}) or {}))

    COVER_LAYOUT_SPEC = dict(spec.get("cover_layout", {}) or {})
    HOME_LAYOUT_SPEC = dict(spec.get("home_layout", {}) or {})
    COVER_FONT_RATIO_SPEC = dict(spec.get("cover_font_size", {}) or {})
    HOME_FONT_RATIO_SPEC = dict(spec.get("home_font_size", {}) or {})
    CHAPTER_TITLE_CN_DYNAMIC_SPEC = dict(spec.get("chapter_title_cn_dynamic_font", {}) or {})

    ENDING_LAYOUT_SPEC = dict(spec.get("ending_layout", {}) or {})
    ENDING_FONT_RATIO_SPEC = dict(spec.get("ending_font_size", {}) or {})
    public_text = spec.get("ending_public_text", {}) if isinstance(spec.get("ending_public_text", {}), dict) else {}
    ENDING_PUBLIC_TEXT = {
        "brand_cn": str(public_text.get("brand_cn", "全澜脑科学®")),
        "brand_en": str(public_text.get("brand_en", "QuanLan BrainScience®")),
        "slogan_cn": str(public_text.get("slogan_cn", "更强大脑 更美生活")),
        "slogan_en": str(public_text.get("slogan_en", "Stronger Brains, Better Lives")),
        "follow_text": str(public_text.get("follow_text", "")),
    }
    public_brand = spec.get("public_brand", {}) if isinstance(spec.get("public_brand", {}), dict) else {}
    top_logo = str(public_brand.get("top_logo") or public_brand.get("content_logo") or ENDING_PUBLIC_TEXT.get("brand_en") or ENDING_PUBLIC_TEXT.get("brand_cn") or "QuanLan BrainScience®")
    content_logo = str(public_brand.get("content_logo") or top_logo)
    try:
        PUBLIC_TOP_LOGO_TEXT = top_logo
        CONTENT_LOGO_TEXT = content_logo
        PUBLIC_BRAND_TEXT = content_logo
        brand_color = _hex_to_rgb_tuple(public_brand.get("brand_color") or colors.get("primary_text"), (31, 58, 95))
        PUBLIC_LOGO_COLOR = brand_color
        CONTENT_LOGO_COLOR = brand_color
    except Exception:
        pass

    content_logo_style = spec.get("content_logo_style", {}) if isinstance(spec.get("content_logo_style", {}), dict) else {}
    try:
        CONTENT_LOGO_X_RATIO = float(content_logo_style.get("x_ratio", 120.0 / 2160.0))
        CONTENT_LOGO_Y_RATIO = float(content_logo_style.get("y_ratio", 120.0 / 3840.0))
        CONTENT_LOGO_FONT_RATIO_H = float(content_logo_style.get("font_ratio_h", 88.0 / 3840.0))
        CONTENT_LOGO_OPACITY = int(content_logo_style.get("opacity", 230))
    except Exception:
        CONTENT_LOGO_X_RATIO = 120.0 / 2160.0
        CONTENT_LOGO_Y_RATIO = 120.0 / 3840.0
        CONTENT_LOGO_FONT_RATIO_H = 88.0 / 3840.0
        CONTENT_LOGO_OPACITY = 230

    guide = spec.get("subtitle_guide_line", {}) if isinstance(spec.get("subtitle_guide_line", {}), dict) else {}
    try:
        SUBTITLE_GUIDE_LINE_Y_RATIO = float(guide.get("y_ratio", 0.80))
        SUBTITLE_GUIDE_LINE_MARGIN_X_RATIO = float(guide.get("margin_x_ratio", 0.08))
        SUBTITLE_GUIDE_LINE_WIDTH_RATIO = float(guide.get("width_ratio", 0.0014))
        SUBTITLE_GUIDE_LINE_DASH_RATIO = float(guide.get("dash_ratio", 0.018))
        SUBTITLE_GUIDE_LINE_GAP_RATIO = float(guide.get("gap_ratio", 0.010))
        SUBTITLE_GUIDE_LINE_COLOR = _rgba_from_hex(guide.get("color", "#6B8FAE"), (107, 143, 174), int(guide.get("opacity", 108)))
    except Exception:
        SUBTITLE_GUIDE_LINE_Y_RATIO = 0.80
        SUBTITLE_GUIDE_LINE_MARGIN_X_RATIO = 0.08
        SUBTITLE_GUIDE_LINE_WIDTH_RATIO = 0.0014
        SUBTITLE_GUIDE_LINE_DASH_RATIO = 0.018
        SUBTITLE_GUIDE_LINE_GAP_RATIO = 0.010
        SUBTITLE_GUIDE_LINE_COLOR = (107, 143, 174, 108)
    return spec
