# Auto-generated split runtime module.
# Source: backup/AutoMediaProducer_integrated_postprocess_spec.py lines 6902-7928.
# Do not edit this file alone; edit the canonical source and run tools/sync_split_runtime.py.

SUPPORTED_POSTPROCESS_IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp"}
POSTPROCESS_SIDE_CAR_PROMPT_NAMES = (
    "10_导读脚本_最终版_12_绘图提示词_逐图对应_台词驱动.txt",
    "1_导读脚本_绘图脚本.txt",
    "绘图提示词.txt",
    "绘图脚本.txt",
    "image_prompts.txt",
    "prompts.txt",
)


def decode_hash_u_escapes_text(value: str) -> str:
    """Decode filenames produced as #U4e2d#U6587 after ZIP/Windows transfers."""
    s = str(value or "")
    try:
        return re.sub(r"#U([0-9a-fA-F]{4,6})", lambda m: chr(int(m.group(1), 16)), s)
    except Exception:
        return s



MANUAL_IMAGE_NAMING_RULES = """手动生成图片命名规则（推荐使用固定 A/B/C 页型命名，便于自动后处理）
1. 微信封面（A1 / WeChat Cover）：A1_微信封面.png 或 A1_封面页.png，最终 3:4。
2. 微信首页（A2 / WeChat Home）：A2_微信首页.png 或 A2_首页.png，最终 9:16。
3. B站封面（A01 / Bilibili Cover）：A01_B站封面.png，最终 4:3。
4. B站首页（A02 / Bilibili Home）：A02_B站首页.png，最终 16:9。
5. 内容页（B 系列）：B01.png、B02.png、B03.png……；品牌页（C）：C_品牌页.png。
6. A1、A2、A01、A02 使用同一张“整章内容总结”无字背景，由程序按平台比例裁切，并统一叠加品牌、书名、作者、版本、章节序号、章节中文名、章节英文名。
7. 固定平台图和品牌页均使用全屏蒙版 full_canvas，不允许 raw 图中出现文字、Logo、数字、水印或伪文字。
8. A 系列与 C 页 raw 图禁止任何文字；B 系列 raw 图优先无文字，如确需标注仅允许 1–3 个英文关键词标签，每个 1–2 个词，不允许表格、长段文字、中文、Logo、水印或伪文字。
"""

DRAWING_PROMPT_FILE_MANUAL_HEADER = (
    "【手动绘图使用说明】\n"
    + MANUAL_IMAGE_NAMING_RULES.rstrip()
    + "\n\n【统一后处理说明】\n"
    + "1. 公共元素（Logo、封面标题、品牌页固定文案）由程序统一后处理，请不要手动绘制。\n"
    + "2. B 系列内容页会由后处理套上下20%浅色安全蒙版，强制留出顶部品牌区和底部字幕区；封面页、首页和结尾页不套此内容页蒙版。\n"
    + "3. 封面页和首页会由程序在中文章节名下方叠加英文章节名，英文字号比中文稍小；请不要在 raw 图里手动绘制章节标题。\n"
    + "4. 下面进入正式绘图提示词正文；逐张复制对应图名下的提示词给绘图模型即可。每张图必须贴合该图对应台词的核心概念；A1/A2/A01/A02/C 概括整章主题且 raw 图不带文字，B 系列逐图对应各自台词并以画面关系为主，最多只用 1–3 个英文关键词标签示意，禁止使用泛用背景、表格、说明框和大段文字。\n\n"
)


def write_manual_image_naming_rules(folder_path: str = "", logger=None) -> str:
    """把手动图片命名规则写到目标文件夹，并在日志中提示。"""
    path = ""
    if folder_path and os.path.isdir(folder_path):
        path = os.path.join(folder_path, "00_手动图片命名规则.txt")
        try:
            write_text_file(path, MANUAL_IMAGE_NAMING_RULES.rstrip() + "\n")
        except Exception:
            path = ""
    if logger:
        logger("📌 手动生成图片请按命名规则保存：A1_封面页.png / A2_首页.png / B01.png … / C_品牌页.png；固定约束（安全区/参考线/Logo/文字位置）全部走后处理，B 系列内容页会套上下20%安全蒙版。")
        if path:
            logger(f"   详细命名规则已写入：{path}")
    return path


def normalize_postprocess_role(role: str | None) -> str:
    """把 UI/CLI 传入的角色名标准化；auto 会按文件名和提示词自动识别。"""
    value = str(role or "auto").strip().lower()
    aliases = {
        "auto": "auto",
        "自动": "auto",
        "tweet": "tweet_cover_27_36",
        "tweet_cover": "tweet_cover_27_36",
        "推文": "tweet_cover_27_36",
        "推文封面": "tweet_cover_27_36",
        # 当前工程固定 A1=3:4；通用“封面/cover”不再走旧 4:3 cover_27_48。
        "cover": "tweet_cover_27_36",
        "封面": "tweet_cover_27_36",
        "chapter_cover": "tweet_cover_27_36",
        "home": "home_page_27_48",
        "homepage": "home_page_27_48",
        "home_page": "home_page_27_48",
        "首页": "home_page_27_48",
        "a1": "tweet_cover_27_36",
        "a2": "home_page_27_48",
        "a01": "bilibili_cover_4_3",
        "a02": "bilibili_home_16_9",
        "b站封面": "bilibili_cover_4_3",
        "bilibili_cover": "bilibili_cover_4_3",
        "b站首页": "bilibili_home_16_9",
        "bilibili_home": "bilibili_home_16_9",
        "b": "content_diagram_27_48",
        "c": "brand_end_page_27_48",
        "content": "content_diagram_27_48",
        "内容": "content_diagram_27_48",
        "内容页": "content_diagram_27_48",
        "diagram": "content_diagram_27_48",
        "brand": "brand_end_page_27_48",
        "brand_end": "brand_end_page_27_48",
        "品牌": "brand_end_page_27_48",
        "品牌页": "brand_end_page_27_48",
        "尾页": "brand_end_page_27_48",
        "daily_research_square_visual_summary": "daily_research_square_visual_summary",
    }
    return aliases.get(value, value if value in {"tweet_cover_27_36", "cover_27_48", "home_page_27_48", "bilibili_cover_4_3", "bilibili_home_16_9", "content_diagram_27_48", "brand_end_page_27_48", "daily_research_square_visual_summary"} else "auto")


def infer_visual_role_from_image_name(image_path: str, prompt: str = "", forced_role: str = "auto") -> str:
    """手动文件夹后处理时，根据文件名和可选提示词判断页型。"""
    role = normalize_postprocess_role(forced_role)
    if role != "auto":
        return role
    name = decode_hash_u_escapes_text(os.path.splitext(os.path.basename(str(image_path or "")))[0])
    prompt = decode_hash_u_escapes_text(str(prompt or ""))
    combined = f"{name}\n{prompt}".lower()
    if re.search(r"推文图\s*[_\- ]?0?1|tweet[_\- ]?cover|wechat[_\- ]?cover", combined, flags=re.I):
        return "tweet_cover_27_36"
    if re.search(r"(?:^|[^a-z])a01(?:[^a-z]|$)|bilibili[_\- ]?cover|b站封面|哔哩哔哩封面", combined, flags=re.I):
        return "bilibili_cover_4_3"
    if re.search(r"(?:^|[^a-z])a02(?:[^a-z]|$)|bilibili[_\- ]?home|b站首页|哔哩哔哩首页", combined, flags=re.I):
        return "bilibili_home_16_9"
    if (re.search(r"(?:^|[^a-z])c(?:[^a-z]|$)|(brand|ending|end[_\- ]?page|final[_\- ]?page|尾页|品牌页|结束页|关注页)", name, flags=re.I)
            or re.search(r"(brand\s*(?:end|page)|ending\s*brand|end[_\- ]?page|final[_\- ]?page|尾页|品牌页|结束页|关注页)", prompt, flags=re.I)):
        return "brand_end_page_27_48"
    if re.search(r"(?:^|[^a-z])a2(?:[^a-z]|$)|home\s*page|首页|图[_\- ]?0?2|镜头[_\- ]?0?2|shot[_\- ]?0?2", combined, flags=re.I):
        return "home_page_27_48"
    if re.search(r"(?:^|[^a-z])a1(?:[^a-z]|$)|cover|title[_\- ]?page|chapter[_\- ]?cover|封面|片头|镜头[_\- ]?0?1|shot[_\- ]?0?1", combined, flags=re.I):
        return "tweet_cover_27_36"
    if re.search(r"(?:^|[^a-z])b\d{1,2}(?:[^a-z]|$)", combined, flags=re.I):
        return "content_diagram_27_48"
    if prompt:
        return detect_visual_role(name, prompt)
    return "content_diagram_27_48"



def _load_prompt_map_from_file(prompt_file: str, logger=None) -> dict:
    """读取绘图提示词文件，返回 {提示词名stem: 提示词文本}。"""
    if not prompt_file or not os.path.exists(prompt_file):
        return {}
    try:
        text = read_text_file(prompt_file)
        pairs = ScriptParser.extract_image_prompts(text, logger=None)
        result = {}
        for p_name, p_text in pairs:
            key = decode_hash_u_escapes_text(os.path.splitext(os.path.basename(str(p_name or "")))[0]).strip().lower()
            if key and p_text:
                result[key] = p_text
        if logger and result:
            logger(f"🧾 已读取后处理提示词映射：{os.path.basename(prompt_file)}，共 {len(result)} 条。")
        return result
    except Exception as e:
        if logger:
            logger(f"⚠️ 读取后处理提示词文件失败：{os.path.basename(prompt_file)}；{str(e)[:120]}")
        return {}


def find_nearby_prompt_file_for_folder(folder_path: str) -> str:
    """优先在图片文件夹、父目录中找绘图提示词文件；中文文件名被 #Uxxxx 转义时按内容兜底。"""
    candidates = []
    folder = os.path.abspath(folder_path or "")
    search_bases = []
    if folder:
        cur = folder
        for _ in range(4):
            if cur and os.path.isdir(cur) and cur not in search_bases:
                search_bases.append(cur)
            parent = os.path.dirname(cur)
            if not parent or parent == cur:
                break
            cur = parent
        for base in search_bases[:2]:
            for name in POSTPROCESS_SIDE_CAR_PROMPT_NAMES:
                candidates.append(os.path.join(base, name))
        try:
            for base in search_bases:
                for name in os.listdir(base):
                    decoded = decode_hash_u_escapes_text(name)
                    low = decoded.lower()
                    if low.endswith(("_绘图提示词.txt", "_绘图脚本.txt")) or (low.endswith('.txt') and ("绘图" in decoded or "逐图" in decoded or "台词驱动" in decoded)):
                        candidates.append(os.path.join(base, name))
        except Exception:
            pass
    for path in candidates:
        if path and os.path.exists(path) and is_nonempty_file(path, min_bytes=20):
            return path
    # 最后按内容找，避免 #Uxxxx 文件名或随机文件名导致 prompt 映射丢失。
    try:
        scored = []
        for base in search_bases:
            for name in os.listdir(base):
                if not str(name).lower().endswith('.txt'):
                    continue
                path = os.path.join(base, name)
                if not is_nonempty_file(path, min_bytes=20):
                    continue
                try:
                    if os.path.getsize(path) > 900000:
                        continue
                except Exception:
                    pass
                txt = _read_text_if_exists(path, max_chars=24000) if '_read_text_if_exists' in globals() else read_text_file(path)[:24000]
                if not _looks_like_image_prompt_source_text(txt):
                    continue
                decoded = decode_hash_u_escapes_text(name).lower()
                score = 0
                if '_12_' in decoded or '绘图' in decoded: score += 40
                if '逐图' in decoded: score += 20
                if '台词驱动' in decoded: score += 20
                scored.append((-score, path))
        if scored:
            scored.sort(key=lambda x: (x[0], x[1].lower()))
            return scored[0][1]
    except Exception:
        pass
    return ""


def _prompt_for_image(image_path: str, prompt_map: dict) -> str:
    """用图片文件名匹配提示词；支持完全匹配和包含式匹配。"""
    if not prompt_map:
        return ""
    stem = decode_hash_u_escapes_text(os.path.splitext(os.path.basename(image_path))[0]).strip().lower()
    if stem in prompt_map:
        return prompt_map[stem]
    normalized_stem = re.sub(r"[\s_\-]+", "", stem)
    for key, value in prompt_map.items():
        normalized_key = re.sub(r"[\s_\-]+", "", key)
        if normalized_key and (normalized_key == normalized_stem or normalized_key in normalized_stem or normalized_stem in normalized_key):
            return value
    return ""


def _manual_postprocess_fallback_prompt(image_path: str, role: str) -> str:
    """没有提示词文件时，用文件名提供最小角色锚点，不伪造标题。"""
    name = os.path.splitext(os.path.basename(str(image_path or "")))[0]
    if role == "tweet_cover_27_36":
        return f"tweet cover raw background only, no public text, file name: {name}"
    if role == "cover_27_48":
        return f"cover page raw background only, no public text, file name: {name}"
    if role == "home_page_27_48":
        return f"home page raw background only, no public text, file name: {name}"
    if role == "brand_end_page_27_48":
        return f"brand end page raw background only, no public text, file name: {name}"
    return f"content diagram raw image, no public brand text, file name: {name}"


def iter_postprocess_image_files(folder_path: str, recursive: bool = False) -> list[str]:
    """列出待后处理图片；自动跳过 _raw、隐藏文件和系统缩略图。"""
    folder = os.path.abspath(folder_path or "")
    if not folder or not os.path.isdir(folder):
        return []
    files = []
    if recursive:
        walker = os.walk(folder)
    else:
        try:
            walker = [(folder, [], os.listdir(folder))]
        except Exception:
            walker = []
    for root, _dirs, names in walker:
        parts = set(os.path.normpath(root).split(os.sep))
        if "_raw" in parts:
            continue
        for name in names:
            if not name or name.startswith(".") or name.lower() in {"thumbs.db", "desktop.ini"}:
                continue
            ext = os.path.splitext(name)[1].lower()
            if ext in SUPPORTED_POSTPROCESS_IMAGE_EXTS:
                files.append(os.path.join(root, name))
    return sorted(files, key=lambda p: os.path.basename(p).lower())


def postprocess_image_folder(folder_path: str, *, role: str = "auto", prompt_file: str = "", recursive: bool = False, logger=None) -> dict:
    """从文件夹中提取图片并统一后处理。用于手动生成视频图片后的批量盖章。"""
    folder = os.path.abspath(folder_path or "")
    result = {"folder": folder, "total": 0, "ok": 0, "failed": 0, "skipped": 0, "prompt_file": "", "items": []}
    if not folder or not os.path.isdir(folder):
        if logger:

            logger(f"❌ 后处理文件夹不存在：{folder_path}")
        return result

    prompt_file = prompt_file or find_nearby_prompt_file_for_folder(folder)
    result["prompt_file"] = prompt_file or ""
    prompt_map = _load_prompt_map_from_file(prompt_file, logger=logger) if prompt_file else {}
    images = iter_postprocess_image_files(folder, recursive=recursive)
    result["total"] = len(images)
    if logger:
        logger(f"🖼️ 文件夹后处理开始：{folder}；图片 {len(images)} 张；模式={normalize_postprocess_role(role)}")
    write_manual_image_naming_rules(folder, logger=logger)
    if not images:
        return result


    for image_path in images:
        prompt = _prompt_for_image(image_path, prompt_map)
        detected_role = infer_visual_role_from_image_name(image_path, prompt=prompt, forced_role=role)
        effective_prompt = prompt or _manual_postprocess_fallback_prompt(image_path, detected_role)
        try:
            ok = postprocess_generated_image(image_path, effective_prompt, logger=logger, prompt_name=os.path.basename(image_path))
            item = {"path": image_path, "role": detected_role, "ok": bool(ok)}
            result["items"].append(item)
            if ok:
                result["ok"] += 1
            else:
                result["failed"] += 1
                if logger:
                    logger(f"⚠️ 后处理未完成：{os.path.basename(image_path)}；识别页型={detected_role}")
        except Exception as e:
            result["failed"] += 1
            result["items"].append({"path": image_path, "role": detected_role, "ok": False, "error": str(e)[:160]})
            if logger:
                logger(f"❌ 后处理失败：{os.path.basename(image_path)}；{str(e)[:160]}")
    if logger:
        logger(f"✅ 文件夹后处理完成：成功 {result['ok']} 张，失败 {result['failed']} 张，raw 备份位于各文件夹 _raw/。")
    return result

def detect_visual_role(prompt_name: str = "", prompt: str = "") -> str:
    """根据分镜名称和提示词内容识别视觉页类型，用于追加精确规格。"""
    name = decode_hash_u_escapes_text(str(prompt_name or ""))
    body = decode_hash_u_escapes_text(str(prompt or ""))
    combined = f"{name}\n{body}".lower()
    if "daily_research_square_visual_summary" in combined or "daily research square visual summary" in combined:
        return "daily_research_square_visual_summary"

    # 先相信文件名/分镜名；A/C 全章摘要里会出现 A1/A2/A01/A02 字样，
    # 如果用 combined 先匹配，会把 C_品牌页误判成 A 系列。
    if re.search(r"(?:^|[^a-z])c(?:[^a-z]|$)|(brand|ending|end[_\- ]?page|final[_\- ]?page|尾页|品牌页|结束页|关注页)", name, flags=re.I):
        return "brand_end_page_27_48"
    if re.search(r"(?:^|[^a-z])a01(?:[^a-z]|$)|bilibili[_\- ]?cover|b站封面|哔哩哔哩封面", name, flags=re.I):
        return "bilibili_cover_4_3"
    if re.search(r"(?:^|[^a-z])a02(?:[^a-z]|$)|bilibili[_\- ]?home|b站首页|哔哩哔哩首页", name, flags=re.I):
        return "bilibili_home_16_9"
    if re.search(r"(?:^|[^a-z])a2(?:[^a-z]|$)|home\s*page|首页", name, flags=re.I):
        return "home_page_27_48"
    if re.search(r"(?:^|[^a-z])a1(?:[^a-z]|$)|master|封面页|cover", name, flags=re.I):
        return "tweet_cover_27_36"

    # 固定平台图：A1 为 3:4，A2 为 9:16，A01 为 4:3，A02 为 16:9。
    if re.search(r"(?:^|[^a-z])a01(?:[^a-z]|$)|bilibili[_\- ]?cover|b站封面|哔哩哔哩封面", combined, flags=re.I):
        return "bilibili_cover_4_3"
    if re.search(r"(?:^|[^a-z])a02(?:[^a-z]|$)|bilibili[_\- ]?home|b站首页|哔哩哔哩首页", combined, flags=re.I):
        return "bilibili_home_16_9"
    if (re.search(r"推文图\s*[_\- ]?0?1", name, flags=re.IGNORECASE)
            or re.search(r"推文图\s*[_\- ]?0?1", body, flags=re.IGNORECASE)
            or "27:36" in combined
            or re.search(r"tweet[_\- ]?cover|wechat[_\- ]?cover", combined)):
        return "tweet_cover_27_36"
    if re.search(r"(?:^|[^a-z])a2(?:[^a-z]|$)|home\s*page|首页", combined, flags=re.I):
        return "home_page_27_48"
    if re.search(r"(?:^|[^a-z])a1(?:[^a-z]|$)|封面页|cover", combined, flags=re.I):
        return "tweet_cover_27_36"
    # v97：手动命名时优先按文件名识别品牌尾页，避免被“content/medical illustration”等词误判成内容页。
    if (re.search(r"(brand|ending|end[_\- ]?page|final[_\- ]?page|尾页|品牌页|结束页|关注页)", name, flags=re.I)
            or re.search(r"(brand\s*(?:end|page)|ending\s*brand|end[_\- ]?page|final[_\- ]?page|尾页|品牌页|结束页|关注页)", body, flags=re.I)):
        return "brand_end_page_27_48"
    # 内容页硬约束里可能出现 cover/brand 负面词，因此内容页标记放在封面之前，但品牌尾页已在上面优先识别。
    if ("content page software logo lock" in combined
            or "middle content image" in combined
            or "middle content illustration" in combined
            or "content illustration" in combined
            or "content diagram" in combined):
        return "content_diagram_27_48"
    if ("镜头_02" in name or "镜头 2" in name
            or re.search(r"(home\s*page|首页|shot[_\- ]?0?2|a2)", combined, flags=re.I)):
        return "home_page_27_48"
    if ("镜头_01" in name or "镜头 1" in name
            or re.search(r"(cover|title[_\- ]?page|chapter[_\- ]?cover|封面|片头|shot[_\- ]?0?1)", combined, flags=re.I)):
        return "tweet_cover_27_36"
    return "content_diagram_27_48"


def parse_image_size(size: str, default_w: int, default_h: int) -> tuple[int, int]:
    """解析 1024x1824 这类尺寸字符串；解析失败时回退到默认尺寸。"""
    m = re.match(r"^\s*(\d{2,5})\s*x\s*(\d{2,5})\s*$", str(size or ""), flags=re.I)
    if not m:
        return int(default_w), int(default_h)
    return int(m.group(1)), int(m.group(2))


def _parse_exact_ratio_size_from_env(env_name: str, default_size: str, fallback_w: int, fallback_h: int, *, ratio_w: int, ratio_h: int) -> tuple[str, int, int]:
    """读取尺寸并强制校正为精确比例，避免后处理输出出现 1024x1824 这类非严格 9:16。"""
    raw_size = os.environ.get(env_name, default_size)
    w, h = parse_image_size(raw_size, fallback_w, fallback_h)
    if w <= 0 or h <= 0 or w * ratio_h != h * ratio_w:
        # 以宽度为主校正；若不能整除则使用默认精确规格。
        corrected_h = int(round(w * ratio_h / ratio_w))
        if corrected_h > 0 and w * ratio_h == corrected_h * ratio_w:
            h = corrected_h
        else:
            w, h = fallback_w, fallback_h
    return f"{int(w)}x{int(h)}", int(w), int(h)


def visual_role_canvas(role: str):
    """返回角色对应的目标画幅和主画布尺寸；A1/A2/A01/A02 后处理输出固定为精确比例。"""
    role = normalize_postprocess_role(role) if role else "content_diagram_27_48"
    if role in {"tweet_cover_27_36", "cover_27_48"}:
        # A1：微信封面，固定 3:4。cover_27_48 仅作为旧别名兼容，不再输出 4:3。
        default_size = "768x1024" if TOKEN_SAVER_MODE else "1440x1920"
        return ("3:4",) + _parse_exact_ratio_size_from_env("OPENAI_IMAGE_SIZE_A1_3_4", os.environ.get("OPENAI_IMAGE_SIZE_3_4", default_size), 768 if TOKEN_SAVER_MODE else 1440, 1024 if TOKEN_SAVER_MODE else 1920, ratio_w=3, ratio_h=4)
    if role == "home_page_27_48":
        # A2：微信首页，固定 9:16。
        default_size = "1080x1920" if TOKEN_SAVER_MODE else "2160x3840"
        return ("9:16",) + _parse_exact_ratio_size_from_env("OPENAI_IMAGE_SIZE_A2_9_16", os.environ.get("OPENAI_IMAGE_SIZE_9_16", default_size), 1080 if TOKEN_SAVER_MODE else 2160, 1920 if TOKEN_SAVER_MODE else 3840, ratio_w=9, ratio_h=16)
    if role == "bilibili_cover_4_3":
        # A01：B站封面，固定 4:3。
        default_size = POSTPROCESS_STABLE_SPEC["cover_page"].get("recommended_size_token_saver", "1024x768") if TOKEN_SAVER_MODE else POSTPROCESS_STABLE_SPEC["cover_page"].get("recommended_size_high", "1920x1440")
        return ("4:3",) + _parse_exact_ratio_size_from_env("OPENAI_IMAGE_SIZE_A01_4_3", os.environ.get("OPENAI_IMAGE_SIZE_4_3", default_size), 1024 if TOKEN_SAVER_MODE else 1920, 768 if TOKEN_SAVER_MODE else 1440, ratio_w=4, ratio_h=3)
    if role == "bilibili_home_16_9":
        # A02：B站首页，固定 16:9。
        default_size = POSTPROCESS_STABLE_SPEC.get("bilibili_home_page", {}).get("recommended_size_token_saver", "1024x576") if TOKEN_SAVER_MODE else POSTPROCESS_STABLE_SPEC.get("bilibili_home_page", {}).get("recommended_size_high", "1920x1080")
        return ("16:9",) + _parse_exact_ratio_size_from_env("OPENAI_IMAGE_SIZE_A02_16_9", os.environ.get("OPENAI_IMAGE_SIZE_16_9", default_size), 1024 if TOKEN_SAVER_MODE else 1920, 576 if TOKEN_SAVER_MODE else 1080, ratio_w=16, ratio_h=9)
    if role == "brand_end_page_27_48":
        default_size = POSTPROCESS_STABLE_SPEC["ending_page"]["recommended_size_token_saver"] if TOKEN_SAVER_MODE else POSTPROCESS_STABLE_SPEC["ending_page"]["recommended_size_high"]
        return ("9:16",) + _parse_exact_ratio_size_from_env("OPENAI_IMAGE_SIZE_ENDING_9_16", default_size, 1080 if TOKEN_SAVER_MODE else 1440, 1920 if TOKEN_SAVER_MODE else 2560, ratio_w=9, ratio_h=16)
    default_size = "1080x1920" if TOKEN_SAVER_MODE else "2160x3840"
    return ("9:16",) + _parse_exact_ratio_size_from_env("OPENAI_IMAGE_SIZE_27_48", default_size, 1080 if TOKEN_SAVER_MODE else 2160, 1920 if TOKEN_SAVER_MODE else 3840, ratio_w=9, ratio_h=16)




GPT_IMAGE2_LOW_COST_SIZES = {
    "3:4": ("720x960", 720, 960),
    "9:16": ("720x1280", 720, 1280),
    "4:3": ("960x720", 960, 720),
    "16:9": ("1280x720", 1280, 720),
}


def _openai_api_safe_canvas_for_role(role: str):
    """Return the low-token GPT Image 2 request size for each role.

    Final exported platform images are still controlled by visual_role_canvas() and post-processing.
    This function only chooses the raw Image API request size. The defaults match the low-cost
    exact-ratio sizes requested for GPT Image 2: A1=720x960, B/C/A2=720x1280,
    A01=960x720, A02=1280x720. All edges are multiples of 16 and all pixel counts are above
    the 655,360 minimum.
    """
    role = normalize_postprocess_role(role)
    if role in {"tweet_cover_27_36", "cover_27_48"}:
        size, w, h = GPT_IMAGE2_LOW_COST_SIZES["3:4"]
        return ("3:4-api-lowcost", size, w, h)
    if role in {"home_page_27_48", "brand_end_page_27_48", "content_diagram_27_48"}:
        size, w, h = GPT_IMAGE2_LOW_COST_SIZES["9:16"]
        return ("9:16-api-lowcost", size, w, h)
    if role == "bilibili_cover_4_3":
        size, w, h = GPT_IMAGE2_LOW_COST_SIZES["4:3"]
        return ("4:3-api-lowcost", size, w, h)
    if role == "bilibili_home_16_9":
        size, w, h = GPT_IMAGE2_LOW_COST_SIZES["16:9"]
        return ("16:9-api-lowcost", size, w, h)
    if role == "daily_research_square_visual_summary":
        return ("1:1-api", "1024x1024", 1024, 1024)
    size, w, h = GPT_IMAGE2_LOW_COST_SIZES["9:16"]
    return ("9:16-api-lowcost", size, w, h)


def coerce_openai_image_request_size(role: str, requested_size: str, fallback_w: int, fallback_h: int):
    """Coerce a requested size to a safe OpenAI Images API size if needed.

    Always returns exactly four values: (ratio_label, size_string, width, height).
    The previous v5 build returned three values for already-valid sizes, which caused
    "not enough values to unpack (expected 4, got 3)" in the OpenAI image client.
    """
    w, h = parse_image_size(requested_size, fallback_w, fallback_h)
    if w > 0 and h > 0 and w % 16 == 0 and h % 16 == 0:
        if w == h:
            ratio = "1:1-api"
        elif w * 16 == h * 9:
            ratio = "9:16-api"
        elif w * 9 == h * 16:
            ratio = "16:9-api"
        elif w * 4 == h * 3:
            ratio = "3:4-api"
        elif w * 3 == h * 4:
            ratio = "4:3-api"
        else:
            ratio = "custom-api"
        return ratio, requested_size, w, h
    return _openai_api_safe_canvas_for_role(role)


def visual_generation_canvas(role: str):
    """图像 API 的实际生成画幅。A1/A2/A01/A02 只生成一次 1:1 Master Background，随后按平台比例裁切。

    注意：OpenAI Images API 要求 width/height 都能被 16 整除；因此这里返回“API 安全尺寸”，
    而最终输出规格仍由 visual_role_canvas() 和后处理裁切决定。
    """
    role = normalize_postprocess_role(role)
    if role in {"tweet_cover_27_36", "cover_27_48", "home_page_27_48", "bilibili_cover_4_3", "bilibili_home_16_9"}:
        # Only A1 should actually call the image model. A2/A01/A02 are derived crops.
        # Default request is the low-token 3:4 A1 master (720x960), not a square 1024x1024 image.
        size = os.environ.get("OPENAI_IMAGE_SIZE_A_MASTER", os.environ.get("OPENAI_IMAGE_SIZE_A1_3_4", "720x960"))
        _api_ratio, size, w, h = coerce_openai_image_request_size("tweet_cover_27_36", size, 720, 960)
        return "3:4-master-lowcost", size, w, h
    return _openai_api_safe_canvas_for_role(role if role != "auto" else "content_diagram_27_48")

def detect_visual_canvas_from_prompt(prompt: str):
    exact = re.search(
        r"(?:request\s+image\s+canvas\s+exactly|canvas\s+requirement.*?exactly|exactly)\s*(\d{3,5})\s*x\s*(\d{3,5})",
        str(prompt or ""),
        flags=re.I | re.S,
    )
    if exact:
        w = int(exact.group(1))
        h = int(exact.group(2))
        size = f"{w}x{h}"
        role = detect_visual_role("", prompt)
        return coerce_openai_image_request_size(role, size, w, h)
    role = detect_visual_role("", prompt)
    return visual_generation_canvas(role)


def _active_visual_style_profile(style_key: str | None = None) -> dict:
    return {
        "name": "science",
        "raw_aesthetic": "explanation-first biomedical illustration style with slight 3D depth, clean scientific composition, clear anatomy and structure relationships, crisp contour linework, soft dimensional shading, light neutral or white background with optional subtle supportive biomedical background, restrained but vivid accent colors, matte surfaces, callout-friendly layout, medically plausible mechanism visualization, non-sci-fi",
        "content_subject": "B page no-text medical / biomedical explanatory base image only. Depict the source-supported medical subject, structure, evidence, process, experiment, causal mechanism, comparison, sequence, hierarchy or model as a clear explanatory biomedical figure, cutaway, cross-section, exploded view, comparison panel, or step-by-step mechanism figure with slight depth and vivid but disciplined presentation; the final page may receive a software-rendered short English keyword caption and optional vector annotations.",
        "negative": "No visible text, no letters, no numbers, no labels, no captions, no logo, no watermark, no pseudo-text. No sci-fi HUD, cyberpunk lighting, neon networks, holographic anatomy, futuristic dashboard, cinematic 3D, fantasy anatomy, metallic/mecha parts, space/cosmic particles, decorative technology interface, glossy CGI translucency, lens flare, volumetric glow, or poster-style spectacle.",
    }


def build_role_specific_visual_lock(role: str) -> str:
    """科学经典单风格：图像模型只出无字基础图，文字/标签/箭头留给后处理。"""
    profile = _active_visual_style_profile()
    raw_aesthetic = profile["raw_aesthetic"]
    negative = profile["negative"]
    if role in {"tweet_cover_27_36", "cover_27_48", "home_page_27_48", "bilibili_cover_4_3", "bilibili_home_16_9"}:
        return (
            "A1/A2/A01/A02 shared full-chapter-summary Master Background only. A1 is the only real image-generation prompt; A2, A01 and A02 must be software crops from that same one master image. Final crops: A1=3:4, A2=9:16, A01=4:3, A02=16:9. "
            "Design the master as a square-safe no-text medical / biomedical chapter key visual: the core subject and chapter-level relationship stay in the central 60% area, while all four edges are low-information extendable background for vertical and horizontal crops. Prefer a summary figure, cross-section collage, comparison layout, or mechanism map on a pale light background, with slight dimensional depth. Do not create a generic wallpaper, sci-fi scene, neon brain, flashy CGI close-up, or typography placeholder. The full-canvas mask and all text are added by software. "
            f"Use {raw_aesthetic}. {negative}"
        )
    if role == "brand_end_page_27_48":
        return (
            "C ending / brand page raw full-chapter-summary background only for the science classic-reading mode. It must be generated from this chapter's whole-summary theme: core scientific question, key biological objects, mechanism/evidence chain, conclusion boundary and next-question relation. Create a calm no-text biomedical closing key visual with a clean explanatory summary-figure feeling; never use generic brand atmosphere, soft particles, abstract brain wallpaper or unrelated chapter content. Use a pale, low-contrast, airy background so deterministic brand typography remains readable; no CTA. "
            f"Use {raw_aesthetic}. Leave center area clean for deterministic brand and slogan text only. {negative}"
        )
    return (
        f"{profile['content_subject']} Use {raw_aesthetic}. "
        "Do not make a generic wallpaper or sci-fi concept art. The visible scientific/medical structure must show the narration's concept relationship clearly. Prefer diagram-first composition, clear separation of components, and callout-friendly space. Do not draw safety bands, guide/reference lines, logos, watermarks, UI frames, fixed typography, labels, arrows, captions or legends; these are added only by software post-processing when needed. "
        f"{negative}"
    )


def build_compact_global_image_rules() -> str:
    profile = _active_visual_style_profile()
    return (
        "The image generator must produce a no-text raw base image only. "
        "All typography, short English keyword captions, labels, arrows, logos, coordinates, safety-zone masks, reference lines, book/chapter information, slogans, follow text, brand text, CTA and QR must be added later through deterministic post-processing. "
        "Do not render any visible text, letters, numbers, labels, captions, legends, pseudo-text, logo, watermark, book title, chapter title, brand, CTA, or QR in the generated image. "
        "A1/A2/A01/A02 share one no-text full-chapter-summary Master Background generated once from the whole chapter summary, not from generic science decoration; only A1 is a real image-generation prompt, and software crops the same master image to A1 3:4, A2 9:16, A01 4:3 and A02 16:9. C brand page must also use a chapter-summary background, not a generic end-card atmosphere. "
        f"Use this active visual style: {profile['raw_aesthetic']}. Keep the design restrained, readable and non-generic."
    )


COMPACT_GLOBAL_IMAGE_RULES = build_compact_global_image_rules()

CONTENT_PAGE_BRAND_REPEAT_BLOCK = "Content pages: no text, no labels, no arrows with text, no captions, no legends, no public brand/logo/title in raw image. Fixed top-left logo and any labels/arrows are overlaid by software/vector post-processing. Do not draw safety bands or guide/reference lines; top/bottom safety treatment is added only by software post-processing."


def sanitize_content_prompt_brand_text(prompt: str) -> str:
    """内容图提示词禁止出现品牌字样，避免图像模型自己生成第二个 Logo。"""
    p = str(prompt or "")
    # 删除包含品牌字样的整句/从句；品牌由程序后处理统一叠加。
    p = re.sub(r"[^。.!?;；\n]*QuanLan\s*BrainScience\s*®?[^。.!?;；\n]*[。.!?;；]?", " ", p, flags=re.IGNORECASE)
    p = re.sub(r"[^。.!?;；\n]*(?:watermark|brand mark|brand logo|logo-like text|pseudo-watermark|channel name)[^。.!?;；\n]*[。.!?;；]?", " ", p, flags=re.IGNORECASE)
    p = re.sub(r"do not render[^。.!?;；\n]*", " ", p, flags=re.IGNORECASE)
    p = re.sub(r"software will overlay[^。.!?;；\n]*", " ", p, flags=re.IGNORECASE)
    p = re.sub(r"software-stamped[^。.!?;；\n]*", " ", p, flags=re.IGNORECASE)
    p = re.sub(r"\s+", " ", p).strip()
    return p


def sanitize_content_prompt_text_policy(prompt: str) -> str:
    """内容图主体提示词去掉与中间内容页无关的公共文字元素，避免书名、章节、作者等泄露到内容图里。"""
    p = str(prompt or "")
    forbidden_patterns = [
        r"[^。.!?;；\n]*(?:book\s*title|chapter\s*(?:title|number|info(?:rmation)?)|author\s*line|author(?:s)?|version\s*line|edition|subtitle|page\s*title|section\s*title|follow\s*prompt|cover\s*title|brand\s*page|opening\s*page)[^。.!?;；\n]*[。.!?;；]?",
        r"[^。.!?;；\n]*(?:书名|章节信息|章节标题|章节序号|作者|版本|副标题|页标题|封面|首页|品牌页)[^。.!?;；\n]*[。.!?;；]?",
    ]
    for pat in forbidden_patterns:
        p = re.sub(pat, " ", p, flags=re.IGNORECASE)
    p = re.sub(r"\b(?:title|subtitle|caption|legend)\s*:\s*", " ", p, flags=re.IGNORECASE)
    p = re.sub(r"\s+", " ", p).strip()
    return p


def _strip_existing_public_locks(prompt: str) -> str:
    """删除旧版本重复公共规格块，避免同一提示词越跑越长。"""
    p = str(prompt or "").replace("\r\n", "\n").replace("\r", "\n")
    markers = [
        "GLOBAL NON-NEGOTIABLE IMAGE RULES:",
        "PUBLIC ELEMENT SINGLE SOURCE OF TRUTH:",
        "PAGE TYPE LOCK:",
        "PUBLIC BRAND LOCK:",
        "Fixed public palette:",
    ]
    for marker in markers:
        pos = p.find(marker)
        if pos >= 0:
            p = p[:pos].strip()
    return re.sub(r"\s+", " ", p).strip()



def strip_public_elements_for_raw_generation(prompt: str, role: str = "") -> str:
    """移除会导致模型生成公共元素的片段，但保留该图自己的主体画面描述。"""
    p = str(prompt or "").replace("\r\n", "\n").replace("\r", "\n")
    kept = []
    for line in p.splitlines():
        t = line.strip()
        if not t:
            continue
        if role in {"tweet_cover_27_36", "cover_27_48", "brand_end_page_27_48"}:
            # 不整行丢弃，避免“标题/Logo + 主体构图”写在同一行时把主体也删掉。
            t = re.sub(r"(?:QuanLan\s*BrainScience\s*®?|全澜脑科学®?)", " ", t, flags=re.I)
            t = re.sub(r"(?:logo|watermark|brand|book\s*title|chapter\s*title|chapter\s*number|author\s*line|slogan|follow|CTA|QR|关注|公众号|书名|章节标题|章节序号|作者|标题|副标题)\s*[：:=]?\s*[\"“]?[^。.!?;；\n\"”]{0,160}[\"”]?[。.!?;；]?", " ", t, flags=re.I)
            t = re.sub(r'(?:text|visible\s+text|render\s+text)\s*[：:=]?\s*["“][^"”]{1,160}["”]', " ", t, flags=re.I)
        else:
            t = sanitize_content_prompt_text_policy(sanitize_content_prompt_brand_text(t))
        t = re.sub(r"\s+", " ", t).strip(" ,，.;；。")
        if t:
            kept.append(t)
    p = " ".join(kept)
    p = re.sub(r"\s+", " ", p).strip()
    if not p:
        if role in {"tweet_cover_27_36", "cover_27_48"}:
            p = "No-text active-style background with one concrete source-supported chapter motif."
        elif role == "brand_end_page_27_48":
            p = "No-text chapter-related scientific ending background with one concrete biomedical motif connected to the chapter theme."
        else:
            p = "No-text active-style content illustration with one concrete source-supported concept and an explicit visual relationship."
    return p




def _compact_generation_prompt_text(prompt: str, max_chars: int | None = None) -> str:
    """清洗绘图 API 主体提示词：只删公共噪声和重复句，不再按字符数截断。"""
    raw = str(prompt or "").replace("\r\n", "\n").replace("\r", "\n")
    raw = _strip_existing_public_locks(raw)
    # 删除最耗 token 且由程序/接口控制的尺寸、坐标、字体、色值长规格；不整段截断，避免丢掉主体画面。
    raw = re.sub(r"\bcanvas\s*size\s*[:=]?\s*\d{3,5}\s*x\s*\d{3,5}[.;；。]?", " ", raw, flags=re.I)
    raw = re.sub(r"\bfont\s*size\s*[:=]?\s*\d{1,4}\s*px?[.;；。]?", " ", raw, flags=re.I)
    raw = re.sub(r"\b(?:canvas|size|resolution|aspect ratio|ratio|dpi|font|fontsize|center_[xy]|x|y|width|height)\s*[:=][^.;；。\n]+[.;；。]?", " ", raw, flags=re.I)
    raw = re.sub(r"#[0-9A-Fa-f]{6}", " ", raw)
    raw = re.sub(r"\b\d{3,5}\s*x\s*\d{3,5}\b", " ", raw, flags=re.I)
    raw = re.sub(r"\b\d{2,4}\s*px\b", " ", raw, flags=re.I)
    raw = re.sub(r"\bNo\s*(?=[.;；。]|$)", " ", raw, flags=re.I)
    # 合并重复句；对公共禁令只保留后面的短协议，不在主体里重复。
    public_noise = re.compile(r"(no\s+(?:visible\s+)?(?:logo|watermark|brand|title|cta|qr)|do not render|software[- ]stamped|public elements|公共元素|后处理|水印|品牌|标题)", re.I)
    parts = re.split(r"(?<=[。.!?；;])\s+|\n+", raw)
    seen, kept = set(), []
    for part in parts:
        text = part.strip(" \t\n,，")
        if not text:
            continue
        if public_noise.search(text):
            continue
        key = re.sub(r"\s+", " ", text).lower()
        if key in seen:
            continue
        seen.add(key)
        kept.append(text)
    text = " ".join(kept).strip()
    return re.sub(r"\s+", " ", text).strip()



SCI_FI_STYLE_NEGATIVE_RE = re.compile(
    r"\b(?:sci[-\s]?fi|science fiction|cyberpunk|futuristic|future tech|neon|HUD|hologram|holographic|data stream|digital dashboard|cinematic 3D|metallic|mecha|spaceship|space age)\b|"
    r"(?:科幻|赛博朋克|霓虹|全息|高科技界面|数据流|金属机甲|太空感)",
    flags=re.I,
)


def sanitize_cell_style_subject_text(prompt: str) -> str:
    """把单张图主体描述中的科幻/霓虹/HUD/文字标签倾向清掉，统一回 严谨医学插画风格。"""
    p = str(prompt or "")
    p = SCI_FI_STYLE_NEGATIVE_RE.sub(" ", p)
    p = re.sub(r"\b(?:with|including|add|show)\s+(?:visible\s+)?(?:text|letters|numbers|labels|captions|legends|logos?)\b", " ", p, flags=re.I)
    p = re.sub(r"(?:带有|加入|显示|包含)(?:文字|字母|数字|标签|图例|标题|logo|标志)", " ", p, flags=re.I)
    p = re.sub(r"\s+", " ", p).strip(" ,，.;；。")
    return p

def _hard_cap_visual_prompt_text(prompt: str, max_chars: int | None = None, *, tail: str = "") -> str:
    """v8.2：不再硬截断绘图提示词。

    旧版会按 IMAGE_API_HARD_MAX_CHARS 截断，并可能把英文短语截成
    `restrained ac...` 这类半截提示词。新版只做空白规范化和尾部规则追加，
    不切词、不切句、不切段。若用户确实需要压缩，应在上游重写提示词，
    不能在这里机械截断。
    """
    text = re.sub(r"\s+", " ", str(prompt or "")).strip()
    if not text:
        return ""
    tail = re.sub(r"\s+", " ", str(tail or "")).strip()
    if tail and tail not in text:
        text = (text.rstrip(" ,，.;；。") + " " + tail).strip()
    return text



def _build_concise_b_teaching_api_prompt(voice: str, original_prompt: str = "") -> str:
    """B 系列最终发给图像 API 的短硬提示词：台词相关 + 关键词示意，禁止大段说明文字。"""
    summary = _summarize_voiceover_for_visual_lock(voice, limit=180)
    strict_target = _strict_b_visual_target_from_voiceover(voice) if '_strict_b_visual_target_from_voiceover' in globals() else ""
    anchors = _voiceover_visual_keywords(voice) if '_voiceover_visual_keywords' in globals() else ""
    logic = _voiceover_logic_relation_brief(voice) if '_voiceover_logic_relation_brief' in globals() else ""

    logic_lower = str(logic or "").lower()
    layout_hint = "single clean teaching scene"
    if "comparison" in logic_lower or "contrast" in logic_lower:
        layout_hint = "very simple side-by-side comparison"
    elif "sequence" in logic_lower or "process" in logic_lower or "stepwise" in logic_lower or "temporal" in logic_lower:
        layout_hint = "simple visual flow, max 2-3 visual states, no numbered text"
    elif "evidence-to-claim" in logic_lower or "observation" in logic_lower or "experimental" in logic_lower:
        layout_hint = "single evidence scene with one small readout motif"
    elif "input-output" in logic_lower or "feedback" in logic_lower or "pathway" in logic_lower or "mechanistic linkage" in logic_lower or "cause-to-effect" in logic_lower:
        layout_hint = "single causal mechanism scene with arrows"
    elif "hierarchy" in logic_lower or "zoom" in logic_lower:
        layout_hint = "simple macro-to-micro zoom, max one inset"

    short_anchor = ""
    if anchors:
        parts = [x.strip() for x in str(anchors).split(';') if x.strip()]
        kept = []
        for part in parts:
            if strict_target and part == strict_target:
                continue
            kept.append(part)
            if len(kept) >= 1:
                break
        short_anchor = "; ".join(kept)

    lines = [
        "B-SERIES VOICEOVER-MATCHED KEYWORD DIAGRAM.",
        f"Paired voiceover meaning: {summary}.",
        f"Visual target: {strict_target or summary}.",
        f"Layout: {layout_hint}; one main visual focus only.",
        "Show the relationship mainly through biomedical objects, arrows, spatial arrangement, and color contrast; do not write mechanism explanations inside the image.",
        "Visible text policy: keep labels minimal. If labels help scientific clarity, use only 2-4 English keyword labels/callouts total, each 1-2 words. Keywords only, no sentences.",
        "Forbidden visible text: title, header, footer, paragraph, caption, explanation box, numbered steps, bullet list, table, dense labels, Chinese text, pseudo-text, logo, watermark.",
        "Accuracy: every visible object must be supported by the paired voiceover; remove neighboring-shot details and decorative filler.",
        "Style: clean professional biomedical textbook illustration, crisp contour linework, light neutral background, restrained academic colors, slight dimensional depth, not a poster, not an infographic board, not cinematic CGI.",
    ]
    if short_anchor:
        lines.append(f"Optional supported anchor: {short_anchor}.")
    out = re.sub(r"\s+", " ", " ".join(lines)).strip()
    tail = "Final B rules: match the paired voiceover; one clean teaching figure; keyword labels only when helpful: 2-4 English labels, 1-2 words each. No title, paragraph, caption, explanation box, table, numbered steps, Chinese text, pseudo-text, logo, watermark."
    return _hard_cap_visual_prompt_text(out, max_chars=None, tail=tail)

def enforce_canonical_visual_spec(prompt: str, prompt_name: str = "") -> str:
    """绘图前统一改成 raw 图提示词：优先用配对台词重建主体，避免图文不一致。"""
    raw0 = _strip_existing_public_locks(prompt)
    role = detect_visual_role(prompt_name, raw0)
    if role == "daily_research_square_visual_summary":
        square_tail = (
            "Daily research square visual summary contract: compose the complete scientific mechanism directly inside one 1:1 square canvas. "
            "Do not create a tall mobile poster, vertical full-body animal anatomy poster, page screenshot, infographic board, or layout that depends on cropping. "
            "All essential structures, arrows, insets, and mechanism stages must fit inside the square with balanced margins. "
            "No visible text, letters, numbers, captions, logo, watermark, pseudo-text, UI, title, header, footer, or paragraph. "
            "Use a Cell-style biomedical visual abstract aesthetic with clear mechanism-first composition."
        )
        return _hard_cap_visual_prompt_text(raw0, max_chars=None, tail=square_tail)
    page_type = infer_alignment_page_type(prompt_name, raw0)
    # A/C 提示词会包含全章摘要，其中可能出现 A1/A2/A01/A02 字样；
    # 页型必须优先相信文件名/角色，避免 C 品牌页被误判成 A 系列封面。
    if role == "brand_end_page_27_48":
        page_type = "C. Brand Page"
    elif role in {"tweet_cover_27_36", "cover_27_48", "home_page_27_48", "bilibili_cover_4_3", "bilibili_home_16_9"}:
        page_type = "A1/A2/A01/A02 Shared Master/Crop Page"
    paired_voice = _extract_paired_voiceover_from_prompt(raw0)
    global_theme = _extract_global_script_theme_from_prompt(raw0)
    theme_voice = global_theme if role in {"tweet_cover_27_36", "cover_27_48", "home_page_27_48", "bilibili_cover_4_3", "bilibili_home_16_9", "brand_end_page_27_48"} and global_theme else paired_voice

    if theme_voice:
        if role == "content_diagram_27_48" and paired_voice:
            # v6.5: B 系列用短硬教学提示词，避免长提示词被预算截断后准确性约束丢失。
            return _build_concise_b_teaching_api_prompt(paired_voice, original_prompt=raw0)
        body = _build_voiceover_grounded_visual_brief(theme_voice, page_type=page_type, original_prompt=raw0)
    elif role in {"tweet_cover_27_36", "cover_27_48", "home_page_27_48", "bilibili_cover_4_3", "bilibili_home_16_9"}:
        body = strip_public_elements_for_raw_generation(raw0, role=role)
        body = _compact_generation_prompt_text(body, max_chars=IMAGE_BODY_PROMPT_BUDGET_CHARS)
        if not body:
            body = "Create one shared no-text A1/A2 explanatory biomedical key visual with slight dimensional depth and a chapter-relevant concrete biology motif, pale high-key light neutral background, restrained blue-white palette, low visual density, soft low-contrast supportive background, non-sci-fi; prefer a summary-figure feeling, not generic wallpaper or title placeholder. The overall background should stay lighter and calmer so later typography remains easy to read."
    elif role == "brand_end_page_27_48":
        body = strip_public_elements_for_raw_generation(raw0, role=role)
        body = _compact_generation_prompt_text(body, max_chars=IMAGE_BODY_PROMPT_BUDGET_CHARS)
        if not body:
            body = "Create a no-text ending/brand page explanatory biomedical key visual with slight dimensional depth related to the chapter topic, pale high-key light neutral background, restrained blue-white palette, low visual density, soft low-contrast supportive background, non-sci-fi; no generic end-card wallpaper or text placeholder. The overall background should stay lighter and calmer so later typography remains easy to read."
    else:
        body = strip_public_elements_for_raw_generation(raw0, role=role)
        body = _compact_generation_prompt_text(body, max_chars=IMAGE_BODY_PROMPT_BUDGET_CHARS)
        if not body:
            body = "No-text neuroscience biomedical mechanism base illustration relevant to this chapter, explanation-first biomedical illustration aesthetic with slight dimensional depth, restrained blue-white academic palette, light neutral background, optional subtle supportive background, non-sci-fi."

    # v140 hard reset: keep the semantic visual brief FIRST. 旧版把长通用规则放在前面，
    # 触发预算截断后只剩泛化背景，具体台词和逻辑关系被切掉。
    if role not in {"tweet_cover_27_36", "cover_27_48", "home_page_27_48", "bilibili_cover_4_3", "bilibili_home_16_9", "brand_end_page_27_48"}:
        body = body + " Relationship-first rule: the final raw image must be understandable as this narration's concept relationship, not as a generic topic background. Prefer a diagram-first textbook figure, cross-section, cutaway, exploded view, or comparison panel rather than a cinematic close-up."
    else:
        if role in {"tweet_cover_27_36", "cover_27_48", "home_page_27_48", "bilibili_cover_4_3", "bilibili_home_16_9", "brand_end_page_27_48"}:
            body = body + " A/C full-chapter summary rule: this must read as a chapter-level biomedical concept map that summarizes the whole chapter's problem, objects, mechanism/evidence chain and conclusion/next-question relationship; it must visibly include multiple concrete chapter elements rather than a single floating icon. Prefer at least 3 source-supported components for A-series and at least 2-4 recap components for C page, with explicit macro-micro or evidence/mechanism relationships when supported. Never use only generic biology symbols, generic brain/neurons/DNA/cells, decorative particles, medical wallpaper, or brand atmosphere."
        else:
            body = body + " Theme-specific rule: use a concrete motif from the chapter theme, not a generic decorative wallpaper."

    body = sanitize_cell_style_subject_text(body)
    if role == "content_diagram_27_48":
        contract = (
            "B-SERIES CONTRACT: flat or lightly shaded educational biomedical diagram matched to the paired voiceover. Prefer zero visible text; if needed, allow only 1-3 concise English keyword labels/callouts total, each 1-2 words, plus simple arrows. No short section headers. "
            "No title, no paragraph, no caption, no explanation box, no numbered steps, no bullet list, no table, no dense label clusters, no Chinese text, no logo, no watermark, no pseudo-text, no UI, no HUD, no cyberpunk, no neon sci-fi, no decorative random particles. "
            "Use an explanation-first biomedical illustration look with medically plausible morphology, clear structure relationships, crisp contour linework, light neutral background, minimal perspective distortion, and textbook-figure clarity."
        )
    else:
        contract = (
            "RAW CONTRACT: no visible text, no letters, no numbers, no labels, no captions, no logo, "
            "no watermark, no pseudo-text, no UI, no HUD, no cyberpunk, no neon sci-fi, no decorative random particles. "
            "Use an explanation-first biomedical illustration look with medically plausible morphology, clear structure relationships, crisp contour linework, soft dimensional shading, clean color separation, light neutral background, and explanation-first clarity. Allow slight 3D depth and subtle volume, but avoid flashy CGI, photoreal translucency, glossy rendering, and dramatic depth effects. "
            "All fixed typography, arrows, labels, logo, reference lines and masks are post-processing only."
        )
    locked = f"{body}\n{contract}"
    if len(locked) > IMAGE_API_PROMPT_BUDGET_CHARS:
        keep = max(720, IMAGE_API_PROMPT_BUDGET_CHARS - len(contract) - 2)
        body = body[:keep].rstrip(" ,，.;；。")
        locked = f"{body}\n{contract}"
    return re.sub(r"\s+", " ", locked).strip()



SCIENTIFIC_IMAGE_GUARDRAIL = ""

CONTENT_VISUAL_RICHNESS_SPEC = ""


# 生成脚本之后不再对“绘图提示词文件”做结构化精简；以下旧辅助函数保留为兼容入口。
def _first_visual_lock_marker_index(prompt: str) -> int:
    markers = [
        "GLOBAL IMAGE RULES — INCLUDE IN EVERY SINGLE IMAGE PROMPT",
        "CONTENT PAGE SOFTWARE LOGO LOCK — DO NOT DRAW LOGO IN THE RAW IMAGE",
        "ABSOLUTE B-TYPE LOGO LOCK",
        "SCIENTIFIC ACCURACY GUARDRAIL:",
        "CONTENT VISUAL RICHNESS SPEC:",
        "SERIES COVER / OPENING PAGE LAYOUT LOCK",
        "UNIFIED VISUAL SPEC",
    ]
    positions = [str(prompt or "").find(m) for m in markers if str(prompt or "").find(m) >= 0]
    return min(positions) if positions else -1


def _base_image_idea_from_prompt(prompt: str) -> str:
    """只抽取这张图自己的主体构图描述，剥离后面注入过的公共规则。"""
    p = re.sub(r"\s+", " ", str(prompt or "")).strip()
    cut = _first_visual_lock_marker_index(p)
    if cut > 0:
        p = p[:cut].strip()
    # 去掉少数模型可能直接写进主体段的参数说明，避免独立提示词里重复堆规格。
    p = re.sub(r"These are production instructions[^。.!?;；\n]*[。.!?;；]?", " ", p, flags=re.I)
    p = re.sub(r"Do not render the specification words themselves[^。.!?;；\n]*[。.!?;；]?", " ", p, flags=re.I)
    p = re.sub(r"\s+", " ", p).strip()
    return p


def _extract_visible_text_items_from_prompt(prompt: str) -> list[str]:
    """从旧版长提示词里提取 text "..." 可见文案，便于压缩封面/品牌页。"""
    items = []
    for m in re.finditer(r'text\s+["“]([^"”]{1,160})["”]', str(prompt or ""), flags=re.I):
        value = m.group(1).strip()
        if value and value not in items and not re.search(r"x=|y=|px|opacity|font|Canvas size", value, flags=re.I):
            items.append(value)
    return items[:10]


def _remove_verbose_visual_specs(prompt: str) -> str:
    """删除最耗 token 的像素坐标、字体参数、全局规则和重复负面约束。"""
    p = str(prompt or "").replace("\r\n", "\n").replace("\r", "\n")
    # 先切掉旧模板中从 Canvas size 开始的大块像素/坐标规格；主体画面描述通常在它之前。
    cut_markers = [
        "Canvas size:", "【A1 Mandatory", "【A2 Mandatory", "【B-type Mandatory", "【C-type Mandatory",
        "GLOBAL IMAGE RULES", "Global Image Rules", "ABSOLUTE B-TYPE LOGO LOCK",
        "Public Frame Lock", "Top Logo Frame Lock", "Central Text Group Frame Lock",
    ]
    cut_positions = [p.find(x) for x in cut_markers if p.find(x) >= 0]
    if cut_positions:
        p = p[:min(cut_positions)]
    # 删除残留的坐标/字号/颜色/比例句。
    p = re.sub(r"\b(?:x|y|width|height|center x|center y|size|font|opacity|ratio)\s*=\s*[^,.;；。\n]+[,.;；。]?", " ", p, flags=re.I)
    p = re.sub(r"#[0-9A-Fa-f]{6}", " ", p)
    p = re.sub(r"\b\d{3,4}\s*x\s*\d{3,4}\b", " ", p, flags=re.I)
    p = re.sub(r"\b\d{2,4}\s*px\b", " ", p, flags=re.I)
    p = re.sub(r"\s+", " ", p).strip(" +")
    return p


def _compact_role_spec(role: str, visible_items: list[str] | None = None) -> str:
    """旧压缩入口兼容：不再要求模型绘制公共文字，全部留给后处理。"""
    profile = _active_visual_style_profile()
    palette = f"active style: {profile['raw_aesthetic']}; restrained editorial composition; no safety bands/reference lines/fixed overlay elements in raw image"
    if role == "tweet_cover_27_36":
        return f"A1 Cover 3:4 raw full-chapter-summary biomedical Master Background only, generated from this chapter's core problem, biological objects, mechanism/evidence chain and conclusion boundary. No generic wallpaper. No logo, no title, no visible public text; software stamps public elements after generation. {palette}."
    if role == "cover_27_48":
        return f"A1/A2/A01/A02 raw full-chapter-summary biomedical Master Background only; A1 is the only real generation prompt, and A2/A01/A02 are crop-only derivatives from the same mother image. No generic brain/neuron/DNA/cell wallpaper and no unrelated chapter motif. No logo, no title, no chapter text, no visible public text; software stamps public elements after generation. {palette}."
    if role == "brand_end_page_27_48":
        return f"C brand end page raw full-chapter-summary biomedical closing background only, generated from this chapter's core problem, mechanism/evidence chain, conclusion boundary and next-question relationship. No generic brand atmosphere, no soft particles, no unrelated chapter image. No logo, no slogan, no CTA, no visible public text; software stamps public elements after generation. {palette}."
    return f"B content explanation image. No public logo, no book title, no chapter title, no brand text in the raw image; no safety bands or guide/reference lines; software stamps fixed elements after generation. {palette}."


def compact_image_prompt_preserving_effect(prompt: str, prompt_name: str = "") -> str:
    """兼容旧入口：只清洗旧版长绘图提示词，不再按字符数截断。"""
    raw = str(prompt or "").strip()
    if not raw:
        return ""
    if not IMAGE_PROMPT_COMPACT_MODE:
        return raw
    role = detect_visual_role(prompt_name, raw)
    visible_items = _extract_visible_text_items_from_prompt(raw)
    base = _remove_verbose_visual_specs(_base_image_idea_from_prompt(raw) or raw)
    if role == "content_diagram_27_48":
        base = sanitize_content_prompt_text_policy(sanitize_content_prompt_brand_text(base))
    if not base:
        base = "Active-style no-text educational illustration relevant to this chapter."
    spec = _compact_role_spec(role, visible_items)
    result = f"{base}. {spec}".strip()
    return re.sub(r"\s+", " ", result).strip()


def prepare_image_prompt_for_api(prompt: str, prompt_name: str = "", logger=None) -> str:
    """图像 API 调用前：逐张读取独立绘图提示词，再只追加统一公共元素锁定规则。"""
    raw = str(prompt or "").strip()
    if not raw:
        return ""
    locked = enforce_canonical_visual_spec(raw, prompt_name=prompt_name)
    before_len = len(locked)
    role = detect_visual_role(prompt_name, raw)
    tail = (
        "Final hard rules: textbook teaching figure only; no atmosphere, no poster, no decorative wallpaper. "
        "Allow only minimal concise English scientific keyword labels for B-series, typically 2-4 callouts when helpful, each 1-2 words; no Chinese, no logo, no watermark, no pseudo-text."
        if role == "content_diagram_27_48" else
        "Final hard rules: textbook teaching figure only; no atmosphere, no poster, no decorative wallpaper. Raw image only: no visible text, letters, numbers, labels, logo, watermark, pseudo-text."
    )
    locked = _hard_cap_visual_prompt_text(
        locked,
        max_chars=IMAGE_API_HARD_MAX_CHARS,
        tail=tail,
    )
    if logger:
        if len(locked) < before_len:
            logger(f"✂️ 已压缩 {prompt_name or '当前图片'} 的 API 绘图提示词：{before_len} → {len(locked)} 字符。")
        logger(f"🔒 已为 {prompt_name or '当前图片'} 注入分层生产 raw 图协议；最终提示词约 {len(locked)} 字符。")
    return locked


SERIES_COVER_LAYOUT_LOCK = ""

COVER_ENDING_AESTHETIC_SPEC = ""

PUBLIC_ELEMENT_PARAMETER_TABLE = ""

GLOBAL_IMAGE_GENERATION_GUARDRAIL = f"""
GLOBAL NON-NEGOTIABLE IMAGE RULES:
These are invisible production instructions only. Do not render the specification language itself into the image.
{LOCKED_MOBILE_FONT_SPEC}
{LOCKED_MEDICAL_FONT_STYLE_SPEC}
{LOCKED_CENTERED_LAYOUT_SPEC}
{PUBLIC_ELEMENT_STYLE_LOCK}
{SERIES_COVER_LAYOUT_LOCK}
{PUBLIC_ELEMENT_PARAMETER_TABLE}
{COVER_ENDING_AESTHETIC_SPEC}
{CANONICAL_PUBLIC_VISUAL_SPEC}
{SCIENTIFIC_IMAGE_GUARDRAIL}
{CONTENT_VISUAL_RICHNESS_SPEC}
PUBLIC BRAND LOCK: public brand elements belong only to QuanLan BrainScience and must never be drawn by the image model. This program only produces science-book interpretation assets; do not use humanities, film, commercial, marketing, poster, or entertainment-reading visual systems. Fixed overlays must not be drawn by the image model: no logo, watermark, safety bands, reference lines, coordinates, UI panels, QR or CTA. Book/chapter cover typography, chapter number/title, safety masks, reference lines and brand elements are added by software post-processing. A1/A2/A01/A02 covers must keep both Chinese and English chapter titles in the post-processing layer. Diagram text must stay minimal: no paragraphs, no captions, no long explanations, no legends, and no text boxes; for B-series use only necessary short English scientific annotation keywords beside structures when essential, typically 2-4 concise callouts total, each 1-2 words. Keep the design minimal, explicit, disciplined, centered, and instructional. B-series images must teach one sentence-level concept with explicit subject, action, and result rather than stacking repeated chapter motifs.
""".strip()


OBJECTIVE_SCIENTIFIC_CN_GUARDRAIL = ""

SCRIPT_GENERATION_COMPACT_QUALITY_GUARDRAIL = ""


# ================== 提示词模板 (已深度优化: 大写/首尾闭环/内容零损耗/硬核科普过渡) ==================
SCRIPT_PROMPT_TEMPLATE = ""




PROFESSIONAL_TERMINOLOGY_REPLACEMENTS = {
    "中央神经系统": "中枢神经系统",
    "外围神经系统": "外周神经系统",
    "周边神经系统": "外周神经系统",
    "工作内存": "工作记忆",
    "神经电路": "神经环路",
    "神经回路": "神经环路",
    "脑电路": "脑环路",
    "脑回路": "脑环路",
    "神经线路": "神经通路",
    "默认模式网": "默认模式网络",
    "显著网络": "显著性网络",
    "执行功能控制": "执行控制",
    "杏仁体": "杏仁核",
    "海马体": "海马",
    "连接体组": "连接组",
    "神经可塑": "神经可塑性",
    "突触可塑": "突触可塑性",
    "突触强度": "突触传递效能",
    "是许多神经精神疾病的药物靶点": "是原文提到的一类重要受体",
    "药物靶点": "作用对象",
    "在临床观察中，": "",
    "在临床观察中": "",
    "临床上，": "",
    "在临床上，": "",
}


def apply_professional_terminology_cleanup(script_text: str) -> str:
    """保存前的专业术语兜底清洗。只做高置信、固定错误译法替换。"""
    if not script_text:
        return script_text
    cleaned = script_text
    for bad, good in PROFESSIONAL_TERMINOLOGY_REPLACEMENTS.items():
        cleaned = cleaned.replace(bad, good)
    banned_intro_phrases = [
        "所有知识点均严格依据原文逻辑展开。",
        "所有知识点均严格依据原文逻辑展开",
        "全文知识点均严格依据原文逻辑展开。",
        "全文知识点均严格依据原文逻辑展开",
    ]
    for phrase in banned_intro_phrases:
        cleaned = cleaned.replace(phrase, "")

    # 开场介绍句兜底：避免‘本期解读的是……今天分享的章节是……’重复介绍。
    # 只处理高置信固定句式，不改变科学内容。
    cleaned = re.sub(
        r"本期解读的是([^。；;!?！？]{1,80}?)。?今天分享的章节是[:：]?\s*",
        r"今天继续分享\1的",
        cleaned
    )
    cleaned = re.sub(
        r"今天继续分享([^。；;!?！？]{1,80}?)的的",
        r"今天继续分享\1的",
        cleaned
    )
    cleaned = cleaned.replace("本期解读的是", "今天继续分享")

    # 高置信论文腔/机翻腔兜底：避免保存时残留特别生硬的固定句式。
    academic_phrase_replacements = {
        "这为理解行为状态转换提供了分子基础。": "这样看，行为状态的切换，可能要先从分子层面说起。",
        "这为理解行为状态转换提供了分子基础": "这样看，行为状态的切换，可能要先从分子层面说起",
        "这提示我们该机制具有重要意义。": "这一步把问题往前推了一层。",
        "这提示我们该机制具有重要意义": "这一步把问题往前推了一层",
        "这揭示了该机制的重要意义。": "这让这个机制的作用更清楚了。",
        "这揭示了该机制的重要意义": "这让这个机制的作用更清楚了",
        "为理解这一过程提供了基础。": "让我们可以从这里开始理解这个过程。",
        "为理解这一过程提供了基础": "让我们可以从这里开始理解这个过程",
        "这为理解行为状态转换提供了分子基础。": "这样看，行为状态的切换，可能要先从分子层面的调节说起。",
        "这为理解行为状态转换提供了分子基础": "这样看，行为状态的切换，可能要先从分子层面的调节说起",
    }
    for bad, good in academic_phrase_replacements.items():
        cleaned = cleaned.replace(bad, good)
    return cleaned


def sanitize_sentence_clarity_and_redundancy(text: str) -> str:
    """保存前清理高置信的语病、重复修饰和不完整表意；只做保守句法修正。"""
    if not text:
        return text
    t = str(text)

    fixed_replacements = {
        "涉及慢速突触调节和第二信使对神经元兴奋性的长效改变。": "本章从较慢的突触调节过程讲起，重点说明代谢型受体和第二信使通路。它们可以在较长时间尺度上调节神经元兴奋性。",
        "涉及慢速突触调节和第二信使对神经元兴奋性的长效改变": "本章从较慢的突触调节过程讲起，重点说明代谢型受体和第二信使通路。它们可以在较长时间尺度上调节神经元兴奋性",
        "慢速突触调节和第二信使对神经元兴奋性的长效改变": "通过代谢型受体和第二信使通路，对神经元兴奋性进行较慢、较持久的调节",
        "第二信使对神经元兴奋性的长效改变": "第二信使通路对神经元兴奋性的较持久调节",
        "神经元兴奋性的长效改变": "神经元兴奋性的较持久调节",
        "慢速突触调节": "较慢的突触调节过程",
        "这类受体反应极快且短暂，且持续时间短暂。": "这类受体介导的反应通常起效快、持续时间短。",
        "这类受体反应极快且短暂， 且持续时间短暂。": "这类受体介导的反应通常起效快、持续时间短。",
        "这类受体反应极快且短暂，且持续时间短暂": "这类受体介导的反应通常起效快、持续时间短",
        "这类受体反应极快且短暂， 且持续时间短暂": "这类受体介导的反应通常起效快、持续时间短",
        "反应极快且短暂，且持续时间短暂": "反应起效快、持续时间短",
        "反应极快且短暂， 且持续时间短暂": "反应起效快、持续时间短",
        "作用很快且短暂，且持续时间短暂": "作用出现较快，持续时间较短",
        "快速短暂，且持续时间短暂": "起效快，持续时间短",
        "很短暂且持续时间短暂": "持续时间短",
        "持续时间短暂": "持续时间短",
    }
    for bad, good in fixed_replacements.items():
        t = t.replace(bad, good)

    # 清理同一句中连续重复的“短暂/短/很快/快速”等修饰，避免“短暂，且持续时间短”一类冗余。
    t = re.sub(r"([^。！？\n]{0,40}?)(?:极快|很快|快速)且短暂[，,、]?\s*且(?:持续时间)?(?:也)?(?:很)?短(?:暂)?", r"\1起效快、持续时间短", t)
    t = re.sub(r"([^。！？\n]{0,40}?)短暂[，,、]?\s*且持续时间短", r"\1持续时间短", t)

    t = re.sub(r"短暂[，,、]?\s*且短暂", "短暂", t)

    # 保持口播句子表意完整：避免“且……”孤立悬挂。
    t = re.sub(r"([。！？；;])\s*且", r"\1同时", t)

    # 清理多余空格和中文标点前空格。
    t = re.sub(r"[ \t]+([，。！？；：、])", r"\1", t)
    t = re.sub(r"([，。！？；：、])[ \t]+", r"\1", t)
    return t


def sanitize_final_chinese_logic_and_professional_expression(text: str) -> str:
    """保存前最后一层中文审校：修正高置信的不地道专业表达、抽象名词堆叠和逻辑压缩句。"""
    if not text:
        return text

    t = str(text)

    # 高置信专业表达修正：只改明确不自然或过度压缩的固定句式，避免误改原文含义。
    professional_replacements = {
        "涉及慢速突触调节和第二信使对神经元兴奋性的长效改变。": "本章从较慢的突触调节过程讲起，重点说明代谢型受体和第二信使通路。它们可以在较长时间尺度上调节神经元兴奋性。",
        "涉及慢速突触调节和第二信使对神经元兴奋性的长效改变": "本章从较慢的突触调节过程讲起，重点说明代谢型受体和第二信使通路。它们可以在较长时间尺度上调节神经元兴奋性",
        "涉及较慢的突触调节过程和第二信使通路对神经元兴奋性的较持久调节。": "本章从较慢的突触调节过程讲起，重点说明代谢型受体和第二信使通路。它们可以在较长时间尺度上调节神经元兴奋性。",
        "慢速突触调节": "较慢的突触调节过程",
        "长效改变": "较持久的调节",
        "对神经元兴奋性的长效改变": "对神经元兴奋性的较持久调节",
        "第二信使对神经元兴奋性的长效改变": "第二信使通路对神经元兴奋性的较持久调节",
    }
    for bad, good in professional_replacements.items():
        t = t.replace(bad, good)

    # 避免“涉及A和B”这类压缩式开场句。只处理短句，改成更完整的说明结构。
    t = re.sub(
        r"口播文案[：:]\s*涉及([^。！？\n]{4,80})。",
        lambda m: "口播文案：这一部分需要说明" + m.group(1).strip() + "之间的关系。",
        t
    )

    # 清理抽象名词堆叠导致的“X和Y对Z的……”结构，让语义关系更明确。
    t = re.sub(
        r"第二信使通路和([^，。！？\n]{2,30})对神经元兴奋性的较持久调节",
        r"第二信使通路如何与\1一起，在较长时间尺度上调节神经元兴奋性",
        t
    )

    # 删除或改写无中生有的对比/否定转折，尤其是前文没有铺垫“离子通道”时突然写“不能单靠”。
    unsupported_logic_replacements = {
        "不能仅靠快速的电信号解释，这就需要引入慢速的突触调节与第二信使机制。":
            "这一部分进入本章的主线：较慢的突触调节过程，以及第二信使通路如何参与神经元兴奋性的调节。",
        "不能仅靠快速的电信号解释，这就需要引入慢速的突触调节与第二信使机制":
            "这一部分进入本章的主线：较慢的突触调节过程，以及第二信使通路如何参与神经元兴奋性的调节",
        "不能仅靠快速电信号解释，这就需要引入慢速的突触调节与第二信使机制。":
            "这一部分进入本章的主线：较慢的突触调节过程，以及第二信使通路如何参与神经元兴奋性的调节。",
        "不能仅靠快速电信号解释，这就需要引入慢速的突触调节与第二信使机制":
            "这一部分进入本章的主线：较慢的突触调节过程，以及第二信使通路如何参与神经元兴奋性的调节",
        "这种现象不能仅靠快速的电信号解释，这就需要引入慢速的突触调节与第二信使机制。":
            "接下来要看的，是较慢的突触调节过程，以及第二信使通路如何参与神经元兴奋性的调节。",
        "这种现象不能仅靠快速的电信号解释，这就需要引入慢速的突触调节与第二信使机制":
            "接下来要看的，是较慢的突触调节过程，以及第二信使通路如何参与神经元兴奋性的调节",
        "这种状态的维持，不能单靠快速开启的离子通道来解释。本章讨论的是，神经递质如何通过代谢型受体启动第二信使通路，并在较长时间尺度上调节神经元的兴奋性。":
            "本章从突触传递的时间尺度讲起。原文进一步讨论代谢型受体和第二信使通路如何参与较慢、较持久的兴奋性调节。",
        "这种状态的维持，不能单靠快速开启的离子通道来解释。":
            "原文在快速突触传递之外，进一步讨论较慢的调节过程。",
        "不能单靠快速开启的离子通道来解释。":
            "还需要说明较慢的受体通路如何参与调节。",
        "本章讨论的是，神经递质如何通过代谢型受体启动第二信使通路，并在较长时间尺度上调节神经元的兴奋性。":
            "本章重点说明代谢型受体和第二信使通路。它们可以在较长时间尺度上调节神经元兴奋性。",
    }
    for bad, good in unsupported_logic_replacements.items():
        t = t.replace(bad, good)

    # 禁止无铺垫的“快速电信号 vs 慢速第二信使”对比。若前文没有明确交代比较对象，改成顺接的主题进入句。
    t = re.sub(
        r"(?:这种(?:状态|现象|变化)[^。！？]{0,20})?不能(?:单靠|仅靠)[^。！？]{0,18}(?:快速|快)[^。！？]{0,18}(?:电信号|离子通道|突触传递)[^。！？]{0,20}(?:解释|说明)[，,。；;]?\s*(?:这就|因此|所以|于是)?(?:需要|要)?(?:引入|进入|转向)[^。！？]{0,30}(?:慢速|较慢)[^。！？]{0,30}(?:第二信使|代谢型受体)[^。！？]*[。！？]?",
        "这一部分进入本章的主线：较慢的突触调节过程，以及第二信使通路如何参与神经元兴奋性的调节。",
        t
    )
    t = re.sub(
        r"(?:这种(?:状态|现象|变化)[^。！？]{0,20})?不能(?:单靠|仅靠)[^。！？]{0,18}(?:快速|快)[^。！？]{0,18}(?:电信号|离子通道|突触传递)[^。！？]{0,20}(?:解释|说明)[。！？]",
        "接下来原文把讨论推进到较慢的突触调节过程。",
        t
    )

    # 拆分“本章讨论的是，A如何通过B，并在C上D”这类长难句。
    t = re.sub(
        r"本章讨论的是，神经递质如何通过代谢型受体启动第二信使通路，并在较长时间尺度上调节神经元的兴奋性。",
        "本章重点说明代谢型受体和第二信使通路。神经递质可以通过这些通路，在较长时间尺度上调节神经元兴奋性。",
        t
    )

    # 结尾品牌页兜底：如果模型只写了公众号引导，至少补上“本期总结/下期预告/关注引导”的结构提醒。
    t = t.replace("这篇研究的快速导读就先到这。关注我们，下一章，我们将继续讲解相关神经科学问题。",
                  "本期我们梳理了这项研究的核心问题、证据线索和主要结论。下期将继续围绕相关神经科学问题展开。关注我们，下一章，我们将继续讲解相关神经科学问题。")
    t = t.replace("关注我们，下一章，我们将继续讲解相关神经科学问题。",
                  "关注我们，下一章，我们将继续讲解相关神经科学问题。")

    # 删除模型误写进脚本的“写作要求/审校要求”，这些不是口播内容。
    meta_instruction_patterns = [
        r"(?m)^\s*[-•*]?\s*口播文案[：:]\s*钩子案例要贴合内容[^\n。！？]*[。！？]?\s*$",
        r"(?m)^\s*[-•*]?\s*口播文案[：:]\s*不要有这种无意义的口水话[^\n。！？]*[。！？]?\s*$",
        r"(?m)^\s*[-•*]?\s*口播文案[：:]\s*.*不要悬浮编造[^\n。！？]*[。！？]?\s*$",
        r"(?m)^\s*[-•*]?\s*口播文案[：:]\s*.*贴合内容且与生活相关[^\n。！？]*[。！？]?\s*$",
        r"(?m)^\s*[-•*]?\s*口播文案[：:]\s*.*引发观众共鸣[^\n。！？]*[。！？]?\s*$",
    ]
    for pat in meta_instruction_patterns:
        t = re.sub(pat, "", t)

    # 句子层面的轻量清洁：避免连续逗号、标点前后空格、空句。
    t = re.sub(r"，{2,}", "，", t)
    t = re.sub(r"。{2,}", "。", t)
    t = re.sub(r"[ \t]+([，。！？；：、])", r"\1", t)
    t = re.sub(r"([，。！？；：、])[ \t]+", r"\1", t)
    t = re.sub(r"(?m)^\s*[-•*]?\s*口播文案[：:]\s*[。；;]?\s*$", "", t)
    return t
