# Auto-generated split runtime module.
# Source: backup/AutoMediaProducer_integrated_postprocess_spec.py lines 9792-11290.
# Do not edit this file alone; edit the canonical source and run tools/sync_split_runtime.py.



WEB_CALL_MODE_API = "API 自动调用"
WEB_CALL_MODE_MANUAL = "网页手动输入"
CALL_MODE_OPTIONS = [WEB_CALL_MODE_API]


def is_web_manual_mode(call_mode: str) -> bool:
    return False


def get_web_bridge_dir(base_dir: str) -> str:
    return os.path.join(base_dir, "90_网页手动输入桥接")


def _web_step_slug(step_label: str) -> str:
    return safe_filename(step_label, max_len=60, fallback="web_step")


def web_text_result_or_export(base_dir: str, step_label: str, prompt: str, engine: str, logger=None) -> str:
    """网页手动输入模式：导出当前步骤网页输入提示词；若用户已保存网页返回文件，则读取结果继续。"""
    bridge_dir = get_web_bridge_dir(base_dir)
    os.makedirs(bridge_dir, exist_ok=True)
    slug = _web_step_slug(step_label)
    prompt_path = os.path.join(bridge_dir, f"{slug}_输入提示词.txt")
    result_path = os.path.join(bridge_dir, f"{slug}_网页返回.txt")
    readme_path = os.path.join(bridge_dir, "00_网页手动输入说明.txt")
    write_text_file(readme_path, (
        "网页手动输入模式使用说明\n"
        "1. 打开 *_输入提示词.txt，复制全部内容到对应模型网页。\n"
        "2. 将网页生成的完整返回结果保存到同名 *_网页返回.txt。\n"
        "3. 再次运行同一章节，程序会自动读取 *_网页返回.txt 并继续后续步骤。\n"
        "4. 配图步骤会导出每张图的独立提示词；手动生成图片后，请按日志提示的文件名保存到目标图片目录。\n\n"
        + MANUAL_IMAGE_NAMING_RULES
    ))
    if is_nonempty_file(result_path, min_bytes=50):
        result = read_text_file(result_path).strip()
        if logger:
            logger(f"🌐 已读取网页返回结果：{os.path.basename(result_path)}（{len(result)} 字符）")
        return result
    write_text_file(prompt_path, prompt)
    if logger:
        logger(f"🌐 网页手动输入模式：已导出 {step_label} 的完整输入提示词。")
        logger(f"   模型建议：{describe_text_engine(engine)}")
        logger(f"   请复制：{prompt_path}")
        logger(f"   网页返回后保存到：{result_path}")
        logger("   保存网页返回文件后，重新运行同一流程即可从这里继续。")
    return ""


def export_web_image_prompts(pending_images: list, images_dir: str, image_engine: str, logger=None) -> None:
    """网页手动输入模式：把每张待生成图片的完整提示词导出为独立文件，用户可在多个网页窗口独立绘图。"""

    if not pending_images:
        return
    prompt_dir = os.path.join(os.path.dirname(images_dir), "90_网页手动输入桥接", "20_待手动生成图片_API提示词")
    os.makedirs(prompt_dir, exist_ok=True)
    index_lines = ["# 网页手动配图索引", "", f"建议模型：{describe_image_engine(image_engine)}", "", "## 手动生成图片命名规则", MANUAL_IMAGE_NAMING_RULES.rstrip(), "", "## 统一后处理说明", "封面/首页/结尾页公共文字与装饰线由程序统一后处理；B 系列内容页会套上下20%安全蒙版，强制留出顶部品牌区和底部字幕区。手动绘图时请不要主动绘制公共元素。", ""]
    write_manual_image_naming_rules(images_dir, logger=None)
    for p_name, p_text, img_save_path in pending_images:
        prompt_file = os.path.join(prompt_dir, f"{safe_filename(p_name, max_len=80, fallback='image')}_API绘图提示词.txt")
        write_text_file(prompt_file, prepare_image_prompt_for_api(p_text, prompt_name=p_name, logger=None).strip() + "\n")
        index_lines.append(f"- {p_name}")
        index_lines.append(f"  - 输入提示词：{prompt_file}")
        index_lines.append(f"  - 网页生成后请保存为：{img_save_path}")
        index_lines.append("")
    write_text_file(os.path.join(prompt_dir, "00_手动配图索引.txt"), "\n".join(index_lines))
    if logger:
        logger(f"🌐 网页手动输入模式：已导出 {len(pending_images)} 条配图提示词。")
        logger(f"   提示词目录：{prompt_dir}")
        logger("   可把每个 txt 复制到不同网页窗口独立绘图；生成后按索引中的文件名保存 PNG，再重新运行即可自动检查缺图。")
        write_manual_image_naming_rules(images_dir, logger=logger)



def cleanup_final_only_outputs(ch_dir: str, script_path: str, images_dir: str = "", logger=None) -> None:
    """最终输出精简：保留最终 LRC、最终台词、最终绘图提示词、章节 PDF 和图片目录。

    v8.0：断点续作默认优先保留已有缓存，不清理 parsed_content.md、翻译缓存、图文中间稿等，
    避免下次运行又重新解析或重新请求模型。若确实需要最终精简，可设置
    QUANLAN_CLEANUP_DURING_RESUME=1。
    """
    if not FINAL_ONLY_OUTPUT_MODE:
        return
    # v17：精简模式下默认也清理冗余中间文件。断点续作只依赖章节序号、最终台词、LRC、绘图提示词、短视频总结和图片目录。
    if resume_skip_existing_enabled() and not resume_force_rebuild_enabled() and not _env_bool("QUANLAN_CLEANUP_DURING_RESUME", True):
        if logger:
            logger("♻️ 已按配置保留中间缓存文件，跳过最终精简清理。")
        return
    keep = {
        os.path.abspath(script_path),
        os.path.abspath(os.path.splitext(script_path)[0] + ".lrc"),
        os.path.abspath(get_voiceover_text_path(script_path)),
        os.path.abspath(get_image_prompt_text_path(script_path)),
        os.path.abspath(get_short_video_summary_text_path(script_path)),
    }
    # parsed_content.md 是旧版遗留中间文件；章节 PDF 是当前直传大模型的核心输入，默认保留。
    delete_names = {
        "parsed_content.md",
        "0_目录信息_给大模型.txt",
        "0_章节名翻译.txt",
        "0_章节名翻译提示词.txt",
        "0_脚本生成提示词_含目录.txt",
        "0_脚本生成提示词_需手动上传PDF.txt",
        "07_图文对齐整理提示词.txt",
        "0_视频简介生成提示词.txt",
        "0_短视频总结生成提示词.txt",
        "运行计时摘要.txt",
    }
    suffix_delete = (
        "_完整脚本原稿.txt",
        "_纯台词脚本.txt",
        "_绘图脚本.txt",
        "_视频简介.txt",
        "_图文一一对应脚本.txt",
        "_总脚本_图文一一对应.txt",
        "_初稿绘图脚本.txt",
        "_初稿台词_未标图号.txt",
        "_初稿台词_已标图号.txt",
        "_LRC配图台词对应表.txt",
        "_LRC配图ABC映射表.txt",
        "_口播台词_逐句锁定_最终版.txt",
        "_口播台词_便捷入口.txt",
        "_绘图提示词_便捷入口.txt",
        ".api_prompt.txt",
    )
    removed = 0
    try:
        for name in os.listdir(ch_dir):
            path = os.path.join(ch_dir, name)
            abspath = os.path.abspath(path)
            if abspath in keep:
                continue
            if os.path.isdir(path):
                if os.path.abspath(path) == os.path.abspath(images_dir or ""):
                    continue
                if name in {"90_网页手动输入桥接", "90_网页手动输入桥接_legacy"}:
                    if safe_rmtree(path, logger=logger):
                        removed += 1
                continue
            if name in delete_names or any(name.endswith(suf) for suf in suffix_delete):
                if safe_remove_file(path, logger=logger):
                    removed += 1
        # 图片目录只保留图片和 prompt hash；完整 API prompt 副本可由总绘图提示词重建，默认清理。
        if images_dir and os.path.isdir(images_dir) and not save_image_api_prompt_sidecars_enabled():
            for root_dir, _dirs, files in os.walk(images_dir):
                for fname in files:
                    if fname.endswith(".api_prompt.txt"):
                        if safe_remove_file(os.path.join(root_dir, fname), logger=logger):
                            removed += 1
        if logger and removed:
            logger(f"🧹 最终精简输出已清理 {removed} 个中间文件；保留：主脚本/LRC、唯一绘图提示词、短视频总结、封面首页元信息和图片目录。")
    except Exception as e:
        if logger:
            logger(f"⚠️ 最终精简清理失败：{str(e)[:120]}")


NON_CONTENT_TOC_TITLES = {
    # 书后/章后工具性栏目：不要作为独立章节进入流水线
    "highlights",
    "glossary",
    "selected reading",
    "selected readings",
    "references",
    "reference",
    "bibliography",
    "further reading",
    "further readings",
    "suggested reading",
    "suggested readings",
    "recommended reading",
    "recommended readings",
    "additional reading",
    "additional readings",
    "key terms",
    "review questions",
    "study questions",
    "questions",
    "answers",
    "index",
    "author index",
    "subject index",
    "name index",
    "contents",
    "table of contents",
    "acknowledgments",
    "acknowledgements",
    "preface",
    "credits",
    "about the author",
    "about the authors",
    # 常见中文工具性栏目
    "重点",
    "本章重点",
    "摘要",
    "小结",
    "术语表",
    "名词解释",
    "参考文献",
    "参考资料",
    "延伸阅读",
    "推荐阅读",
    "精选阅读",
    "阅读材料",
    "索引",
    "人名索引",
    "主题索引",
    "目录",
    "致谢",
    "前言",
}


def normalize_toc_title_for_filter(title: str) -> str:
    """把 PDF 书签标题规整成适合过滤判断的短标题。"""
    text = unicodedata.normalize("NFKC", str(title or "")).strip()
    text = re.sub(r"\s+", " ", text)
    # 去掉常见书签序号前缀，如 "035.", "35)", "III.", "第35章"。
    text = re.sub(r"^\s*\d{1,4}\s*[\.)、．]\s*", "", text)
    text = re.sub(r"^\s*[IVXLCDM]{1,12}\s*[\.)、．]\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"^\s*第\s*[一二三四五六七八九十百千万零〇两0-9]+\s*[章节篇部卷]\s*", "", text)
    # 有些导出文本会带页码或层级信息，这里只保留最后一个标题段。
    if "|" in text:
        text = text.split("|")[-1].strip()
    text = re.sub(r"\s+(?:p\.?\s*\d+|page\s*\d+)$", "", text, flags=re.IGNORECASE)
    text = re.sub(r"[\s\-_:：;；,.。]+$", "", text).strip()
    return text.casefold()


def is_non_content_toc_title(title: str) -> bool:
    """识别 Highlights / Glossary / References 等与正文机制无关的工具性目录项。"""
    norm = normalize_toc_title_for_filter(title)
    if not norm:
        return True
    if norm in NON_CONTENT_TOC_TITLES:
        return True
    # 只匹配非常短的工具性短语，避免误杀 "References in neural coding" 这类正文标题。
    if len(norm) <= 40 and re.fullmatch(
        r"(?:selected|suggested|recommended|additional|further) readings?", norm

    ):
        return True
    return False


def should_keep_toc_bookmark_title(title: str) -> bool:
    """PDF 书签进入章节列表前的统一过滤规则。"""
    raw = str(title or "").strip()
    if not raw or "\n" in raw or len(raw) >= 150:
        return False
    return not is_non_content_toc_title(raw)

def is_part_toc_title(title: str) -> bool:
    """识别 Part / Section / Unit 这类目录分部标题；它们保留在树里，但不作为脚本章节。"""
    text = unicodedata.normalize("NFKC", str(title or "")).strip()
    text = re.sub(r"\s+", " ", text)
    low = text.casefold()
    if re.match(r"^(?:part|section|unit)\s+[ivxlcdm0-9]+(?:\b|\s+)", low, flags=re.IGNORECASE):
        return True
    if re.match(r"^第\s*[一二三四五六七八九十百千万零〇两0-9]+\s*[部篇卷]\b", text):
        return True
    return False


def _chapter_number_display(raw_number: str, raw_prefix: str = "") -> str:
    """把目录中的原始章节号统一成适合中文口播/封面的显示形式。"""
    raw = re.sub(r"\s+", " ", str(raw_number or "")).strip()
    prefix = str(raw_prefix or "").strip()
    if not raw:
        return ""
    if prefix.startswith("第"):
        if re.search(r"[章节]", prefix):
            return re.sub(r"\s+", "", prefix)
        return f"第{raw}章"
    if re.fullmatch(r"\d+(?:\.\d+)*", raw):
        return f"第{raw}章"
    if prefix.lower().startswith(("chapter", "ch")):
        return f"第{raw}章"
    return raw


def parse_chapter_title_metadata(title: str, idx_in_toc: int | None = None) -> dict:
    """从 PDF 书签标题中拆出：真实章节号、去掉编号后的章节标题、是否正文章节。"""
    original = str(title or "").strip()
    text = unicodedata.normalize("NFKC", original)
    text = re.sub(r"\s+", " ", text).strip()
    meta = {
        "original_title": original,
        "chapter_number": "",
        "number_raw": "",
        "title_clean": text,
        "is_numbered_chapter": False,
        "is_part_title": is_part_toc_title(text),
        "is_non_content": is_non_content_toc_title(text),
    }
    if not text or meta["is_part_title"] or meta["is_non_content"]:
        return meta

    patterns = [
        # 第16章 Neurotransmitters / 第十六章 神经递质
        r"^(第\s*([一二三四五六七八九十百千万零〇两0-9]+)\s*[章节])\s*[\-_:：、.)）．]*\s*(.+)$",
        # Chapter 16 Neurotransmitters / Ch. 16 Neurotransmitters
        r"^((?:chapter|ch\.?|chap\.?)\s*([0-9]+(?:\.[0-9]+)*))\s*[\-_:：、.)）．]*\s*(.+)$",
        # 16 Neurotransmitters / 16. Neurotransmitters / 16) Neurotransmitters
        r"^(([0-9]+(?:\.[0-9]+)*))\s*[\-_:：、.)）．]?\s+(.+)$",
    ]
    for pattern in patterns:
        m = re.match(pattern, text, flags=re.IGNORECASE)
        if not m:
            continue
        raw_prefix = m.group(1).strip()
        raw_number = m.group(2).strip()
        clean_title = m.group(3).strip()
        meta.update({
            "chapter_number": _chapter_number_display(raw_number, raw_prefix),
            "number_raw": raw_number,
            "title_clean": clean_title or text,
            "is_numbered_chapter": True,
        })
        return meta

    # 罗马数字章节兜底；但 Part IV 已在前面排除。
    m = re.match(r"^([IVXLCDM]{1,12})\s+[\-_:：、.)）．]?\s*(.+)$", text, flags=re.IGNORECASE)
    if m:
        meta.update({
            "chapter_number": m.group(1).upper(),
            "number_raw": m.group(1).upper(),
            "title_clean": m.group(2).strip() or text,
            "is_numbered_chapter": True,
        })
    return meta


def is_scriptable_chapter_title(title: str) -> bool:
    """只有真正带章节号的正文条目才进入脚本流水线；Part、Glossary、References 等都跳过。"""
    meta = parse_chapter_title_metadata(title)
    return bool(meta.get("is_numbered_chapter")) and not meta.get("is_part_title") and not meta.get("is_non_content")


def infer_chapter_number_from_title(title: str, idx_in_toc: int) -> str:
    """从 PDF 目录标题中保留真实章节序号；不再用包含 Part 的目录下标兜底伪造章节号。"""
    meta = parse_chapter_title_metadata(title, idx_in_toc)
    if meta.get("chapter_number"):
        return meta["chapter_number"]
    return f"第{idx_in_toc + 1}章"


def chapter_dir_prefix_from_meta(meta: dict, idx_in_toc: int) -> str:
    """章节目录名前缀优先使用真实章节号，避免 Part 分部把序号顶偏。"""
    raw = str((meta or {}).get("number_raw") or "").strip()
    m = re.search(r"\d+", raw)
    if m:
        return f"{int(m.group(0)):02d}"
    display = str((meta or {}).get("chapter_number") or "").strip()
    m = re.search(r"\d+", display)
    if m:
        return f"{int(m.group(0)):02d}"
    return f"{idx_in_toc + 1:02d}"


def build_chapter_theme_for_prompt(ch: dict, idx_in_toc: int | None = None) -> str:
    """给提示词使用的章节名：真实章节号 + 去编号后的标题。"""
    title = str((ch or {}).get("title", "")).strip()
    meta = parse_chapter_title_metadata(title, idx_in_toc)
    number = meta.get("chapter_number") or ""
    clean_title = meta.get("title_clean") or title
    return f"{number} {clean_title}".strip() if number else clean_title


def _episode_subtitle_from_dirname(ch_dir: str, fallback: str = "") -> str:
    """从章节输出文件夹名提取“每集小标题”。

    文件夹名是本地权威来源；去掉前缀序号/Chapter/第X章，只保留标题部分。
    例：32_Sensory Coding -> Sensory Coding；第32章_感觉编码 -> 感觉编码。
    """
    try:
        name = os.path.basename(os.path.abspath(str(ch_dir or ""))).strip()
    except Exception:
        name = ""
    if not name:
        return str(fallback or "").strip()
    name = re.sub(r"[_]+", " ", name).strip(" ._-—–")
    # 去掉常见章节前缀，但不改写标题本身。
    name = re.sub(r"^\s*\d{1,4}\s*[\-–—_\s]+", "", name).strip()
    name = re.sub(r"^\s*第\s*[一二三四五六七八九十百千万零〇两\d]+\s*章\s*[\-–—_\s：:]+", "", name).strip()
    name = re.sub(r"^\s*(?:Chapter|Ch(?:apt|ap)?\.?)\s*[IVXLCDM\d]+\s*[\-–—_\s：:]+", "", name, flags=re.I).strip()
    name = re.sub(r"\s+", " ", name).strip(" ._-—–：:")
    return name or str(fallback or "").strip()


def build_episode_subtitle_from_ch_dir(ch_dir: str, fallback: str = "", chapter_number: str = "", include_number: bool = False) -> str:
    """返回与章节文件夹一致的小标题；需要时加上章节号。"""
    title = _episode_subtitle_from_dirname(ch_dir, fallback=fallback)
    if include_number:
        number = str(chapter_number or "").strip()
        if number and title and not re.search(r"(?:第\s*)?\d{1,4}\s*章|\bChapter\s*\d+\b", title, flags=re.I):
            return f"{number} {title}".strip()
    return title


def _stable_chapter_title_cn_from_metadata(ch_dir: str) -> str:
    """从章节目录下 0_封面首页元信息.txt 读取稳定中文章名。

    该文件是封面/首页字段的权威来源，也用于下一章预告的中文标题；
    这样不会因为文件夹名是英文或翻译缓存失败，而把英文标题写进口播。
    """
    try:
        if not ch_dir:
            return ""
        loader = globals().get("load_cover_home_metadata_value")
        value = loader(ch_dir, "Chapter Title CN") if callable(loader) else ""
        value = clean_chapter_title_translation_text(value, fallback="")
        if value and contains_cjk_text(value):
            return value
    except Exception:
        pass
    return ""


def strip_chapter_number_for_speech_title(text: str) -> str:
    """口播里的“下一章”后不再重复第 N 章，只保留稳定中文小标题。"""
    raw = str(text or "").strip()
    if not raw:
        return ""
    raw = re.sub(r"^\s*第\s*[一二三四五六七八九十百千万零〇两\d]+\s*章\s*[:：\-–—_\s]*", "", raw).strip()
    raw = re.sub(r"^\s*(?:CHAPTER|Chapter|chapter|Ch\.?)\s*[IVXLCDM\d]+\s*[:：\-–—_\s]*", "", raw).strip()
    raw = re.sub(r"\s+", " ", raw).strip(" 。；;：:")
    return raw


def _compose_chapter_theme_with_cn(number: str, title_cn: str) -> str:
    title_cn = clean_chapter_title_translation_text(title_cn, fallback="")
    number = str(number or "").strip()
    if title_cn and contains_cjk_text(title_cn):
        return f"{number} {title_cn}".strip() if number else title_cn
    return ""


def build_chapter_theme_for_prompt_from_dir(ch: dict, idx_in_toc: int | None = None, ch_dir: str = "", fallback_title: str = "") -> str:
    """给当前/下一章提示词使用的主题。

    优先级：0_封面首页元信息.txt 的 Chapter Title CN > 中文翻译/中文文件夹名 > PDF 目录标题。
    文件夹名只在含中文时参与口播；英文文件夹名不再覆盖稳定中文章名。
    """
    title = str((ch or {}).get("title", "")).strip()
    meta = parse_chapter_title_metadata(title, idx_in_toc)
    number = meta.get("chapter_number") or ""
    stable_cn = _stable_chapter_title_cn_from_metadata(ch_dir)
    stable_theme = _compose_chapter_theme_with_cn(number, stable_cn)
    if stable_theme:
        return stable_theme
    folder_title = build_episode_subtitle_from_ch_dir(ch_dir, fallback=fallback_title or meta.get("title_clean") or title, chapter_number=number, include_number=True) if ch_dir else ""
    if folder_title and contains_cjk_text(folder_title):
        return folder_title
    return build_chapter_theme_for_prompt(ch, idx_in_toc)


def build_translated_chapter_theme_for_prompt(ch: dict, idx_in_toc: int | None = None, translated_title: str = "", ch_dir: str = "") -> str:
    """给提示词/下一章预告使用的章节名。

    下一章预告优先用下一章 `0_封面首页元信息.txt` 里的中文章名；
    若稳定文件不存在，再用本轮翻译结果。英文文件夹名只用于断点定位，不再直接写进口播。
    """
    title = str((ch or {}).get("title", "")).strip()
    meta = parse_chapter_title_metadata(title, idx_in_toc)
    number = meta.get("chapter_number") or ""
    stable_cn = _stable_chapter_title_cn_from_metadata(ch_dir)
    stable_theme = _compose_chapter_theme_with_cn(number, stable_cn)
    if stable_theme:
        return stable_theme
    clean_title = clean_chapter_title_translation_text(translated_title, fallback="")
    if clean_title and contains_cjk_text(clean_title):
        return f"{number} {clean_title}".strip() if number else clean_title
    folder_title = build_episode_subtitle_from_ch_dir(ch_dir, fallback="", chapter_number=number, include_number=True) if ch_dir else ""
    if folder_title and contains_cjk_text(folder_title):
        return folder_title
    # 兜底才允许使用 PDF 目录英文；这种情况说明稳定中文文件和翻译结果都不存在。
    return build_chapter_theme_for_prompt(ch, idx_in_toc)



def contains_cjk_text(text: str) -> bool:
    """判断文本中是否已经包含中文/日文/韩文字符。"""
    return bool(re.search(r"[\u3400-\u4dbf\u4e00-\u9fff]", str(text or "")))


def strip_edition_from_book_title(text: str) -> tuple[str, str]:
    """把书名里的版次拆出来，避免书名有时写成《xxx第六版》、有时写成《xxx》。
    返回：(去掉版次后的书名, 识别到的版次原文)。
    """
    raw = str(text or "").replace("\r\n", " ").replace("\r", " ").replace("\n", " ")
    raw = re.sub(r"\s+", " ", raw).strip(" \t'\"“”‘’")
    if not raw:
        return "", ""
    raw = re.sub(r"\.(?:pdf|epub|mobi|azw3|docx?)$", "", raw, flags=re.I).strip()
    detected = ""
    version_patterns = [
        r"《\s*(第[一二三四五六七八九十百千万零〇两0-9]+版)\s*》",
        r"[（(【\[]\s*(第[一二三四五六七八九十百千万零〇两0-9]+版)\s*[）)】\]]",
        r"[（(【\[]\s*((?:first|second|third|fourth|fifth|sixth|seventh|eighth|ninth|tenth|\d+(?:st|nd|rd|th)?)\s+edition)\s*[）)】\]]",
        r"(?:^|[\s_\-—–·,，])((?:first|second|third|fourth|fifth|sixth|seventh|eighth|ninth|tenth|\d+(?:st|nd|rd|th)?)\s+edition)(?=$|[\s_\-—–·,，])",
        r"(?:^|[\s_\-—–·,，])(第[一二三四五六七八九十百千万零〇两0-9]+版)(?=$|[\s_\-—–·,，])",
        r"[：:·\s_\-—–,，]+((?:first|second|third|fourth|fifth|sixth|seventh|eighth|ninth|tenth|\d+(?:st|nd|rd|th)?)\s+edition)$",
        r"[：:·\s_\-—–,，]*(第[一二三四五六七八九十百千万零〇两0-9]+版)$",
    ]
    cleaned = raw
    for pat in version_patterns:
        def _repl(m):
            nonlocal detected
            if not detected:
                detected = m.group(1).strip()
            return " "
        cleaned = re.sub(pat, _repl, cleaned, flags=re.I)
    cleaned = re.sub(r"\s+", " ", cleaned)
    cleaned = re.sub(r"\s*[-_—–·,，]+\s*$", "", cleaned)
    cleaned = cleaned.strip(" \t'\"“”‘’《》-—–_·,，.;；。")
    return cleaned or raw, detected


def clean_book_title_translation_text(text: str, fallback: str = "") -> str:
    """清理书名翻译结果：书名只保留书名本体，版次交给 Version 字段。"""
    cleaned = clean_chapter_title_translation_text(text, fallback=fallback)
    cleaned, _version = strip_edition_from_book_title(cleaned)
    return cleaned.strip(" \t'\"“”‘’《》") or str(fallback or "").strip()


def clean_chapter_title_translation_text(text: str, fallback: str = "") -> str:
    """清理章节名翻译结果，只保留一行中文标题。"""
    raw = str(text or "").replace("\r\n", "\n").replace("\r", "\n").strip()
    if not raw:
        return str(fallback or "").strip()
    # 去掉代码围栏、标签、解释性前缀和引号。
    raw = re.sub(r"^```[a-zA-Z0-9_-]*\s*", "", raw).strip()
    raw = re.sub(r"```$", "", raw).strip()
    lines = [ln.strip() for ln in raw.splitlines() if ln.strip()]
    candidates = []
    for ln in lines:
        ln = re.sub(r"^[-•*\d.、\s]+", "", ln).strip()
        ln = re.sub(r"^(?:中文章节名|章节名翻译|翻译|译名|中文标题|标题)\s*[：:]\s*", "", ln, flags=re.I).strip()
        ln = ln.strip(" \t'\"“”‘’《》")
        if not ln:
            continue
        # 避免模型输出解释句；优先选择较短且含中文的标题行。
        if contains_cjk_text(ln) and len(ln) <= 80:
            candidates.append(ln)
    if candidates:
        return candidates[0]
    first = lines[0].strip(" \t'\"“”‘’《》") if lines else ""
    first = re.sub(r"^(?:中文章节名|章节名翻译|翻译|译名|中文标题|标题)\s*[：:]\s*", "", first, flags=re.I).strip()
    return first or str(fallback or "").strip()




def clean_chapter_title_english_text(text: str, fallback: str = "") -> str:
    """清理英文章节名：只保留一行英文原题；中文或占位符不作为英文显示。"""
    raw = str(text or fallback or "").replace("\r\n", "\n").replace("\r", "\n").strip()
    if not raw:
        return ""
    raw = re.sub(r"^```[a-zA-Z0-9_-]*\s*", "", raw).strip()
    raw = re.sub(r"```$", "", raw).strip()
    lines = [ln.strip() for ln in raw.splitlines() if ln.strip()]
    candidates = []
    for ln in lines:
        ln = re.sub(r"^[-•*\d.、\s]+", "", ln).strip()
        ln = re.sub(r"^(?:英文章节名|章节英文名|章节名英文|英文标题|Chapter\s*Title(?:\s*EN|\s*English)?)\s*[：:=]\s*", "", ln, flags=re.I).strip()
        ln = ln.strip(" \t'\"“”‘’《》")
        if not ln:
            continue
        if contains_cjk_text(ln):
            continue
        if _is_placeholder_public_meta(ln) or _looks_garbled_text(ln):
            continue
        # 避免把作者、版次、书名误当成英文章节名。
        if re.search(r"\b(?:edition|author|authors|kandel|principles\s+of\s+neural\s+science)\b", ln, flags=re.I):
            continue
        if len(ln) <= 180 and re.search(r"[A-Za-z]", ln):
            candidates.append(ln)
    return candidates[0] if candidates else ""


def _score_complete_english_chapter_title(title: str) -> tuple[int, int, int, int]:
    """给英文章节名候选评分：优先完整、非截断、信息量更高的标题。"""
    t = clean_chapter_title_english_text(title)
    if not t:
        return (-9999, 0, 0, 0)
    words = re.findall(r"[A-Za-z][A-Za-z'-]*", t)
    word_count = len(words)
    # 目录完整标题通常比输出文件夹名更长；旧版文件夹曾 35 字符截断，不能反过来覆盖完整目录名。
    length_score = min(len(t), 180)
    space_score = 1 if " " in t else 0
    # 轻微惩罚明显不像完整英文标题的尾部片段，但不因此删除候选。
    tail = words[-1].lower() if words else ""
    suspicious_tail = 1 if tail in {"of", "the", "and", "or", "in", "with", "to", "from", "for"} else 0
    return (word_count, length_score, space_score, -suspicious_tail)


def choose_complete_chapter_title_english_text(*values: str, fallback: str = "") -> str:
    """从多个候选中选择最完整的英文章节名。

    目的：封面/首页必须显示完整英文章节名。旧版章节目录名可能被 safe_filename
    截成 35 个字符，不能用被截断的文件夹小标题覆盖 PDF 目录里的完整英文原题。
    """
    candidates: list[str] = []
    for value in list(values) + ([fallback] if fallback else []):
        cleaned = clean_chapter_title_english_text(value)
        if not cleaned:
            continue
        if cleaned not in candidates:
            candidates.append(cleaned)
    if not candidates:
        return ""
    return sorted(candidates, key=_score_complete_english_chapter_title, reverse=True)[0]

def build_chapter_title_translation_prompt(chapter_title: str, chapter_number: str = "", book_name: str = "", toc_text: str = "") -> str:
    """章节名翻译提示词：模板外置到 quanlan_prompt_fragments/chapter_title_translation.md。"""
    title = str(chapter_title or "").strip()
    if not title:
        return ""
    return render_prompt_fragment("chapter_title_translation.md", {
        "book_name": str(book_name or "").strip(),
        "chapter_number": str(chapter_number or "").strip(),
        "chapter_title": title,
        "toc_text": truncate_context(str(toc_text or ""), 3000),
    }, fallback="请把以下章节标题翻译成一行自然准确的中文，不要解释：\n{chapter_title}")

def get_chapter_title_translation_cache_path(ch_dir: str) -> str:
    return os.path.join(ch_dir, "0_章节名翻译.txt")


def load_cached_chapter_title_translation(ch_dir: str) -> str:
    path = get_chapter_title_translation_cache_path(ch_dir)
    if is_nonempty_file(path, min_bytes=2):
        cached = clean_chapter_title_translation_text(read_text_file(path), fallback="")
        # 旧版本曾在翻译失败时把英文原题写入缓存；这里直接忽略，避免下一章预告说英文。
        return cached if cached and contains_cjk_text(cached) else ""
    return ""


def save_cached_chapter_title_translation(ch_dir: str, translated_title: str) -> None:
    title = clean_chapter_title_translation_text(translated_title)
    if title:
        write_text_file(get_chapter_title_translation_cache_path(ch_dir), title + "\n")


def translate_chapter_title_for_prompt(
    chapter_title: str,
    chapter_number: str = "",
    book_name: str = "",
    ch_dir: str = "",
    engine: str = "",
    logger=None,
    check_cancel=None,
    grok_key: str = "",
    gemini_key: str = "",
    openai_key: str = "",
    chatshare_key: str = "",
    web_manual: bool = False,
    toc_text: str = "",
) -> str:
    """把 PDF 目录里的章节名翻译成中文；结果写入缓存，供断点续跑复用。"""
    original = str(chapter_title or "").strip()
    if not original:
        return ""
    cached = load_cached_chapter_title_translation(ch_dir) if ch_dir else ""
    if cached:
        return cached
    if contains_cjk_text(original):
        translated = clean_chapter_title_translation_text(original, original)
        if ch_dir:
            save_cached_chapter_title_translation(ch_dir, translated)
        return translated

    prompt = build_chapter_title_translation_prompt(original, chapter_number=chapter_number, book_name=book_name, toc_text=toc_text)
    if not str(prompt or "").strip():
        if logger:
            logger("🪶 章节名翻译提示词为空，已跳过额外翻译 API，直接使用原始标题。")
        return original
    if ch_dir:
        try:
            write_text_file(os.path.join(ch_dir, "0_章节名翻译提示词.txt"), prompt + "\n")
        except Exception:
            pass
    if web_manual:
        result = web_text_result_or_export(ch_dir or SCRIPT_DIR, "00_章节名翻译", prompt, engine, logger)
        if not result:
            return original
        translated = clean_chapter_title_translation_text(result, fallback="")
        if translated and contains_cjk_text(translated):
            if ch_dir:
                save_cached_chapter_title_translation(ch_dir, translated)
            if logger and translated != original:
                logger(f"🏷️ 章节名翻译：{original} → {translated}")
            return translated
        return original if contains_cjk_text(original) else ""
    result = ""
    try:
        result = generate_text_by_engine(
            engine,
            prompt,
            logger,
            check_cancel=check_cancel,
            grok_key=grok_key,
            gemini_key=gemini_key,
            openai_key=openai_key,
            chatshare_key=chatshare_key,
        )
    except Exception as e:
        if logger:
            logger(f"⚠️ 章节名翻译失败，暂用原始标题：{str(e)[:100]}")
    translated = clean_chapter_title_translation_text(result, fallback="")
    if translated and contains_cjk_text(translated):
        if ch_dir:
            save_cached_chapter_title_translation(ch_dir, translated)
        if logger and translated != original:
            logger(f"🏷️ 章节名翻译：{original} → {translated}")
        return translated
    return original if contains_cjk_text(original) else ""


def build_book_title_translation_prompt(book_title: str) -> str:
    """书名翻译提示词：模板外置到 quanlan_prompt_fragments/book_title_translation.md。"""
    title = str(book_title or "").strip()
    if not title:
        return ""
    return render_prompt_fragment("book_title_translation.md", {"book_title": title}, fallback="请把以下书名翻译成一行自然准确的中文，不要解释，不要保留版次：\n{book_title}")

def get_book_title_translation_cache_path(ch_dir: str) -> str:
    return os.path.join(ch_dir, "0_书名翻译.txt")


def load_cached_book_title_translation(ch_dir: str) -> str:
    path = get_book_title_translation_cache_path(ch_dir)
    if is_nonempty_file(path, min_bytes=2):
        return clean_book_title_translation_text(read_text_file(path))
    return ""


def save_cached_book_title_translation(ch_dir: str, translated_title: str) -> None:
    title = clean_book_title_translation_text(translated_title)
    if title:
        write_text_file(get_book_title_translation_cache_path(ch_dir), title + "\n")



def ensure_book_title_translation(
    book_title: str,
    ch_dir: str = "",
    engine: str = "",
    logger=None,
    check_cancel=None,
    grok_key: str = "",
    gemini_key: str = "",
    openai_key: str = "",
    chatshare_key: str = "",
    web_manual: bool = False,
) -> str:
    """确保书名有中文翻译；已有中文时直接复用。"""
    original_raw = str(book_title or "").strip()
    original, _detected_version = strip_edition_from_book_title(original_raw)
    if not original:
        return ""
    cached = load_cached_book_title_translation(ch_dir) if ch_dir else ""
    if cached:
        return cached
    if contains_cjk_text(original):
        translated = clean_book_title_translation_text(original, original)
        if ch_dir:
            save_cached_book_title_translation(ch_dir, translated)
        return translated
    prompt = build_book_title_translation_prompt(original)
    if ch_dir and prompt:
        try:
            write_text_file(os.path.join(ch_dir, "0_书名翻译提示词.txt"), prompt + "\n")
        except Exception:
            pass
    result = ""
    try:
        if web_manual:
            result = web_text_result_or_export(ch_dir or SCRIPT_DIR, "00_书名翻译", prompt, engine, logger)
        else:
            result = generate_text_by_engine(
                engine,
                prompt,
                logger,
                check_cancel=check_cancel,
                grok_key=grok_key,
                gemini_key=gemini_key,
                openai_key=openai_key,
                chatshare_key=chatshare_key,
            )
    except Exception as e:
        if logger:
            logger(f"⚠️ 书名翻译失败，暂用原始书名：{str(e)[:100]}")
    translated = clean_book_title_translation_text(result, fallback=original)
    if ch_dir and translated:
        save_cached_book_title_translation(ch_dir, translated)
    if logger and translated and translated != original:
        logger(f"📚 书名翻译：{original} → {translated}")
    return translated or original


def build_cover_home_metadata_contract(book_title: str, book_title_cn: str, version_text: str, author_line: str, chapter_number: str, chapter_title: str, chapter_title_cn: str) -> str:
    """给脚本生成模型的硬约束：四张平台首图必须显式包含同一组元信息。"""
    author_value = str(author_line or "").strip()
    parts = [
        "A1/A2/A01/A02 平台封面与首页元信息硬要求（必须遵守）：",
        "1. 必须输出四个固定页槽：A1 微信封面 3:4、A2 微信首页 9:16、A01 B站封面 4:3、A02 B站首页 16:9。",
        "2. A1 是唯一真实生图 prompt：生成一张整章内容总结无字 Master Background；A2/A01/A02 只能写复用同一母图并由程序裁切，不得写独立画面、独立风格或新增元素。",
        "3. 四张图使用同一张 Master Background，程序后处理裁切为 A1=3:4、A2=9:16、A01=4:3、A02=16:9；raw image 不得绘制公共文字，由程序后处理。",
        "4. 四张图的 Text Overlay Spec 必须显式保留以下字段，字段名不要改写：",
        "Brand: 全澜脑科学",
        f"Book Title: {book_title}",
        f"Book Title CN: {book_title_cn}",
        f"Version: {version_text}",
        f"Author: {author_value}",
        f"Chapter Number: {chapter_number}",
        f"Chapter Title: {chapter_title}",
        f"Chapter Title EN: {chapter_title}",
        f"Chapter Title CN: {chapter_title_cn}",
        "5. Author 字段只能使用 PDF 前封面/title page 识别到的真实作者；如果没有识别到作者，就保持为空，不得写‘未提供’。",
        "6. 四张图的遮罩必须是 full_canvas 全屏蒙版，不允许中间方块；显示顺序固定为：品牌、中文书名、英文书名、版本、作者、章节序号、中文章节名、英文章节名。",
        "7. 封面/首图最终显示的 Chapter Title CN / EN 以章节目录下的 0_封面首页元信息.txt 为权威来源；不得从章节文件夹名、分镜图片目录、绘图提示词、短视频总结、导读脚本文件名等流程文本中猜标题。",
    ]
    return "\n".join(parts).strip()


def sync_short_video_summary_title_with_folder(path: str, folder_subtitle: str, logger=None) -> None:
    """已有短视频总结文件存在时，也把小标题同步为章节文件夹名。"""
    title = str(folder_subtitle or "").strip()
    if not path or not title or not is_nonempty_file(path, min_bytes=5):
        return
    try:
        raw = read_text_file(path)
        if not raw.strip():
            return
        if re.search(r"^\s*(?:中文章节名|章节名|小标题)\s*[：:].*$", raw, flags=re.M):
            new = re.sub(r"^\s*(?:中文章节名|章节名|小标题)\s*[：:].*$", f"中文章节名：{title}", raw, count=1, flags=re.M)
        else:
            new = f"中文章节名：{title}\n" + raw.lstrip()
        if "视频号标题" not in new:
            summary_value = _extract_labeled_value_from_text(new, ["短视频总结", "总结", "内容总结"])
            video_title, video_desc = build_wechat_channels_copy_from_summary_output(
                new,
                episode_subtitle=title,
                summary=summary_value,
            )
            insert_lines = []
            if video_title:
                insert_lines.append(f"视频号标题：{video_title}")
            if video_desc:
                insert_lines.append(f"视频号简介：{video_desc}")
            if insert_lines:
                new = re.sub(r"(中文章节名\s*[：:].*\n)", r"\1" + "\n".join(insert_lines) + "\n", new, count=1)
        if new != raw:
            write_text_file(path, new)
            if logger:
                logger(f"🔒 已按章节文件夹同步每集小标题并补充视频号发布字段：{title}")
    except Exception:
        pass


def clean_short_video_summary_text(text: str, chapter_title_cn: str = "", original_title: str = "", max_chars: int = 120) -> tuple[str, str]:
    """清理短视频总结模型输出，返回（中文章节名，150字左右总结）。"""
    raw = str(text or "").replace("\r\n", "\n").replace("\r", "\n").strip()
    raw = re.sub(r"```[a-zA-Z0-9_-]*", "", raw).replace("```", "").strip()
    title = clean_chapter_title_translation_text(chapter_title_cn, fallback=original_title)
    summary = ""
    for ln in raw.splitlines():
        line = ln.strip()
        if not line:
            continue
        if re.match(r"^(?:中文章节名|章节名|标题|译名)\s*[：:]", line):
            value = re.sub(r"^(?:中文章节名|章节名|标题|译名)\s*[：:]\s*", "", line).strip()
            if value:
                title = clean_chapter_title_translation_text(value, fallback=title)
            continue
        if re.match(r"^(?:视频号标题|发布标题|标题|视频号简介|发布简介|视频简介)\s*[：:]", line):
            continue
        if re.match(r"^(?:短视频总结|总结|内容总结|视频总结|简介)\s*[：:]", line):
            value = re.sub(r"^(?:短视频总结|总结|内容总结|视频总结|简介)\s*[：:]\s*", "", line).strip()
            if value:
                summary += value
            continue
        # 如果模型只输出了一段正文，作为总结处理；跳过明显解释/要求复述。
        if not re.search(r"^(?:要求|输出|说明|以下|请注意)\b", line):
            summary += line
    summary = re.sub(r"\s+", "", summary).strip(" ，,。；;：:\n\t")
    # 删除常见夸张/营销动作，不改事实内容。
    for pat in [
        r"欢迎关注[^。.!！?？]*[。.!！?？]?",
        r"请关注[^。.!！?？]*[。.!！?？]?",
        r"点赞[^。.!！?？]*[。.!！?？]?",
        r"转发[^。.!！?？]*[。.!！?？]?",
    ]:
        summary = re.sub(pat, "", summary)
    if max_chars and len(summary) > max_chars:
        cut = summary[:max_chars]
        last_punct = max(cut.rfind("。"), cut.rfind("！"), cut.rfind("？"), cut.rfind("；"))
        if last_punct >= 55:
            cut = cut[:last_punct + 1]
        summary = cut.rstrip("，,；;：:")
    if summary and summary[-1] not in "。！？；":
        summary += "。"
    return title, summary


def _extract_labeled_value_from_text(text: str, labels: list[str]) -> str:
    raw = str(text or "").replace("\r\n", "\n").replace("\r", "\n")
    label_re = "|".join(re.escape(x) for x in labels)
    m = re.search(rf"^\s*(?:{label_re})\s*[：:]\s*(.+?)\s*$", raw, flags=re.M)
    return (m.group(1).strip() if m else "")


def _clean_wechat_channels_title(text: str, chapter_number: str = "", fallback_title: str = "") -> str:
    title = re.sub(r"\s+", " ", str(text or "")).strip(" \t\n\r。；;，,")
    title = re.sub(r"^(?:视频号标题|标题)\s*[：:]\s*", "", title).strip()
    title = re.split(r"[。；;！!?？]\s*", title)[0].strip()
    title = re.sub(r"(?i)^(?:chapter\s*)?\d+\s+", "", title).strip()
    title = re.sub(r"第\s*(\d+)\s*章", r"第\1章", title)
    if re.search(r"[A-Za-z]{4,}", title) and not contains_cjk_text(title):
        title = ""
    for bad in ["核心", "深度", "底层逻辑", "揭秘", "颠覆", "震撼", "最强", "天花板", "真正的答案"]:
        title = title.replace(bad, "")
    title = re.sub(r"\s+", "", title)
    if not title:
        title = str(fallback_title or "").strip()
    number = str(chapter_number or "").strip()
    n = re.search(r"\d+", number)
    if n and title and not re.match(rf"^(?:{re.escape(number)}|{n.group(0)}|第\s*{n.group(0)}\s*章)", title):
        title = f"{n.group(0)} {title}"
    if len(title) > 32:
        cut = title[:32]
        for sep in ["，", "：", ":", "？", "?", "、"]:
            pos = cut.rfind(sep)
            if pos >= 12:
                cut = cut[:pos]
                break
        title = cut.rstrip("，,：:、？?")
    return title.strip()


def _clean_wechat_channels_description(text: str, summary: str = "", max_chars: int = 90) -> str:
    desc = str(text or "").strip()
    desc = re.sub(r"^(?:视频号简介|简介|描述)\s*[：:]\s*", "", desc).strip()
    if not desc:
        desc = str(summary or "").strip()
    for pat in [
        r"欢迎关注[^。.!！?？]*[。.!！?？]?",
        r"请关注[^。.!！?？]*[。.!！?？]?",
        r"点赞[^。.!！?？]*[。.!！?？]?",
        r"转发[^。.!！?？]*[。.!！?？]?",
        r"分享给[^。.!！?？]*[。.!！?？]?",
    ]:
        desc = re.sub(pat, "", desc)
    desc = re.sub(r"\s+", "", desc).strip("，,；;：:")
    if max_chars and len(desc) > max_chars:
        cut = desc[:max_chars]
        last = max(cut.rfind("。"), cut.rfind("？"), cut.rfind("！"), cut.rfind("；"))
        if last >= 45:
            cut = cut[:last + 1]
        desc = cut.rstrip("，,；;：:")
    if desc and desc[-1] not in "。！？；":
        desc += "。"
    return desc


def build_wechat_channels_copy_from_summary_output(raw_text: str, *, chapter_number: str = "", episode_subtitle: str = "", summary: str = "") -> tuple[str, str]:
    """从短视频总结模型输出中提取/生成微信视频号标题和简介。"""
    raw = str(raw_text or "")
    title_raw = _extract_labeled_value_from_text(raw, ["视频号标题", "标题", "发布标题"])
    desc_raw = _extract_labeled_value_from_text(raw, ["视频号简介", "简介", "发布简介", "视频简介"])
    fallback_title = str(episode_subtitle or "").strip()
    title = _clean_wechat_channels_title(title_raw, chapter_number=chapter_number, fallback_title=fallback_title)
    desc = _clean_wechat_channels_description(desc_raw, summary=summary, max_chars=90)
    return title, desc


def build_short_video_summary_prompt(source_text: str, chapter_title_cn: str, original_title: str = "", chapter_number: str = "", book_name: str = "", folder_subtitle: str = "") -> str:
    """生成短视频总结文件的提示词：模板外置到 quanlan_prompt_fragments/short_video_summary.md。"""
    source = truncate_context(str(source_text or ""), 8000)
    if not source.strip():
        return ""
    # 每集小标题以章节文件夹名为准，模型不得另起标题。
    title = str(folder_subtitle or "").strip() or clean_chapter_title_translation_text(chapter_title_cn, fallback=original_title)
    return render_prompt_fragment("short_video_summary.md", {
        "book_name": str(book_name or "").strip(),
        "chapter_number": str(chapter_number or "").strip(),
        "original_title": str(original_title or "").strip(),
        "chapter_title_cn": title,
        "episode_subtitle": title,
        "source_text": source,
    }, fallback="请基于章节内容输出两行：中文章节名：{episode_subtitle}\n短视频总结：...\n\n{source_text}")

def save_short_video_summary_file(script_path: str, chapter_title_cn: str, summary_text: str, original_title: str = "", logger=None, folder_subtitle: str = "", chapter_number: str = "") -> str:
    """保存短视频总结文件；同时输出微信视频号发布标题/简介。"""
    forced_title = str(folder_subtitle or "").strip() or build_episode_subtitle_from_ch_dir(os.path.dirname(script_path), fallback="")
    title, summary = clean_short_video_summary_text(summary_text, chapter_title_cn=chapter_title_cn, original_title=original_title)
    if forced_title:
        title = forced_title
    if not title:
        title = clean_chapter_title_translation_text(chapter_title_cn, fallback=original_title)
    if not summary:
        return ""
    video_title, video_desc = build_wechat_channels_copy_from_summary_output(
        summary_text,
        chapter_number=chapter_number,
        episode_subtitle=title,
        summary=summary,
    )
    path = get_short_video_summary_text_path(script_path)
    lines = []
    if title:
        lines.append(f"中文章节名：{title}")
    if video_title:
        lines.append(f"视频号标题：{video_title}")
    if video_desc:
        lines.append(f"视频号简介：{video_desc}")
    lines.append(f"短视频总结：{summary}")
    write_text_file(path, "\n".join(lines).strip() + "\n")
    if logger:
        logger(f"📝 视频号发布文案/短视频总结已保存：{os.path.basename(path)}")
    return path



def ensure_short_video_summary_file(
    script_path: str,
    chapter_title_cn: str,
    original_title: str = "",
    chapter_number: str = "",
    book_name: str = "",
    source_text: str = "",
    engine: str = "",
    logger=None,
    check_cancel=None,
    grok_key: str = "",
    gemini_key: str = "",
    openai_key: str = "",
    chatshare_key: str = "",
    web_manual: bool = False,
    ch_dir: str = "",
    folder_subtitle: str = "",
) -> str:
    """确保新增短视频总结文件存在；优先用章节正文，其次用台词作为来源。"""
    out_path = get_short_video_summary_text_path(script_path)
    folder_subtitle = str(folder_subtitle or "").strip() or build_episode_subtitle_from_ch_dir(ch_dir or os.path.dirname(script_path), fallback="")
    if is_nonempty_file(out_path, min_bytes=20):
        sync_short_video_summary_title_with_folder(out_path, folder_subtitle, logger=logger)
        return out_path
    source = str(source_text or "").strip()
    if not source:
        voice_path = get_voiceover_text_path(script_path)
        source = read_text_file(voice_path) if is_nonempty_file(voice_path) else read_text_file(script_path)
    prompt = build_short_video_summary_prompt(source, chapter_title_cn, original_title=original_title, chapter_number=chapter_number, book_name=book_name, folder_subtitle=folder_subtitle)
    if not prompt.strip():
        return ""
    if ch_dir:
        try:
            write_text_file(os.path.join(ch_dir, "0_短视频总结生成提示词.txt"), prompt + "\n")
        except Exception:
            pass
    result = ""
    if web_manual:
        result = web_text_result_or_export(ch_dir or os.path.dirname(script_path), "03_短视频总结", prompt, engine, logger)
        if not result:
            return ""
    else:
        try:
            result = generate_text_by_engine(
                engine,
                prompt,
                logger,
                check_cancel=check_cancel,
                grok_key=grok_key,
                gemini_key=gemini_key,
                openai_key=openai_key,
                chatshare_key=chatshare_key,
            )
        except Exception as e:
            if logger:
                logger(f"⚠️ 短视频总结生成失败：{str(e)[:100]}")
            return ""
    return save_short_video_summary_file(script_path, chapter_title_cn, result, original_title=original_title, logger=logger, folder_subtitle=folder_subtitle, chapter_number=chapter_number)


def build_raw_script_title_header(chapter_number: str, original_title: str, translated_title: str, english_title: str = "") -> str:
    """写在“完整脚本原稿”最开头的章节名翻译信息；同时保留英文原题，供封面/首页后处理显示。"""
    number = str(chapter_number or "").strip()
    original = str(original_title or "").strip()
    translated = clean_chapter_title_translation_text(translated_title, fallback=original)
    english = clean_chapter_title_english_text(english_title or original)
    lines = ["【章节名翻译】"]
    if number:
        lines.append(f"章节序号：{number}")
    if original:
        lines.append(f"原始章节名：{original}")
    if translated:
        lines.append(f"中文章节名：{translated}")
    if english:
        lines.append(f"英文章节名：{english}")
    return "\n".join(lines).strip() + "\n\n"


def _ensure_raw_title_header_english_line(raw: str, original_title: str = "", english_title: str = "") -> str:
    """已有章节名翻译头缺少英文章节名时，补一行，避免首页/封面解析不到英文。"""
    text = str(raw or "").lstrip()
    english = clean_chapter_title_english_text(english_title or original_title)
    if not english or not re.match(r"^【章节名翻译】", text):
        return text if text.endswith("\n") else text + "\n"
    header_end = re.search(r"\n\s*\n", text)
    end = header_end.start() if header_end else min(len(text), 600)
    header = text[:end]
    if re.search(r"英文章节名\s*[：:=]", header):
        return text if text.endswith("\n") else text + "\n"
    m = re.search(r"(^中文章节名\s*[：:=].*$)", header, flags=re.M)
    insert_at = m.end() if m else len(header)
    patched = text[:insert_at] + f"\n英文章节名：{english}" + text[insert_at:]
    return patched if patched.endswith("\n") else patched + "\n"


def prepend_raw_script_title_header(raw_script_text: str, chapter_number: str, original_title: str, translated_title: str, english_title: str = "") -> str:
    """确保完整脚本原稿开头有章节名翻译，不重复添加；已有头部会补齐英文章节名。"""
    raw = str(raw_script_text or "").lstrip()
    if re.match(r"^【章节名翻译】", raw):
        return _ensure_raw_title_header_english_line(raw, original_title=original_title, english_title=english_title)
    return build_raw_script_title_header(chapter_number, original_title, translated_title, english_title=english_title) + raw + ("\n" if raw and not raw.endswith("\n") else "")


def ensure_raw_script_title_header_file(raw_backup_path: str, chapter_number: str, original_title: str, translated_title: str, english_title: str = "", logger=None) -> None:
    """断点续跑时，给已有完整脚本原稿补上章节名翻译头，并补齐英文章节名。"""
    if not raw_backup_path or not is_nonempty_file(raw_backup_path, min_bytes=20):
        return
    text = read_text_file(raw_backup_path)
    patched = prepend_raw_script_title_header(text, chapter_number, original_title, translated_title, english_title=english_title)
    if patched != text:
        write_text_file(raw_backup_path, patched)
        if logger:
            logger(f"🏷️ 已在完整脚本原稿开头补充章节名翻译/英文章节名：{os.path.basename(raw_backup_path)}")


def find_next_scriptable_chapter_index(toc: list, current_index: int) -> int | None:
    """寻找下一个真正正文章节；跳过 Part IV、Glossary、References 等目录层级或工具项。"""
    for j in range(int(current_index) + 1, len(toc or [])):
        if is_scriptable_chapter_title((toc[j] or {}).get("title", "")):
            return j
    return None


def find_next_outline_boundary_page(toc: list, current_index: int, current_page: int, default_span: int = 20) -> int:
    """切分章节 PDF 的结束边界。

    关键修复：PDF 书签常包含大量章内小节。旧逻辑会把“当前章节后的第一个更大页码书签”
    当作下一章边界，导致第 13 章这类有小节书签的章节只切出 1 页。

    新逻辑：优先寻找后续第一个“同级或更高层级”的书签页作为边界，跳过章内子书签；
    只有在书签没有层级信息时，才退回到第一个更大页码。找不到边界时使用 default_span。
    返回值仍是 1-based 的 exclusive end page：例如 start=318、boundary=346 表示切 318..345。
    """
    try:
        cur_page = int(current_page)
    except Exception:
        cur_page = 1
    try:
        cur_index = int(current_index)
    except Exception:
        cur_index = 0
    try:
        current_item = (toc or [])[cur_index] or {}
    except Exception:
        current_item = {}
    try:
        cur_level = int(current_item.get("level") or 0)
    except Exception:
        cur_level = 0

    fallback_first_greater = 0
    for j in range(cur_index + 1, len(toc or [])):
        item = (toc[j] or {})
        try:
            p = int(item.get("page") or 0)
        except Exception:
            continue
        if p <= cur_page:
            continue
        if not fallback_first_greater:
            fallback_first_greater = p
        try:
            lvl = int(item.get("level") or 0)
        except Exception:
            lvl = 0
        # 有层级信息时，跳过章内小节；同级/更高层级才是章节边界。
        if cur_level and lvl and lvl > cur_level:
            continue
        return p

    # 没有层级信息的旧 PDF 书签：保留原兼容逻辑。
    if not cur_level and fallback_first_greater:
        return fallback_first_greater
    return cur_page + int(default_span)


# ================== 下一章真实内容校验：用于严格“承上启下” ==================
def get_next_chapter_context_cache_path(ch_dir: str) -> str:
    return os.path.join(ch_dir, "0_下一章真实内容摘录.md")


def get_next_chapter_guidance_cache_path(ch_dir: str) -> str:
    return os.path.join(ch_dir, "0_下一章真实内容预告校验.json")


def clean_next_chapter_source_excerpt(text: str, max_chars: int = NEXT_CHAPTER_CONTEXT_CHAR_LIMIT) -> str:
    """清理下一章原文摘录，只保留给模型判断下章预告所需的正文。"""
    raw = str(text or "").replace("\r\n", "\n").replace("\r", "\n")
    raw = re.sub(r"!\[[^\]]*\]\([^\)]*\)", "", raw)
    raw = re.sub(r"<[^>]{1,120}>", " ", raw)
    raw = re.sub(r"\n{3,}", "\n\n", raw).strip()
    return truncate_context(raw, max_chars)


NEXT_CHAPTER_PDF_CONTEXT_CHAR_LIMIT = int(os.environ.get("QUANLAN_NEXT_PDF_CONTEXT_CHAR_LIMIT", "6000"))
NEXT_CHAPTER_PDF_UPLOAD_FILENAME = "next_chapter_for_llm.pdf"


def get_next_chapter_pdf_path(ch_dir: str) -> str:
    """下一章 PDF 直传缓存文件路径。"""
    return os.path.join(ch_dir, NEXT_CHAPTER_PDF_UPLOAD_FILENAME)


def build_next_chapter_pdf_context_prompt(next_theme: str, toc_text: str = "") -> str:
    """用于 PDF 附件兜底模式的极简下一章内容摘录提示词。"""
    toc = truncate_context(toc_text or "", 12000)
    return f"""请直接阅读随本请求上传的下一章节 PDF 附件，只依据附件内容输出用于当前章节结尾预告的事实材料。不要使用常识补全，不要编造机制、脑区、实验、疾病、生活例子或因果关系。

输出必须包含两个区块：

【下一章事实预告JSON】
{{
  "next_theme": "{next_theme}",
  "transition_bridge": "用一句中文说明它如何从当前章节结尾自然过渡到下一章；依据不足则留空",
  "mechanism_preview": "用一句中文概括附件中真实支持的下一章核心问题、规律或机制；没有足够依据则留空",
  "allowed_bridge_question": "用一个中文开放式问题作为结尾引子；必须受附件内容直接支持；依据不足则留空",
  "relevance_example": "如附件明确提供具体例子，可写一个短例子；附件无依据则留空",
  "evidence_terms": ["只写附件中出现或直接支持的关键词，最多8个"],
  "forbidden_claims": ["列出容易被误写、但附件没有支持的推断，最多5个"]
}}

【下一章真实内容摘录】
用中文整理附件中与下一章主题、关键机制、核心证据、科学边界、可用于承上启下的开放问题和禁止误写的无依据推断。保持事实密度，不写长篇讲解，不写标题党，不加入附件外内容。总长度控制在6000字以内。

程序识别出的下一正文章节：{next_theme}

完整目录信息，仅用于定位章节边界：
{toc}
""".strip()


def build_next_chapter_local_markdown_context_prompt(next_theme: str, local_markdown: str, toc_text: str = "") -> str:
    """用于本地 Markdown 解析模式的下一章内容摘录提示词；模板外置。"""
    return render_prompt_fragment("next_chapter_local_context.md", {
        "next_theme": str(next_theme or "下一章").strip() or "下一章",
        "toc_text": truncate_context(toc_text or "", 12000),
        "source_text": truncate_context(local_markdown or "", NEXT_CHAPTER_PDF_CONTEXT_CHAR_LIMIT),
    }, fallback="请只依据下一章本地解析内容提取事实材料，不要编造。\n下一章：{next_theme}\n{source_text}")

def parse_next_chapter_pdf_context_output(text: str, fallback_theme: str = "") -> tuple[dict, str]:
    """解析 PDF 直读返回的下一章 JSON guidance 和正文摘录。"""
    raw = str(text or "").replace("\r\n", "\n").replace("\r", "\n").strip()
    guidance = parse_next_chapter_guidance_json(raw, fallback_theme=fallback_theme)
    excerpt = raw
    m = re.search(r"【\s*下一章真实内容摘录\s*】\s*([\s\S]+)$", raw)
    if m:
        excerpt = m.group(1).strip()
    else:
        # 避免把 JSON 当作大段原文反复塞进后续提示词。
        excerpt = re.sub(r"【\s*下一章事实预告JSON\s*】\s*\{[\s\S]*?\}\s*", "", raw).strip()
    excerpt = clean_next_chapter_source_excerpt(excerpt, NEXT_CHAPTER_PDF_CONTEXT_CHAR_LIMIT)
    return guidance, excerpt


def extract_next_guidance_from_context_text(text: str, fallback_theme: str = "") -> dict:
    """从缓存的下一章 PDF 直读文本中复原 guidance，避免再调用一次校验 API。"""
    guidance, _excerpt = parse_next_chapter_pdf_context_output(text, fallback_theme=fallback_theme)
    return guidance


def save_next_chapter_pdf_guidance_to_cache(ch_dir: str, guidance: dict) -> None:
    """PDF 直读已产生 guidance 时，同时落到下一章目录，便于复用。"""
    if not ch_dir or not guidance:
        return
    try:
        save_next_chapter_guidance_cache(ch_dir, guidance)
    except Exception:
        pass


def prepare_next_chapter_markdown_context(
    *,
    pdf_path: str,
    toc: list,
    out_dir: str,
    next_idx_in_toc: int | None,
    logger=None,
    allow_mineru_parse: bool = False,
    direct_pdf_to_llm: bool = True,
    engine: str = "",
    toc_text: str = "",
    check_cancel=None,
    grok_key: str = "",
    gemini_key: str = "",
    openai_key: str = "",
    chatshare_key: str = "",
    web_manual: bool = False,
) -> tuple[str, str]:
    """
    同步准备下一正文章节的真实内容摘录。
    当前流程会先切分下一章 PDF，再本地解析为 Markdown；本地解析失败时只保守使用下一章标题，禁止 PDF 附件直传。
    返回 (下一章原文摘录, 下一章输出目录)。失败时返回空摘录，但不会中断当前章节生成。
    """
    if next_idx_in_toc is None or not toc or next_idx_in_toc < 0 or next_idx_in_toc >= len(toc):
        return "", ""
    next_ch = toc[next_idx_in_toc]
    next_title = str((next_ch or {}).get("title", "")).strip()
    if not next_title:
        return "", ""
    try:
        next_page = int((next_ch or {}).get("page") or 0)
    except Exception:
        next_page = 0
    if next_page <= 0:
        if logger:
            logger("⚠️ 下一章缺少有效页码，无法切分下一章 PDF；结尾只会使用下一章标题。")
        return "", ""

    next_meta = parse_chapter_title_metadata(next_title, next_idx_in_toc)
    next_dir = resolve_chapter_output_dir(out_dir, next_title, next_idx_in_toc, next_meta, logger=logger)
    os.makedirs(next_dir, exist_ok=True)
    current_cache_path = get_next_chapter_context_cache_path(next_dir)

    # 如果下一章目录里已有摘录缓存，直接复用，避免重复解析和重复调用模型。
    if is_nonempty_file(current_cache_path):
        text = clean_next_chapter_source_excerpt(read_text_file(current_cache_path), NEXT_CHAPTER_PDF_CONTEXT_CHAR_LIMIT)
        if text:
            if logger:
                logger(f"✅ 已读取下一章摘录缓存：{os.path.basename(current_cache_path)}")
            return text, next_dir

    if not pdf_path or not os.path.exists(pdf_path):
        if logger:
            logger("⚠️ 找不到原 PDF，无法准备下一章真实内容；结尾只会使用下一章标题。")
        return "", next_dir

    pdf_attachment_fallback_available = False
    if logger:
        logger("📄 下一章预告也只使用本地 Markdown 解析；禁止上传下一章 PDF 附件。")

    next_boundary_page = find_next_outline_boundary_page(toc, next_idx_in_toc, next_page, default_span=20)
    # 不能再把真实章节边界强制截成 20 页；长章节会被截断，后续摘要缺内容。
    next_end_page = next_boundary_page if next_boundary_page > next_page else next_page + 20
    next_pdf_path = get_next_chapter_pdf_path(next_dir)
    if not ensure_chapter_pdf_for_llm(pdf_path, next_pdf_path, next_page, next_end_page, logger):
        if logger:
            logger("⚠️ 下一章 PDF 切分失败，无法本地解析或直传给文本模型；结尾只会使用下一章标题。")
        return "", next_dir

    next_local_md = extract_chapter_pdf_markdown(next_pdf_path, os.path.join(next_dir, "parsed_content.md"), original_start_page=next_page, logger=logger)
    next_theme_text = build_chapter_theme_for_prompt_from_dir(next_ch, next_idx_in_toc, next_dir)
    if next_local_md:
        prompt = build_next_chapter_local_markdown_context_prompt(next_theme_text, next_local_md, toc_text=toc_text)
        try:
            write_text_file(os.path.join(next_dir, "0_下一章本地Markdown摘录提示词.txt"), prompt + "\n")
        except Exception:
            pass
        if web_manual:
            if logger:
                logger("📄 已为下一章导出本地 Markdown 摘录提示词；网页手动模式下无需上传下一章 PDF。")
            return "", next_dir
        if logger:
            logger(f"📄 正在用下一章本地 Markdown 获取真实内容摘录：{next_theme_text}")
        result = generate_text_by_engine(
            engine,
            prompt,
            logger,
            check_cancel=check_cancel,
            grok_key=grok_key,
            gemini_key=gemini_key,
            openai_key=openai_key,
            chatshare_key=chatshare_key,
        )
        guidance, excerpt = parse_next_chapter_pdf_context_output(result, fallback_theme=next_theme_text)
        if excerpt:
            cache_text = ""
            try:
                if guidance and guidance.get("has_verified_source"):
                    cache_text += "【下一章事实预告JSON】\n" + json.dumps(guidance, ensure_ascii=False, indent=2) + "\n\n"
                cache_text += "【下一章真实内容摘录】\n" + excerpt.strip() + "\n"
                write_text_file(current_cache_path, cache_text)
                save_next_chapter_pdf_guidance_to_cache(next_dir, guidance)
            except Exception:
                pass
            if logger:
                logger("✅ 下一章本地解析内容已准备完成，当前章节结尾将按下一章真实内容预告。")
            return clean_next_chapter_source_excerpt(cache_text or excerpt, NEXT_CHAPTER_PDF_CONTEXT_CHAR_LIMIT), next_dir
        if logger:
            logger("⚠️ 下一章本地 Markdown 没有返回可用摘录；不会上传 PDF，结尾只保守使用下一章标题。")

    if not pdf_attachment_fallback_available:
        if logger:
            logger("⚠️ 下一章本地解析失败；安全策略禁止 PDF 附件上传，结尾只会使用下一章标题。")
        return "", next_dir

    return "", next_dir

def build_next_chapter_guidance_prompt(next_theme: str, next_source_text: str, toc_text: str = "") -> str:
    """生成下一章预告事实校验提示词；模板外置。"""
    src = clean_next_chapter_source_excerpt(next_source_text, NEXT_CHAPTER_CONTEXT_CHAR_LIMIT)
    if not src:
        return ""
    return render_prompt_fragment("next_chapter_guidance.md", {
        "next_theme": str(next_theme or "下一章").strip() or "下一章",
        "toc_text": truncate_context(toc_text or "", 12000),
        "source_text": src,
    }, fallback="请只依据下一章真实内容输出 JSON 事实校验，不要编造。\n下一章：{next_theme}\n{source_text}")

def parse_next_chapter_guidance_json(text: str, fallback_theme: str = "") -> dict:
    """解析下一章预告校验 JSON；失败时返回安全兜底。"""
    fallback = {
        "next_theme": str(fallback_theme or "下一章").strip() or "下一章",
        "transition_bridge": "",
        "mechanism_preview": "",
        "allowed_bridge_question": "",
        "relevance_example": "",
        "evidence_terms": [],
        "forbidden_claims": [],
        "has_verified_source": False,
    }
    raw = str(text or "").strip()
    if not raw:
        return fallback
    raw = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.I).strip()
    raw = re.sub(r"```$", "", raw).strip()
    m = re.search(r"\{[\s\S]*\}", raw)
    if m:
        raw = m.group(0)
    try:
        data = json.loads(raw)
    except Exception:
        data = {}
    if not isinstance(data, dict):
        return fallback
    out = dict(fallback)
    theme = str(data.get("next_theme") or fallback_theme or "").strip()
    bridge = str(data.get("transition_bridge") or "").strip()
    preview = str(data.get("mechanism_preview") or "").strip()
    question = str(data.get("allowed_bridge_question") or "").strip()
    example = str(data.get("relevance_example") or "").strip()
    terms = data.get("evidence_terms") or []
    forbidden = data.get("forbidden_claims") or []
    if not isinstance(terms, list):
        terms = [str(terms)] if terms else []
    if not isinstance(forbidden, list):
        forbidden = [str(forbidden)] if forbidden else []
    terms = [str(x).strip() for x in terms if str(x).strip()][:8]
    forbidden = [str(x).strip() for x in forbidden if str(x).strip()][:5]
    out.update({
        "next_theme": theme or out["next_theme"],
        "transition_bridge": re.sub(r"[\n\r]+", " ", bridge).strip(" 。；;"),
        "mechanism_preview": re.sub(r"[\n\r]+", " ", preview).strip(" 。；;"),
        "allowed_bridge_question": re.sub(r"[\n\r]+", " ", question).strip(" 。；;！？?"),
        "relevance_example": re.sub(r"[\n\r]+", " ", example).strip(" 。；;"),
        "evidence_terms": terms,
        "forbidden_claims": forbidden,
        "has_verified_source": bool(bridge or preview or question or example or terms),
    })
    return out


def load_next_chapter_guidance_cache(ch_dir: str) -> dict:
    path = get_next_chapter_guidance_cache_path(ch_dir)
    if is_nonempty_file(path, min_bytes=5):
        try:
            data = json.loads(read_text_file(path))
            if isinstance(data, dict):

                return data
        except Exception:
            return {}
    return {}


def save_next_chapter_guidance_cache(ch_dir: str, guidance: dict) -> None:
    if not ch_dir or not guidance:
        return
    try:
        write_text_file(get_next_chapter_guidance_cache_path(ch_dir), json.dumps(guidance, ensure_ascii=False, indent=2) + "\n")
    except Exception:
        pass


def build_next_chapter_guidance_by_engine(
    *,
    ch_dir: str,
    next_theme: str,
    next_source_text: str,
    toc_text: str = "",
    engine: str = "",
    logger=None,
    check_cancel=None,
    grok_key: str = "",
    gemini_key: str = "",
    openai_key: str = "",
    chatshare_key: str = "",
    web_manual: bool = False,
) -> dict:
    """用下一章真实原文生成可写入结尾的安全预告信息，并缓存。"""
    cached = load_next_chapter_guidance_cache(ch_dir) if ch_dir else {}
    if cached and str(cached.get("next_theme") or "").strip():
        return cached
    if not clean_next_chapter_source_excerpt(next_source_text, 500):
        return {
            "next_theme": str(next_theme or "下一章").strip() or "下一章",
            "transition_bridge": "",
            "mechanism_preview": "",
            "allowed_bridge_question": "",
            "relevance_example": "",
            "evidence_terms": [],
            "forbidden_claims": [],
            "has_verified_source": False,
        }
    prompt = build_next_chapter_guidance_prompt(next_theme, next_source_text, toc_text=toc_text)
    if not str(prompt or "").strip():
        guidance = {
            "next_theme": str(next_theme or "下一章").strip() or "下一章",
            "transition_bridge": "",
            "mechanism_preview": "",
            "allowed_bridge_question": "",
            "relevance_example": "",
            "evidence_terms": [],
            "forbidden_claims": [],
            "has_verified_source": False,
        }
        save_next_chapter_guidance_cache(ch_dir, guidance)
        if logger:
            logger("🪶 下一章校验提示词为空，已跳过额外校验 API。")
        return guidance
    if ch_dir:
        try:
            write_text_file(os.path.join(ch_dir, "0_下一章真实内容校验提示词.txt"), prompt + "\n")
        except Exception:
            pass
    if web_manual:
        # 网页手动模式下不强制多卡一步；主脚本提示词仍会附带下一章真实原文块。
        guidance = {
            "next_theme": str(next_theme or "下一章").strip() or "下一章",
            "mechanism_preview": "",
            "relevance_example": "",
            "evidence_terms": [],
            "has_verified_source": True,
        }
        save_next_chapter_guidance_cache(ch_dir, guidance)
        return guidance
    try:
        if logger:
            logger(f"🔍 正在根据下一章真实内容生成结尾预告校验信息：{next_theme}")
        result = generate_text_by_engine(
            engine,
            prompt,
            logger,
            check_cancel=check_cancel,
            grok_key=grok_key,
            gemini_key=gemini_key,
            openai_key=openai_key,
            chatshare_key=chatshare_key,
        )
        guidance = parse_next_chapter_guidance_json(result, fallback_theme=next_theme)
        guidance["has_verified_source"] = True
    except Exception as e:
        if logger:
            logger(f"⚠️ 下一章预告校验生成失败：{str(e)[:120]}；将只使用下一章标题作保守预告。")
        guidance = parse_next_chapter_guidance_json("", fallback_theme=next_theme)
    save_next_chapter_guidance_cache(ch_dir, guidance)
    return guidance


def build_next_chapter_verification_block(next_theme: str, next_source_text: str, guidance: dict | None = None) -> str:
    """构建追加到脚本生成/润色提示词里的下一章事实边界。"""
    guidance = dict(guidance or {})
    src = clean_next_chapter_source_excerpt(next_source_text, NEXT_CHAPTER_CONTEXT_CHAR_LIMIT)
    bridge = str(guidance.get("transition_bridge") or "").strip()
    preview = str(guidance.get("mechanism_preview") or "").strip()
    question = str(guidance.get("allowed_bridge_question") or "").strip()
    example = str(guidance.get("relevance_example") or "").strip()
    terms = ", ".join([str(x) for x in guidance.get("evidence_terms") or [] if str(x).strip()])
    forbidden = "；".join([str(x) for x in guidance.get("forbidden_claims") or [] if str(x).strip()])
    if not src:
        return (
            "【下一章结尾预告事实边界｜强保守模式】\n"
            f"程序识别出的下一正文章节：{next_theme}\n"
            "没有可用的下一章真实原文摘录。结尾只能写：本章已回答什么、下一章转向哪个文件夹小标题、关注点赞分享。"
            "不得写具体机制、脑区、实验、疾病、生活例子、应用场景或因果关系；不得只凭章节标题联想；不得强行使用‘引出/因此/由此’等强承接词。"
        )
    return (
        "【下一章真实内容校验｜用于保守过渡】\n"
        f"程序识别出的下一正文章节：{next_theme}\n"
        f"核准的承接逻辑：{bridge or '无；不得强行建立承接关系，只能使用中性章节过渡'}\n"
        f"核准的下一章核心预告：{preview or '无；如果没有原文支持，不要写具体机制'}\n"
        f"核准的开放式引子问题：{question or '无；如果没有原文支持，只能提出标题级问题'}\n"
        f"核准的具体例子素材：{example or '无；如果没有原文支持，不要写具体例子'}\n"
        f"下一章原文关键词：{terms or '以摘录为准'}\n"
        f"禁止误写的无依据推断：{forbidden or '不得新增下一章摘录没有明确支持的任何机制、脑区、实验、疾病、生活例子或应用场景'}\n"
        "\n硬性要求：\n"
        "1. 最后一页先回扣本章已经讲过的结论或未解决问题；若与下一章没有明确逻辑关系，只能用中性章节过渡，不得强行写成‘引出/因此/由此’。\n"
        "2. 下一章预告只允许使用上面核准信息和下面的下一章真实原文摘录；不得只凭章节标题、常识或模型联想。\n"
        "3. 结尾只能保留一个清楚的问题或一句保守预告；不得堆多个问题，不得写长段悬念，不得写“揭晓/真相/秘密/震撼”。\n"
        f"4. 如果无法确认承接关系，就写成保守句：‘本章到这里回答了……。下一章将讨论{next_theme}。关注我们，点赞、分享给对脑科学感兴趣的朋友，下一章继续讲。’不得写“顺着这条线继续看”等空泛指代。\n"
        "5. 不得编造下一章没有描述的机制、例子或应用；不得把可能性说成确定结论。\n\n"
        "【下一章真实原文摘录】\n"
        f"{src}"
    )


def questionize_relevance_example(example: str) -> str:
    """把下一章预告里的具体例子改写成疑问句，用于结尾吊起读者兴趣。"""
    ex = str(example or "").strip()
    ex = re.sub(r"^(?:例如|比如|比方说|像是)\s*[，,：:]*\s*", "", ex)
    ex = ex.strip(" \t\n\r。；;！!？?")
    if not ex:
        return ""
    if re.match(r"^(?:为什么|为何|怎样|怎么|如何|是否|能否|会不会|什么|哪|谁|我们能否|你是否|你有没有)", ex):
        return ex.rstrip("。；;！!") + "？"
    return f"{ex}，这背后的神经机制是什么？"


def compose_verified_follow_sentence(next_theme: str, guidance: dict | None = None) -> str:
    """根据已校验的下一章信息，生成最终关注句；只做保守过渡，不做自由推断。"""
    guidance = dict(guidance or {})
    theme_raw = str(guidance.get("next_theme") or next_theme or "下一章").strip() or "下一章"
    theme = strip_chapter_number_for_speech_title(theme_raw) or theme_raw
    bridge = str(guidance.get("transition_bridge") or "").strip().strip("。；;")
    preview = str(guidance.get("mechanism_preview") or "").strip().strip("。；;")
    question = str(guidance.get("allowed_bridge_question") or "").strip().strip("。；;！？?")
    cta = "关注我们，点赞、分享给对脑科学感兴趣的朋友，下一章继续讲。"
    if bridge and question:
        return f"{bridge}。{question}？{cta}"
    if bridge and preview:
        return f"{bridge}。下一章将讨论{theme}：{preview}。{cta}"
    if preview:
        return f"下一章将讨论{theme}：{preview}。{cta}"
    return f"下一章将讨论{theme}。{cta}"


def normalize_next_chapter_transition_and_cta(voiceover_text: str, next_theme: str = "", logger=None) -> str:
    """本地兜底：避免结尾强行承接，并把关注句统一为关注/点赞/分享。

    只改写原有句子内部，不新增、不删除、不合并、不拆分，保持逐句锁定结构。
    """
    text = str(voiceover_text or "")
    if not text.strip():
        return text
    theme_raw = str(next_theme or "").strip() or "下一章"
    theme = strip_chapter_number_for_speech_title(theme_raw) or theme_raw
    cta = "关注我们，点赞、分享给对脑科学感兴趣的朋友，下一章继续讲。"
    changed = False
    lines = text.splitlines()
    prefix_re = r"^(?P<prefix>\s*(?:【[^】]{1,32}】|\[[^\]]{1,32}\])?\s*)"
    strong_bridge_re = re.compile(
        prefix_re + r"(?:但|不过|而)?(?:这也|这就|这|由此|因此)\s*(?:自然)?(?:引出|带来|提出|留下)\s*(?:了|出)?(?:下一个|新的|下一步)?问题\s*[：:，,]?\s*"
    )
    redundant_system_re = re.compile(
        prefix_re + r"当前章节聚焦于(?P<focus>[^，。；;]+)[，,]\s*(?P=focus)与(?P<next_obj>[^，。；;]+)同属[^，。；;]*[，,]\s*下一章(?:将|会)?(?:探讨|讨论|转向)(?P<topic>[^。；;！!？?]+)[。；;]?\s*$"
    )
    # 结尾常见误写：模型把“本章”误称为“上一章”，或在上一句已经总结本章后，
    # 下一句又重复“本章/上一章介绍了……，下一章……”。这里只保留下一章过渡，
    # 不新增、不删句、不合并句，保持逐句锁定。
    prev_or_current_recap_then_next_re = re.compile(
        prefix_re
        + r"(?:上一章|上章|前一章|本章|这一章|当前章节)"
        + r"(?:已经|主要|先|重点|系统地|简要)?"
        + r"(?:介绍|讲述|讨论|聚焦|说明|梳理|回答|解释|分析|讲清楚|讲了)了?"
        + r"[^，。；;！!？?]{1,120}[，,；;]\s*"
        + r"(?P<next>下一章(?:将|会|，|我们|继续|转向|聚焦|讨论|探讨)[^。；;！!？?]*[。；;！!？?]?)\s*$"
    )
    wrong_previous_chapter_re = re.compile(prefix_re + r"上一章(?=(?:已经|主要|先|重点|系统地|简要)?(?:介绍|讲述|讨论|聚焦|说明|梳理|回答|解释|分析|讲清楚|讲了))")
    for i, line in enumerate(lines):
        old = line
        recap_m = prev_or_current_recap_then_next_re.match(line)
        if recap_m:
            line = f"{recap_m.group('prefix')}{recap_m.group('next').strip()}"
        else:
            # 如果仍出现“上一章介绍了……”，在结尾语境下改为“本章……”，避免把当前章说错。
            line = wrong_previous_chapter_re.sub(lambda mm: mm.group('prefix') + "本章", line)
        m = strong_bridge_re.match(line)
        if m:
            rest = line[m.end():].lstrip()
            prev_line = lines[i - 1] if i > 0 else ""
            if rest and "下一章" in prev_line:
                line = f"{m.group('prefix')}{rest}"
            else:
                sep = "：" if rest else "。"
                line = f"{m.group('prefix')}下一章将讨论{theme}{sep}{rest}"
        line = redundant_system_re.sub(
            lambda mm: f"{mm.group('prefix')}下一章将讨论{mm.group('topic').strip()}。",
            line,
        )
        vague_next_re = re.compile(
            prefix_re + r"(?:下一集|下集|下一章|下章|接下来)(?:，|,)?\s*(?:我们)?(?:会|将|继续)?(?:顺着|沿着|接着)?(?:这条线|这条思路|这个问题|这一路径|这个脉络)(?:继续)?(?:看|讨论|展开|追问|讲下去)?[。；;！!？?]?\s*$"
        )
        if vague_next_re.match(line):
            line = f"{vague_next_re.match(line).group('prefix')}下一章将讨论{theme}。"
        # 如果模型把下一章标题写成“第28章 Auditory Processing...”，
        # 而程序已拿到稳定中文标题，则在原句内部替换为中文小标题。
        if contains_cjk_text(theme) and "下一章" in line and re.search(r"[A-Za-z]{3,}", line):
            line = re.sub(
                prefix_re + r"下一章(?:，|,)?\s*(?:我们)?(?:将|会)?(?:转向|聚焦于|聚焦|探讨|讨论|进入|来到)\s*(?:第\s*\d+\s*章\s*)?[^。；;！!？?]*([。；;！!？?])?\s*$",
                lambda mm: f"{mm.group('prefix')}下一章将讨论{theme}{mm.group(2) or '。'}",
                line,
            )
        if "关注我们" in line and ("下一章继续讲" in line or "下章继续讲" in line or "下一章" in line):
            if "点赞" not in line or "分享" not in line:
                lead_m = re.match(prefix_re, line)
                lead = lead_m.group('prefix') if lead_m else ""
                line = lead + cta
            else:
                line = re.sub(r"关注我们[，,、\s]*(?:请)?", "关注我们，", line)
        if line != old:
            changed = True
            lines[i] = line
    out = "\n".join(lines)
    if text.endswith("\n"):
        out += "\n"
    if changed and logger:
        logger("✅ 已本地优化结尾过渡与关注/点赞/分享引导，保持逐句数量不变。")
    return out

def enforce_verified_next_chapter_ending(voiceover_text: str, next_theme: str, guidance: dict | None = None, logger=None) -> str:
    """逐句锁定模式下不再本地追加或替换结尾句。

    旧逻辑会在模型没有写关注句时自动追加下一章提示，导致 LRC 句子数量变化、图文对应错位。
    现在下一章信息只在润色提示词里作为校对材料，保存阶段绝不增删句子。
    """
    text = str(voiceover_text or "").strip()
    if logger:
        logger("🔒 逐句锁定模式：不本地追加或改写结尾句，避免改变句子数量和图片对应。")
    return text + ("\n" if text else "")


def format_toc_for_prompt(toc: list, current_index: int | None = None, max_chars: int = 12000) -> str:
    """把 PDF 书签目录整理为可直接喂给大模型的上下文，并标出当前正文章节和下一个正文章节。"""

    toc = toc or []
    next_index = find_next_scriptable_chapter_index(toc, current_index) if current_index is not None else None
    lines = [
        "# 书籍目录信息",
        "说明：本目录由 PDF 书签提取。CURRENT 表示当前正文章节，NEXT 表示程序跳过 Part/Glossary/References 后识别出的下一正文章节。",
        "用途：只用于判断全书位置、结尾预告和章节衔接；不要把整段目录直接写入口播台词。",
        "",
    ]
    for i, ch in enumerate(toc):
        title = str(ch.get("title", "")).strip()
        if not title:
            continue
        level = int(ch.get("level", 1) or 1)
        page = ch.get("page", "")
        indent = "  " * max(0, level - 1)
        marks = []
        if current_index is not None and i == current_index:
            marks.append("CURRENT")
        if next_index is not None and i == next_index:
            marks.append("NEXT")
        mark_text = (" [" + ", ".join(marks) + "]") if marks else ""
        page_text = f"p.{page}" if page else "p.?"
        if is_scriptable_chapter_title(title):
            meta = parse_chapter_title_metadata(title, i)
            chapter_no = meta.get("chapter_number") or infer_chapter_number_from_title(title, i)
            display_title = meta.get("title_clean") or title
        else:
            chapter_no = "目录分部" if is_part_toc_title(title) else "非正文条目"
            display_title = title
        lines.append(f"{i + 1:03d}. {indent}{chapter_no} | {page_text} | level {level}{mark_text} | {display_title}")
    text = "\n".join(lines).strip()
    if len(text) <= max_chars:
        return text
    # 目录太长时，保留当前章节附近，并附带首尾信息。
    if current_index is None:
        return text[:max_chars].rstrip() + "\n...（目录过长，后续已截断）"
    window = 25
    selected = []
    for i, ch in enumerate(toc):
        if i < 8 or abs(i - current_index) <= window or i >= len(toc) - 8:
            selected.append(ch)
    compact = format_toc_for_prompt(selected, None, max_chars=max_chars - 200)
    return compact + f"\n\n...（完整目录过长，已保留当前章节前后约 {window} 项、开头和结尾；当前章节原始目录位置：{current_index + 1}）"

def save_toc_text_for_model(out_dir: str, toc: list, current_index: int | None = None, filename: str = "0_目录信息_给大模型.txt", logger=None) -> str:
    """保存喂给大模型的目录上下文，便于复盘提示词来源。"""
    os.makedirs(out_dir, exist_ok=True)
    toc_text = format_toc_for_prompt(toc, current_index=current_index)
    path = os.path.join(out_dir, filename)
    write_text_file(path, toc_text + "\n")
    if logger:
        logger(f"🗂️ 目录信息已保存：{path}")
    return path

def build_review_polish_prompt(script_text: str, source_text: str = "", prompt_template: str = "", toc_text: str = "", next_theme: str = "") -> str:
    """生成终审/台词润色提示词。

    v126：润色阶段改为“逐句锁定”模式。模型只能按字母标记逐句润色，
    不能改变句子数量、顺序和 LRC 配图锚点对应关系。
    """
    locked_rows = _format_locked_voiceover_rows_for_prompt(script_text or "")
    if not locked_rows:
        return ""

    # 科学著作解读单风格：终审只做科学旁白保守润色，不再添加非科学内容模板。
    style_rules = (
        "5. 只按科学著作解读润色：术语准确、机制清楚、证据边界明确；不得改成与科学著作解读无关的表达、鸡汤或营销金句。\n"
        "6. 保留逐句结构和所有图号；只修语病、重复、AI味和不自然表达，不新增事实。\n"
    )

    default_line_lock_rules = (
        "【逐句锁定润色硬规则】\n"
        "待润色台词已经按图片对应关系逐句标记为 [A]、[B]、[C]。你必须一句一句润色：\n"
        "1. 输入多少行，输出必须多少行；不得合并、拆分、删除、增写。\n"
        "2. 每个字母标记只能对应原标记的那一句，顺序不能变化。\n"
        "3. 内部逐句润色阶段，所有 LRC 配图锚点必须原样保留在原字母标记后的行首，不能删除、改号、移动；A1 封面不需要台词锚点；最终 .lrc 导出时程序会把配图锚点拆成独立一行，不与台词合并。\n"
        "4. 不要输出标题、解释、总结、Markdown、下一章预告段或额外说明。\n"
        + style_rules +
        "下一章信息只可用于校对原本已存在的下一期提示句，不可新增任何句子。\n"
        "如果模板或用户要求写得很模糊，例如‘更有故事感’‘更抓人’‘更高级’，请优先转化为‘更自然、更有处境感、更少解读腔’，不要转化为浮夸、强刺激或金句化；不要输出策略说明。\n"
    )
    line_lock_rules = render_prompt_fragment(
        "voiceover_polish_runtime_prefix.md",
        {"style_rules": style_rules},
        fallback=default_line_lock_rules,
    )
    source_excerpt = truncate_context(source_text or "", 18000)
    locked_values = {
        "source_text": source_excerpt,
        "voiceover_text": locked_rows,
        "script_text": locked_rows,
        "toc_text": toc_text or "",
        "table_of_contents": toc_text or "",
        "next_theme": next_theme or "",
        "next_preview": os.environ.get("QUANLAN_NEXT_PREVIEW", ""),
        "next_relevance_example": os.environ.get("QUANLAN_NEXT_RELEVANCE_EXAMPLE", ""),
    }

    if prompt_template:
        rendered_prompt = render_prompt_template(prompt_template, locked_values)
        # 即使外部模板写得宽，也在最前面锁住结构；如果模板没有引用 voiceover_text，则在末尾补上锁定清单。
        if "{voiceover_text}" not in prompt_template and "{{voiceover_text}}" not in prompt_template and "{script_text}" not in prompt_template and "{{script_text}}" not in prompt_template:
            rendered_prompt += "\n\n【待逐句润色台词】\n" + locked_rows
        return line_lock_rules + "\n\n" + rendered_prompt + "\n\n【最终输出要求】\n只输出从 [A]、[B]、[C] 到最后一行的逐句润色结果；不要使用 [001]/[002] 数字序号。"

    return build_line_locked_voiceover_polish_prompt(script_text, source_text=source_text, toc_text=toc_text, next_theme=next_theme)
