# Auto-generated split runtime module.
# Source: backup/AutoMediaProducer_integrated_postprocess_spec.py lines 14336-16264.
# Do not edit this file alone; edit the canonical source and run tools/sync_split_runtime.py.



# Desktop GUI has been removed from this Web-only project.
# Keep this module as the CLI/headless entrypoint used by the Web workbench.

def _run_science_classic_headless(pdf_path: str = "", out_dir: str = "", test_b_image_limit: int = 0) -> int:
    global ui_manager
    _apply_shared_model_config_for_headless()
    slot = _first_task_page_slot()
    model_scheme = load_model_scheme()
    pdf_path = _headless_clean_path(pdf_path or slot.get("pdf_path") or slot.get("current_pdf_path") or "")
    out_dir = _headless_clean_path(out_dir or slot.get("out_dir") or BASE_SAVE_FOLDER)
    raw_toc = slot.get("current_toc") if isinstance(slot.get("current_toc"), list) else []
    current_toc = [dict(ch) if isinstance(ch, dict) else ch for ch in raw_toc]
    limit = max(0, int(test_b_image_limit or slot.get("test_b_image_limit", 0) or 0))
    if limit:
        first_selected = False
        for ch in current_toc:
            if not isinstance(ch, dict):
                continue
            keep = (
                not first_selected
                and bool(ch.get("selected"))
                and is_scriptable_chapter_title(ch.get("title", ""))
            )
            ch["selected"] = keep
            first_selected = first_selected or keep
    selected_count = len([ch for ch in current_toc if isinstance(ch, dict) and ch.get("selected")])
    if not pdf_path or not os.path.exists(pdf_path):
        print(f"ERROR: science classic PDF not found: {pdf_path}", flush=True)
        return 2
    if not current_toc or selected_count <= 0:
        print("ERROR: science classic TOC is empty or has no selected chapters. Read TOC and select chapters in Web first.", flush=True)
        return 3
    os.makedirs(out_dir, exist_ok=True)
    job_state = make_book_task_state(0)
    job_state.update({
        "slot_index": 0,
        "slot_label": "WebScienceClassic",
        "is_running": True,
        "current_toc": current_toc,
        "current_pdf_path": pdf_path,
        "pdf_path": pdf_path,
        "out_dir": out_dir,
        "content_style": normalize_content_style(slot.get("content_style") or model_scheme.get("content_style", get_active_content_style())),
        "text_engine": slot.get("text_engine") or model_scheme.get("text_engine", "GPT-5.5"),
        "review_engine": slot.get("review_engine") or model_scheme.get("review_engine", DEFAULT_MODEL_SCHEME["review_engine"]),
        "image_engine": slot.get("image_engine") or model_scheme.get("image_engine", IMAGE_ENGINE_GPT_IMAGE2),
        "call_mode": slot.get("call_mode") or model_scheme.get("call_mode", WEB_CALL_MODE_API),
        "log_lines": [],
    })
    ui_manager = _HeadlessScienceManager(out_dir)
    print(f"Web science classic job started: PDF={pdf_path}", flush=True)
    print(f"Output folder: {out_dir}", flush=True)
    print(f"Selected chapters: {selected_count} / TOC total: {len(current_toc)}", flush=True)
    if limit:
        print(f"Test-B mode: limited to {limit} B image(s) and the first selected scriptable chapter.", flush=True)
    threading.Thread(target=worker_logic, daemon=True, name="QuanLanHeadlessWorker-1").start()
    task_queue.put({
        "action": "START_PIPELINE",
        "job_state": job_state,
        "slot_index": 0,
        "out_dir": out_dir,
        "do_parse": bool(slot.get("flow_parse", model_scheme.get("flow_parse", True))),
        "do_script": bool(slot.get("flow_script", model_scheme.get("flow_script", True))),
        "do_image": bool(slot.get("flow_image", model_scheme.get("flow_image", True))),
        "clear_existing_images": bool(slot.get("clear_existing_images_before_draw", model_scheme.get("clear_existing_images_before_draw", False))),
        "test_b_image_limit": limit,
        "direct_pdf_to_llm": False,
        "text_engine": job_state["text_engine"],
        "review_engine": job_state["review_engine"],
        "image_engine": job_state["image_engine"],
        "call_mode": job_state["call_mode"],
        "grok_key": load_grok_api_key(),
        "gemini_key": load_gemini_api_key(),
        "openai_key": load_openai_api_key(),
        "image_key": load_image_api_key(),
        "deepseek_key": load_deepseek_api_key(),
        "content_style": job_state["content_style"],
        "prompt_templates": load_prompt_templates(job_state["content_style"], DEFAULT_PROMPT_SCOPE),
        "email_after_completion": bool(slot.get("email_after_completion", model_scheme.get("email_after_completion", False))),
        "email_recipient": normalize_email_recipient(slot.get("email_recipient", model_scheme.get("email_recipient", ""))),
    })
    task_queue.join()
    ok, message = _validate_headless_science_outputs(out_dir, current_toc)
    if not ok:
        print(f"ERROR: science classic output incomplete: {message}", flush=True)
        return 4
    print("Science classic output validation passed: script and image assets found.", flush=True)
    return 0


def run_cli_or_ui():
    """Web-only CLI entrypoint. Desktop GUI fallback has been removed."""
    import argparse
    import sys

    def _safe_console_print(message=""):
        encoding = getattr(sys.stdout, "encoding", None) or "utf-8"
        safe_message = str(message).encode(encoding, errors="replace").decode(encoding, errors="replace")
        print(safe_message)

    parser = argparse.ArgumentParser(description="全澜脑科学 AutoMedia Producer")
    parser.add_argument("--postprocess-folder", dest="postprocess_folder", default="", help="只对指定图片文件夹执行统一公共元素后处理")
    parser.add_argument("--postprocess-role", dest="postprocess_role", default="auto", help="auto/cover/content/brand/tweet")
    parser.add_argument("--prompt-file", dest="prompt_file", default="", help="可选：绘图提示词文件，用于匹配封面标题和页型")
    parser.add_argument("--content-style", dest="content_style", default="", choices=CONTENT_STYLE_OPTIONS, help="内容风格已锁定：科学经典解读")
    parser.add_argument("--recursive", action="store_true", help="递归处理子文件夹；默认只处理当前文件夹")
    parser.add_argument("--show-naming-rules", action="store_true", help="只打印手动生成图片命名规则")
    parser.add_argument("--daily-research-digest", action="store_true", help="生成“每日研究速递”文献卡片口播短视频素材")
    parser.add_argument("--daily-build-article-list", action="store_true", help="只补每日研究速递文献清单，不生成素材")
    parser.add_argument("--daily-out-dir", default="", help="每日研究速递输出目录；默认输出到 chapter_pdf_direct_output/每日研究速递/日期")
    parser.add_argument("--daily-days", type=int, default=14, help="检索最近多少天的 PubMed 文献，默认 14")
    parser.add_argument("--daily-max-articles", type=int, default=5, help="每日研究速递最多选取几篇文章，默认 5")
    parser.add_argument("--daily-issue-count", type=int, default=0, help="清单续做本次最多生成几期；0 表示续做到清单用完")
    parser.add_argument("--daily-journals", default="", help="逗号分隔的期刊列表；默认使用内置神经科学顶刊列表")
    parser.add_argument("--daily-article-list", default="", help="从已有文献清单 JSON 续做；可传 00_文献信息.json 或所在目录")
    parser.add_argument("--daily-continue-until-exhausted", action="store_true", help="从已有文献清单连续制作新素材，直到清单用完")
    parser.add_argument("--daily-resume-existing", action="store_true", help="从已有档期文件夹继续补齐未完成的每日研究速递步骤")
    parser.add_argument("--daily-text-engine", default="GPT-5.5", choices=TEXT_ENGINE_OPTIONS, help="每日研究速递翻译/结构化初稿模型，默认 GPT-5.5")
    parser.add_argument("--daily-polish-engine", default="GPT-5.5", choices=TEXT_ENGINE_OPTIONS, help="每日研究速递中文终稿润色模型，默认使用总控台同步的 GPT-5.5 通道")
    parser.add_argument("--daily-image-engine", default=IMAGE_ENGINE_GPT_IMAGE2, choices=IMAGE_ENGINE_OPTIONS, help="每日研究速递图片摘要模型，默认 生图专用｜GPT Image 2")
    parser.add_argument("--daily-skip-image-api", action="store_true", help="跳过图片 API，用本地占位图生成卡片，便于测试排版")
    parser.add_argument("--daily-test-b-image-limit", type=int, default=0, help="????????????????????? N ???/B??0 ??????")
    parser.add_argument("--daily-skip-medical-related", action="store_true", help="微信避险：跳过标题或摘要中明显涉及医学、疾病、诊疗、患者或临床外推的论文")
    parser.add_argument("--daily-email", action="store_true", help="每日研究速递生成完成后压缩并发送邮件")
    parser.add_argument("--daily-email-recipient", default="", help="每日研究速递收件邮箱；多个邮箱用逗号分隔")
    parser.add_argument("--science-classic-run", action="store_true", help="Run science classic pipeline from Web without GUI")
    parser.add_argument("--science-pdf", default="", help="Science classic PDF path")
    parser.add_argument("--science-out-dir", default="", help="Science classic output folder")
    parser.add_argument("--science-test-b-image-limit", type=int, default=0, help="Limit B images for Web test mode; 0 means unlimited")
    args = parser.parse_args()
    if args.content_style:
        scheme = load_model_scheme()
        scheme["content_style"] = normalize_content_style(args.content_style)
        save_model_scheme(scheme)
        refresh_postprocess_runtime_config()
    if args.science_classic_run:
        raise SystemExit(_run_science_classic_headless(args.science_pdf, args.science_out_dir, args.science_test_b_image_limit))
    if args.show_naming_rules:
        _safe_console_print(MANUAL_IMAGE_NAMING_RULES.rstrip())
        return
    if args.daily_build_article_list:
        path = build_daily_research_article_list(
            out_dir=args.daily_out_dir,
            days=args.daily_days,
            max_articles=args.daily_max_articles,
            journals=args.daily_journals,
            article_list_path=args.daily_article_list,
            skip_medical_related=bool(args.daily_skip_medical_related),
            logger=_safe_console_print,
        )
        _safe_console_print(f"文献清单已保存：{path}")
        return
    if args.daily_research_digest:
        try:
            run_daily_research_digest(
                out_dir=args.daily_out_dir,
                days=args.daily_days,
                max_articles=args.daily_max_articles,
                journals=args.daily_journals,
                article_list_path=args.daily_article_list,
                continue_until_exhausted=bool(args.daily_continue_until_exhausted),
                issue_count=args.daily_issue_count,
                resume_existing=bool(args.daily_resume_existing),
                text_engine=args.daily_text_engine,
                polish_engine=args.daily_polish_engine,
                image_engine=args.daily_image_engine,
                skip_image_api=bool(args.daily_skip_image_api),
                test_b_image_limit=args.daily_test_b_image_limit,
                skip_medical_related=bool(args.daily_skip_medical_related),
                email_after_completion=bool(args.daily_email),
                email_recipient=args.daily_email_recipient,
                logger=_safe_console_print,
            )
        except Exception as exc:
            if exc.__class__.__name__ == "DailyDigestQualityGateError":
                _safe_console_print(f"每日研究速递未达到完整交付标准：{exc}")
                raise SystemExit(2)
            raise
        return
    if args.postprocess_folder:
        postprocess_image_folder(
            args.postprocess_folder,
            role=args.postprocess_role,
            prompt_file=args.prompt_file,
            recursive=bool(args.recursive),
            logger=_safe_console_print,
        )
        return
    _safe_console_print("桌面 GUI 已移除。请使用 Web 工作台：http://127.0.0.1:8765/assistant/")
    raise SystemExit(0)


if __name__ == "__main__":
    run_cli_or_ui()
